CrocSwap/ambient-ts-app

src/components/Global/SimpleModal/SimpleModal.module.css
There is an issue with the detail cards not centering on smaller devices. This PR should fix that.
_Closes #0000_
=> update detail modals to be centered on page no matter the screen

src/components/Global/Account/AccountTabs/Exchange/ExchangeCard.tsx, src/components/Global/Account/AccountTabs/Wallet/WalletCard.tsx
=> convert ipfs logo uri's to http on portfolio

src/components/Global/TokenSelect/TokenSelect.module.css, src/components/Global/TokenSelectContainer/SoloTokenSelect.module.css, src/components/Global/TokenSelectContainer/SoloTokenSelect.tsx
Add hover state, fix placeholder text colour
_Closes #2346_
=> fix token input UI

src/components/Trade/TradeTabs/Orders/Orders.module.css, src/components/Trade/TradeTabs/Ranges/Ranges.module.css, src/components/Trade/TradeTabs/Transactions/Transactions.module.css, src/components/Trade/TradeTabs/Transactions/Transactions.tsx
Add view more button to transactions when candle is selected
_Closes #0000_
1.
2.
1.
2.
=> fix bug on tx

src/components/Trade/Limit/LimitRate/LimitRate.tsx
There is a current issue with using keyboards on the limit rate. Increasing and decreasing the limit tick while the button is active does not work as expected on a keyboard. This PR should fix that.
_Closes #0000_
1.
2.
1.
2.
=> Limit tick keyboard accessibility

src/components/Global/Tabs/TableMenu/TableMenuComponents/TableMenus.module.css, src/components/Global/Tabs/TableMenu/TableMenuComponents/TransactionsMenu.tsx, src/components/Portfolio/PortfolioBanner/PortfolioBanner.module.css, src/components/Portfolio/PortfolioTabs/PortfolioTabs.module.css, src/components/Trade/TradeTabs/TradeTabs2.module.css, src/components/Trade/TradeTabs/TradeTabs2.tsx, src/components/Trade/TradeTabs/Transactions/Transactions.module.css, src/css/GlobalCssClassnames.css, src/pages/Portfolio/Portfolio.module.css, src/pages/Trade/TradeCharts/TradeCharts.module.css, src/pages/Trade/TradeCharts/TradeChartsComponents/TradeChartsTokenInfo.module.css, src/utils/hooks/useProcessTransaction.ts
Trade table UI changes 
Fix account page trade table pagination styling 
_Closes #2340_
=> Update trade table UI

src/pages/Trade/Reposition/Reposition.tsx
=> bug fix: reposition result calculation

src/App/components/PageHeader/Account/Account.module.css, src/App/components/PageHeader/Account/Account.tsx, src/App/components/PageHeader/Account/WalletDropdown/WalletDropdown.module.css, src/App/components/PageHeader/Account/WalletDropdown/WalletDropdown.tsx, src/utils/tokens/USDC.ts
* Display USDC balance (wallet + exchange, active chain) in the wallet dropdown menu
Closes #2516
1. Connect to a wallet on the current chain
2. Verify accurate USDC balance in the wallet dropdown display
3. Switch to a different chain
4. Verify accurate USDC balance in the wallet dropdown display
1. Fallback values are provided if the user has no balance (no tokens should not crash the app)
2. The wallet dropdown is only available if the user has authenticated with a wallet
No further changes needed
=> complete logic to insert USDC data into wallet dropdown

src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx
fix reposition slider initial position 
Closes #2551
1.
2.
1.
2.
=> fix reposition slider initial position

src/components/Global/Account/AccountTabs/Exchange/ExchangeCard.module.css, src/components/Global/Account/AccountTabs/Wallet/WalletCard.module.css
- Account ui/ux
- Most issues were already dealt with
- new token formatting should handle smaller balances as well
_Closes #2347 
1. Token balances on /Account when ExchangeBalance modal open/closed
2.
1.
2.
=> Account UI/UX changes

src/components/Portfolio/ExchangeBalance/Deposit/DepositCurrencySelector/DepositCurrencySelector.module.css, src/components/Portfolio/ExchangeBalance/Transfer/TransferCurrencySelector/TransferCurrencySelector.module.css, src/components/Portfolio/ExchangeBalance/Withdraw/WithdrawCurrencySelector/WithdrawCurrencySelector.module.css, src/components/Swap/CurrencySelector/CurrencySelector.module.css, src/components/Trade/Limit/LimitCurrencySelector/LimitCurrencySelector.module.css, src/components/Trade/Range/RangeCurrencySelector/RangeCurrencySelector.module.css
=> change padding and added hover states to token selectors

src/components/Trade/TradeTabs/Ranges/Ranges.tsx
Fix bug where range orders do not update
_Closes #2573_
=> Fix use effect dependency

src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.css, src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.tsx, src/contexts/CandleContext.tsx, src/pages/Chart/Chart.tsx
=> merge proven into develop - jul 3

src/App/hooks/usePoolMetadata.ts
This PR increases the number of records retrieved from the pool_txs API endpoint from 80 to 200.
Closes #2598
1.
2.
1.
2.
=> increase number of records for pool transactions on /trade from 80 to 200

src/components/RangeDetails/RangeDetails.tsx, src/components/RangeDetails/RangeDetailsSimplify/RangeDetailsSimplify.tsx
=> display updated position apr in range details

src/App/hooks/usePoolMetadata.ts
Add useEffect to set loading status on token change
**PR NOT CREATED YET**
=> Add useEffect to set loading status on token change

src/App/components/PageHeader/Account/Account.tsx, src/App/functions/getFormattedNumber.ts
updated the wallet dropdown USD value displays to eliminate the duplicate '$' character and use US localized formatting for the values.
new display:
Closes #2614
1.
2.
1.
2.
=> update USD value displays in wallet dropdown

src/components/Trade/Range/RangeCurrencyConverter/RangeCurrencyConverter.tsx
=> fix max button click functionality on range input

src/components/Global/TransactionDetails/TransactionDetails.tsx, src/components/Global/TransactionDetails/TransactionDetailsPriceInfo/TransactionDetailsPriceInfo.tsx
Add current APR to transaction details cards displayed when user clicks a row for a liquidity change transaction on /trade.
_Closes #0000_
1.
2.
1.
2.
=> add APR to transaction details for liquidity changes

public/ambient-token-list.json, src/components/Global/PoolCard/PoolCard.module.css, src/components/Global/PoolCard/PoolCard.tsx, src/contexts/CandleContext.tsx, src/utils/data/defaultTokens.ts, src/utils/data/defaultTopPools.ts
Top Pools listed on the homepage and sidebar should be:
ETH-USDC
ETH-WBTC
ETH-PEPE
USDC-DAI
_Closes #0000_
1.
2.
1.
2.
=> add additional default Top Pools

public/ambient-token-list.json, src/components/Global/Account/AccountTabs/Exchange/ExchangeCard.tsx, src/components/Global/PoolCard/PoolCard.tsx, src/components/Global/TokenIcon/TokenIcon.tsx, src/components/Global/TokenSelect/TokenSelect.tsx, src/components/Global/TokenSelectContainer/SoloTokenImport.tsx, src/components/Portfolio/ExchangeBalance/Deposit/DepositCurrencySelector/DepositCurrencySelector.tsx, src/components/Portfolio/ExchangeBalance/Transfer/TransferCurrencySelector/TransferCurrencySelector.tsx, src/components/Portfolio/ExchangeBalance/Withdraw/WithdrawCurrencySelector/WithdrawCurrencySelector.tsx, src/components/Swap/CurrencySelector/CurrencySelector.tsx, src/components/Trade/Limit/LimitCurrencySelector/LimitCurrencySelector.tsx, src/components/Trade/Range/ConfirmRangeModal/ConfirmRangeModal.tsx, src/components/Trade/Reposition/ConfirmRepositionModal/ConfirmRepositionModal.tsx
Refactor `TokenIcon.tsx` to lazy load token icons with React Suspense app-wide
Three circumstances under which `<NoTokenIcon/>` is returned:
1. Token lacks a logo URI
2. Fetch request to URI has not completed
3. Fetch request to URI has failed
Closes #2656 
1. Open the token select modal while connected to mainnet
3. Scroll through tokens and ensure that performance is adequate
4. Ensure that content doesn't move/flash in the modal as logos are loaded
1. Adequate testing will require a slow internet connection (VPN with a low latency is helpful)
2. Clear cache while testing to make sure improvements aren't due to browser image caching …
=> complete logic to load token logos with react suspense

src/components/Global/Account/AccountTabs/Wallet/Wallet.tsx
fix crash on portfolio
Closes #2530
1.
2.
1.
2.
=> fix portfolio crash on wallet before wallet data arrives

src/components/Home/Landing/Investors.tsx
=> fix investor name

src/contexts/CandleContext.tsx
adds a candle fetch on a 1 minute interval
Closes #2531
1.
2.
1.
2.
=> add candle update on a 1 minute interval

src/App/functions/swap/getPriceImpactString.ts
indicate non-zero very small price impacts as '< 0.01%'
Closes #2670
1. Please verify that small swaps indicate that the price impact is '< 0.01%'
=> indicate non-zero very small price impacts as '< 0.01%'

src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
there appear to have been multiple variables containing the liquidity data in TradeCandleStickChart.tsx
1.
2.
1.
2.
=> remove duplicate liquidity data selector

src/App/components/Sidebar/Sidebar.tsx
Remove autofocus, add tabIndex to prioritize sidebar input in tab order
_Closes #2714_
=> Remove autofocus, add tabIndex to prioritize sidebar input in tab order

src/components/Global/Sidebar/FavoritePools/FavoritePoolsCard.tsx
- Separate PR for fixing the nav from fav pools (this will be refactored in the poolcards pr since top, fav and recent pools share logic)
1.
2.
1.
2.
=> Fix fav pools navigation

src/App/components/Sidebar/Sidebar.tsx
fix bug causing the sidebar to become unexpectedly locked.
Closes #2725
1.
2.
1.
2.
=> fix bug causing opening of the sidebar to save the locked status

src/App/functions/fetchCandleSeries.ts, src/contexts/CandleContext.tsx, src/pages/Chart/Chart.tsx, src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx, src/utils/state/tradeDataSlice.ts
=>  fix candle refresh behavior

src/contexts/CandleContext.tsx, src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
A recent change (shown below) was causing candle duration switching while viewing only historical candles (i.e current candle not in view) to no longer work. 
_Closes #0000_
1.
2.
1.
2.
=> fix duration switching for historical candles

src/components/Global/Analytics/PoolRow.tsx, src/components/Global/Analytics/TopPools.tsx, src/pages/Explore/Explore.tsx
Update top pools to display token symbols, TVL, and Volume on mobile devices.
The addition of pool name does not fit on most smaller devices.
_Closes #0000_
=> update pools display on mobile

src/components/Global/TokenSelectContainer/SoloTokenSelect.tsx
add auto focus for token selector search input
Closes #2767
1. Open token selector from /swap, /trade/, or /account and observe that the search input field is ready for the user to start typing without clicking into the field
2.
1.
2.
=> add auto focus for token selector search input

src/components/Global/TokenSelectContainer/SoloTokenSelect.module.css, src/components/Global/TokenSelectContainer/SoloTokenSelect.tsx
Centered Clear Button
Closes #2686
=> Centered clear button

src/components/Trade/TradeTabs/Orders/Orders.module.css, src/components/Trade/TradeTabs/Ranges/Ranges.module.css, src/components/Trade/TradeTabs/Transactions/Transactions.module.css
Fix pagination footer 
Easiest to see on account page (on develop)
_Closes #2691_
=> Fix pagination footer

src/App/components/PageHeader/Account/Account.tsx, src/App/components/PageHeader/Account/WalletDropdown/WalletDropdown.tsx, src/App/functions/getFormattedNumber.ts, src/components/Global/Account/AccountTabs/Exchange/ExchangeCard.tsx, src/components/Global/Account/AccountTabs/Wallet/WalletCard.tsx, src/components/LimitActionModal/LimitActionModal.tsx, src/components/OrderDetails/OrderDetails.tsx, src/components/OrderDetails/OrderDetailsSimplify/OrderDetailsSimplify.tsx, src/components/OrderDetails/PriceInfo/PriceInfo.tsx, src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx, src/components/Portfolio/ExchangeBalance/Transfer/Transfer.tsx, src/components/Portfolio/ExchangeBalance/Withdraw/Withdraw.tsx, src/components/RangeActionModal/RangeActionModal.tsx, src/components/RangeDetails/PriceInfo/PriceInfo.tsx, src/pages/InitPool/InitPool.tsx, src/pages/Swap/Swap.tsx, src/pages/Trade/Limit/Limit.tsx, src/pages/Trade/Range/Range.tsx, src/pages/Trade/Reposition/Reposition.tsx, src/utils/hooks/useProcessOrder.ts, src/utils/hooks/useProcessTransaction.ts
consolidate USD values
_Closes #2616_
=> consolidate USD values

src/App/functions/getFormattedNumber.ts
Handle negative number formatting
_Closes #2747_
=> Handle negative number formatting

src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx
Changed to utelize number formating
Closes #2627
=> Changed to use Number formating

src/components/Global/TabComponent/TabComponent.module.css, src/components/Portfolio/ExchangeBalance/ExchangeBalance.module.css, src/components/Portfolio/ExchangeBalance/ExchangeBalance.tsx, src/pages/Portfolio/Portfolio.module.css
Exchange balance UI
_Closes #2692_
=> Exchange balance UI

src/App/components/PageHeader/PageHeader.module.css, src/App/components/PageHeader/PageHeader.tsx
=> fix header alignment

src/components/Trade/TradeTabs/Transactions/Transactions.module.css
Decreased width of tooltip, no more dead space
Closes #2783
=> Fixed dead space

src/components/Trade/Limit/LimitRate/LimitRate.tsx
Fix bug with limit rates without leading 0
_Closes #2789_
=> Fix limit rate

src/App/components/Sidebar/SidebarSearchResults/PoolsSearchResults/PoolsSearchResults.tsx, src/App/components/Sidebar/SidebarSearchResults/TxSearchResults/TxSearchResults.tsx, src/App/hooks/useFetchPoolStats.ts, src/components/Global/Sidebar/PoolsListItem.tsx, src/components/Global/Sidebar/SidebarRecentTransactions/SidebarRecentTransactions.tsx, src/utils/data/defaultTokens.ts
update default trade direction from quote->base to base->quote
Closes #2803
1.
2.
1.
2.
=> update default trade direction from quote->base to base->quote

src/App/hooks/useFetchPoolStats.ts, src/components/Global/PoolCard/PoolCard.tsx, src/contexts/UserPreferenceContext.tsx
prevent momentary duplication of ETH logo on /trade page loads
Closes #2818
1.
2.
1.
2.
=> prevent momentary duplication of ETH logo on /trade page loads

src/App/functions/fetchCandleSeries.ts, src/contexts/CandleContext.tsx, src/contexts/TradeTableContext.tsx, src/pages/Trade/Trade.tsx
currently, there is an issue in production where the chart for newly created pools without any swaps appears to load endlessly.
example of pool with zero swaps on testnet: 
https://deploy-preview-2825--ambient-finance.netlify.app/trade/market/chain=0x5&tokenA=0x14422ddb3ad47de6b1c655f9f5db62088de0bd1c&tokenB=0x0000000000000000000000000000000000000000
example of pool with one swap on testnet:
https://deploy-preview-2825--ambient-finance.netlify.app/trade/market/chain=0x5&tokenA=0x14422ddb3ad47de6b1c655f9f5db62088de0bd1c&tokenB=0x5cd4958d5cac6ee5aebfca69a0fae5ca48c9fe3a 
example of pool with zero swaps on mainnet (now loading in the PR):
https://us.ambient.finance/trade/market/chain=0x1&tokenA=0x0000000000000000000000000000000000000000&tokenB=0x0d438f3b5175bebc262bf23753c1e53d03432bde …
=> fix handling of empty candle responses

src/index.tsx
fix bug in wagmi causing metamask to appear unavailable
closes #2830
1.
2.
1.
2.
=> fix bug causing metamask to appear unavailable for connection

src/App/App.tsx, src/App/components/WalletModal/WalletModalWagmi.tsx, src/components/Global/Modal/Modal.tsx, src/components/Global/ShareModal/ShareModal.tsx, src/components/Global/Tabs/TableMenu/TableMenuComponents/OrdersMenu.tsx, src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx, src/components/Global/Tabs/TableMenu/TableMenuComponents/TransactionsMenu.tsx, src/components/Global/TokenInput/TokenInputQuantity.tsx, src/components/Global/TokenSelectContainer/SoloTokenSelectModal.tsx, src/components/Global/TransactionDetails/TransactionDetailsModal.tsx, src/components/Global/TransactionSettingsModal/TransactionSettingsModal.tsx, src/components/GlobalModalPortal.tsx, src/components/LimitActionModal/LimitActionModal.tsx, src/components/OrderDetails/OrderDetailsModal/OrderDetailsModal.tsx, src/components/RangeActionModal/RangeActionModal.tsx, src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx, src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx, src/components/Trade/Limit/ConfirmLimitModal/ConfirmLimitModal.tsx, src/components/Trade/Range/ConfirmRangeModal/ConfirmRangeModal.tsx, src/components/Trade/Reposition/ConfirmRepositionModal/ConfirmRepositionModal.tsx, src/components/Trade/Reposition/RepositionHeader/RepositionHeader.tsx, src/components/Trade/TradeModules/TradeModuleHeader.tsx, src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx, src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx, src/pages/Trade/Limit/Limit.tsx, src/pages/Trade/Range/Range.tsx, src/pages/Trade/Reposition/Reposition.tsx, src/pages/Trade/Swap/Swap.tsx
- Adds back the boolean checks that conditionally rendered each modal on the DOM
- still need to investigate why the modals are re-rendering in the first place (assuming the modal's props are the same)
- should also revisit whether we need to pass down the isOpen flag for all modals
Modals should no longer be re-rendering constantly.
_Closes #0000_
1.
2.
1.
2.
=> Conditionally render modal

src/App/hooks/usePoolMetadata.ts
fix pool data loading indicator on trade direction reversal
Closes #2833
1.
2.
1.
2.
=> fix pool data loading indicator on trade direction reversal

src/components/Global/TokenIcon/TokenIcon.tsx, src/components/Global/TokenInput/TokenInputQuantity.tsx
fix token logos disappearing
Closes #2828
1.
2.
1.
2.
=> fix token logos disappearing

src/components/Global/Modal/Modal.module.css
Undo margin auto to fix modal spacing height
=> Fix modal spacing height

src/components/RangeActionModal/RangeActionTokenHeader/RangeActionTokenHeader.module.css, src/components/RangeActionModal/RangeActionTokenHeader/RangeActionTokenHeader.tsx
Swap the icon in remove position to match trade modules:
_Closes #0000_
1.
2.
1.
2.
=> replace icon in remove position

src/components/Global/Modal/Modal.tsx
=> Fix modal escape behaviour

src/components/RangeActionModal/WarningBox/WarningBox.module.css, src/components/RangeActionModal/WarningBox/WarningBox.tsx, src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx, src/components/Trade/TradeModules/TradeConfirmationSkeleton.module.css
This Refactors the current price updated warning in the dom to it's own component that can be reused in the app.
_Closes #0000_
=> Create warning box

src/contexts/AppStateContext.tsx, src/contexts/CandleContext.tsx
fix disappearing chart when user is offline
Closes #2849
1.
2.
1.
2.
=> fix disappearing chart when user is offline

src/components/Global/TokenInput/TokenInputQuantity.tsx, src/components/Portfolio/ExchangeBalance/Deposit/DepositCurrencySelector/DepositCurrencySelector.tsx, src/components/Portfolio/ExchangeBalance/Transfer/TransferCurrencySelector/TransferCurrencySelector.tsx, src/components/Portfolio/ExchangeBalance/Withdraw/WithdrawCurrencySelector/WithdrawCurrencySelector.tsx
exclude exchange balance token selectors from having input disabled when token pair uninitialized
Closes #2852
1.
2.
1.
2.
=> exclude exchange balance token selectors from having input disabled when token pair uninitialized

src/components/Global/TransactionDetails/TransactionDetailsPriceInfo/TransactionDetailsPriceInfo.tsx
order buy/sell in tx details based on denom and trade direction
Closes #2854
1.
2.
1.
2.
=> order buy/sell in tx details based on denom and trade direction

src/pages/Portfolio/Portfolio.module.css, src/pages/Portfolio/Portfolio.tsx
There is a current ui bug on develop that causes the table to not fully extend when viewing another user account:
This PR should address that.
_Closes #0000_
=> fix table width

src/components/Trade/Range/RangeTokenInput/RangeTokenInput.tsx
=> Add useEffect dependency

src/utils/hooks/useUrlParams.ts
=> Token race condition cleanup

src/components/Global/Tabs/TableMenu/TableMenuComponents/OrdersMenu.tsx, src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx, src/components/Global/Tabs/TableMenu/TableMenuComponents/TransactionsMenu.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx
abbreviate 'Copy Trade' button to 'Copy' on Limits/Ranges tables for small screens
_Closes #2863_
1.
2.
1.
2.
=> mobile support: abbreviate 'Copy Trade' button to 'Copy' on Limits/Ranges tables

src/components/Global/TokenInput/TokenInputQuantity.tsx
one side of the token inputs were not getting disabled when user selected an out-of-range set of boundaries
1.
2.
1.
2.
=> re-enable out-of-range input placeholder

src/components/Global/TokenSelectContainer/SoloTokenSelectModal.tsx
disable auto focus for mobile token selection
Closes #2866
1.
2.
1.
2.
=> disable auto focus for mobile token selection

src/utils/data/defaultTokens.ts, src/utils/data/defaultTopPools.ts
replace ETH / USDC with USDT / USDC in Top Pools
Closes #2868
1.
2.
1.
2.
=> replace ETH / USDC with USDT / USDC in Top Pools

docs/release/procedure.md
Add a readme for release procedure
=> Add release procedure readme

src/App/components/PageHeader/PageHeader.module.css, src/App/components/PageHeader/PageHeader.tsx
=> fix page header click

src/App/functions/getLimitOrderData.ts, src/components/Global/OpenOrderStatus/CircularProgressBar.tsx, src/components/Global/OpenOrderStatus/OpenOrderStatus.module.css, src/components/Global/OpenOrderStatus/OpenOrderStatus.tsx, src/components/Global/TransactionDetails/TransactionDetailsPriceInfo/TransactionDetailsPriceInfo.tsx, src/components/Global/TransactionDetails/TransactionDetailsSimplify/TransactionDetailsSimplify.tsx, src/components/LimitActionModal/LimitActionModal.tsx, src/components/LimitActionModal/LimitActionTokenHeader/LimitActionTokenHeader.tsx, src/components/OrderDetails/OrderDetailsModal/OrderDetailsModal.tsx, src/components/OrderDetails/OrderDetailsSimplify/OrderDetailsSimplify.tsx, src/components/OrderDetails/PriceInfo/PriceInfo.tsx, src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx, src/components/Trade/TradeTabs/Orders/orderRowConstants.tsx, src/utils/hooks/useProcessOrder.ts, src/utils/hooks/useProcessTransaction.ts, src/utils/interfaces/LimitOrderIF.ts, src/utils/interfaces/TransactionIF.ts
Fix limit order details in shareable/details card for partially filled orders.
Closes #2872
Closes #2871
1.
2.
1.
2.
=> Fix limit order details display in shareable / details card for partially filled orders

src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx, src/components/Trade/TradeTabs/Orders/Orders.module.css, src/components/Trade/TradeTabs/Orders/Orders.tsx, src/components/Trade/TradeTabs/Orders/orderRowConstants.tsx, src/components/Trade/TradeTabs/Ranges/Leaderboard.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.module.css, src/components/Trade/TradeTabs/Ranges/Ranges.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx, src/components/Trade/TradeTabs/Ranges/rangeRowConstants.tsx, src/components/Trade/TradeTabs/Transactions/Transactions.module.css, src/components/Trade/TradeTabs/Transactions/Transactions.tsx, src/components/Trade/TradeTabs/Transactions/txRowConstants.tsx
=> update column displays in trade/account tables

src/App/components/PageHeader/PageHeader.module.css
=> change header layout to grid on desktop

src/pages/Portfolio/Portfolio.tsx, src/utils/functions/uriToHttp.ts
token logos missing on portfolio (both exchange and wallet balances tables)
broken: https://deploy-preview-2892--ambient-finance.netlify.app/wolsk.eth
fixed: https://deploy-preview-2895--ambient-finance.netlify.app/wolsk.eth
1.
2.
1.
2.
=> fix missing token logos on portfolio

src/App/components/Sidebar/Sidebar.tsx, src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx
=> prevent crash on sidebar search submission

src/components/Trade/TradeTabs/Orders/Orders.module.css, src/components/Trade/TradeTabs/Orders/Orders.tsx, src/components/Trade/TradeTabs/Ranges/Leaderboard.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.tsx, src/components/Trade/TradeTabs/Transactions/Transactions.module.css
=> update ID table header labels

src/components/Global/Tabs/TableMenu/TableMenuComponents/TableMenus.module.css, src/components/Global/Tabs/TableMenu/TableMenuComponents/TransactionsMenu.tsx, src/components/Trade/TradeTabs/Orders/Orders.module.css, src/components/Trade/TradeTabs/Ranges/Ranges.module.css, src/components/Trade/TradeTabs/Transactions/Transactions.module.css
Fix trade menus being cut off
_Closes #2772_
=> Fix table menus being cut off

src/App/components/PageHeader/PageHeader.module.css
add padding to page header to fix notification  from expanding outside viewport
_Closes #0000_
=> add padding to page header

src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx, src/components/Global/Tabs/TableMenu/TableMenuComponents/TableMenus.module.css, src/components/Trade/TradeTabs/Ranges/Leaderboard.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.module.css, src/components/Trade/TradeTabs/Ranges/Ranges.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx
various display fixes for the range and leaderboard tables
=> v1.3 patch - fix table bugs

src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.tsx
Buffer added on transacation details table
Used same period for ranges table and range transaction details card
_Closes #2915
=> 2915 buffer range details card

src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx, src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx, src/components/Trade/TradeTabs/Orders/Orders.module.css, src/components/Trade/TradeTabs/Orders/Orders.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.module.css, src/components/Trade/TradeTabs/Transactions/Transactions.module.css, src/components/Trade/TradeTabs/Transactions/Transactions.tsx, src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx
table displays are off on mobile
1.
2.
1.
2.
=> fix table displays on mobile

src/components/OrderDetails/OrderDetailsSimplify/OrderDetailsSimplify.tsx, src/components/RangeDetails/RangeDetailsSimplify/RangeDetailsSimplify.tsx, src/components/Trade/TradeTabs/Orders/Orders.module.css, src/components/Trade/TradeTabs/Orders/Orders.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.module.css
=> update table column display

src/App/hooks/useFetchPoolStats.ts, src/components/Trade/TableInfo/TableInfo.tsx, src/utils/interfaces/PoolStatIF.ts
Pull live GCGO fields into table info. All fields currently shown stem from tvls.
=> Pull live fields for table info

src/pages/Trade/Limit/Limit.tsx, src/pages/Trade/Range/Range.tsx, src/pages/Trade/Swap/Swap.tsx
fix bypass confirm button bug
Closes #2933
1.
2.
1.
2.
=> fix bypass confirm button bug

src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
fix trade direction reversal bug 
Closes #2943
1.
2.
1.
2.
=> fix trade direction reversal bug

src/components/Trade/TradeTabs/Transactions/Transactions.tsx
fix endless spinner bug when user clicks 'All Transactions' after selecting a candle while logged in without any transactions
Closes #2938
1.
2.
1.
2.
=> fix endless spinner bug

src/components/Portfolio/PortfolioTabs/PortfolioTabs.tsx, src/components/Trade/TradeTabs/Transactions/Transactions.tsx
hide limit cross events in tx query by time and portfolio results
Closes #2936
1.
2.
1.
2.
=> hide limit cross events in tx query by time and portfolio results

src/components/Trade/TradeTabs/Transactions/Transactions.tsx
fix flashing 'No Transactions' message on candle deselection when logged in user does not have transactions
Closes #2940
1.
2.
1.
2.
=> fix flashing message on candle deselection

src/App/App.tsx
Fix mobile footer scrolling on mobile devices.
https://github.com/CrocSwap/ambient-ts-app/issues/2946
_Closes #2946 _
1.open trade table on mobile device
2.mobile footer should stay pinned to bottom of screen
=> fix sidebar sticking on mobile devices

src/pages/Trade/Range/Range.tsx
fix stuck range lines on token pair change
Closes #2953
1.
2.
1.
2.
=> fix stuck range lines on token pair change

src/App/functions/fetchBlockTime.ts, src/components/Global/Account/AccountTabs/Exchange/Exchange.module.css, src/components/Global/Account/AccountTabs/Exchange/Exchange.tsx, src/components/Global/Account/AccountTabs/Wallet/Wallet.tsx, src/components/Global/NotificationCenter/ReceiptDisplay/ReceiptDisplay.tsx, src/components/Global/TabComponent/TabComponent.module.css, src/contexts/CachedDataContext.tsx
switches from using a hardcoded 13.5 block time for calculating elapsed time since a transaction's confirmation (to be displayed in the Notification Center shown in top right after swap) to using a provider call to get the block time based on the block number.
This allows the notification center to show the correct time on layer 2 networks with variable block time.
1.
2.
1.
2.
=> remove hardcoded block time

src/components/Global/TokensArrow/TokensArrow.module.css
Fix  reverse button in swap/limit modules gets stuck in opposite direction when tapped on mobile.
https://github.com/CrocSwap/ambient-ts-app/issues/2912
_Closes #2912_
=> remove animation on mobile screens

src/components/Global/TokenInput/TokenInputQuantity.module.css
=> Fix safari token selector

src/App/hooks/useFetchPoolStats.ts, src/components/Trade/TableInfo/FeaturedBox.tsx, src/components/Trade/TableInfo/TableInfo.tsx, src/contexts/PoolContext.tsx, src/utils/interfaces/PoolStatIF.ts
move pool stats to pool context
Closes #2975
1. switching between trade tabs should not cause data to reload
2. data should get cleared and new data should be fetched when pool changes
1.
2.
=> move pool stats to pool context

src/pages/Chart/Chart.css, src/pages/Chart/Tvl/TvlChart.tsx, src/pages/Trade/Trade.module.css, src/pages/Trade/Trade.tsx, src/pages/Trade/TradeCharts/TradeCharts.module.css
- fixed chart x axis lost on mobile
- space added between Tvl label and Tvl subchart
_Closes #0000_
1.
2.
1.
2.
=> Iphone chart problem - Tvl Space

src/App/hooks/useFetchPoolStats.ts, src/contexts/ExploreContext.tsx, src/contexts/UserPreferenceContext.tsx, src/utils/functions/getMoneynessRank.ts, src/utils/hooks/useProcessOrder.ts, src/utils/hooks/useProcessRange.ts, src/utils/hooks/useProcessTransaction.ts, src/utils/interfaces/NetworkIF.ts
Dynamic moneyness rank using new architecture
_Closes #2990_
=> L2 moneyness

src/App/components/PageHeader/Account/Account.tsx, src/App/components/WalletModal/GateWallet.module.css, src/styled/Components/Header.ts
bugfix: ToS agree button not visible
Closes #2996
1.
2.
1.
2.
=> hotfix: ToS agree button not visible

src/styled/Common.ts
Fixes the styling issue that caused wrong coloring here.
=> Fix semi colons in common styles

src/pages/Trade/TradeCharts/TradeChartsHeader/TradeChartsHeader.tsx, src/utils/functions/printDomToImage.ts
Fix copy chart to clipboard
_Closes #3006_
=> Fix copy chart to clipboard

src/styled/Components/Chart.ts, src/styled/Components/Trade.ts
=> fixed: x axis disappearing on mobile

src/App/hooks/useAppChain.ts
Rename local storage key for current chain from camelCase to SCREAMING_SNAKE_CASE (`chainId` => `CHAIN_ID`)
=> rename local storage key for current chain

src/components/Global/TokensArrow/TokensArrow.tsx, src/styled/Components/TradeModules.ts
=> Fix the display prop on token arrow

src/components/Trade/TradeTabs/Orders/orderRowConstants.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx, src/components/Trade/TradeTabs/Ranges/rangeRowConstants.tsx, src/components/Trade/TradeTabs/Transactions/txRowConstants.tsx
Fix transaction table tooltips
Added tooltip to range date for consistency between transaction/limit/range
_Closes #2952_
=> Fix tooltips

src/App/hooks/usePoolMetadata.ts, src/contexts/TradeTableContext.tsx
reset to pool view when user locks metamask
Closes #3016
1.
2.
1.
2.
=> reset to pool view when user locks metamask

src/components/Global/TabComponent/TabComponent.tsx
fix missing underline animation when switching to Ranges tab. 
Closes #3026
1.
2.
1.
2.
=> fix underline animation when switching to Ranges tab

src/components/Home/Landing/Investors.tsx, src/styled/Components/Home.ts
=> Fix alignment of investors page

src/components/Global/TokenInput/TokenInputQuantity.tsx, src/pages/InitPool/InitPool.tsx, src/utils/regex/exponentialNumRegEx.ts
Init pool input + trade modules input
=> Add commas to token inputs

src/App/functions/fetchTokenPrice.ts, src/constants/index.ts
Swaps out price endpoint off moralis and onto analytics server. No functionality should change. 
_Closes #2785 
Note numbers are approximately equivalent when pulled from either source.
=> Swap Moralis price endpoint for analytics server

src/pages/Chart/Chart.tsx, src/pages/Chart/LimitLine/LimitLineChart.tsx
added command lines for limit sections
_Closes #0000_
1.
2.
1.
2.
=> added comment lines for limit sections

src/App/functions/fetchAprEst.ts, src/App/functions/fetchPoolRecentChanges.ts, src/App/functions/fetchUserRecentChanges.ts, src/App/functions/getLimitOrderData.ts, src/App/functions/getPositionData.ts, src/App/functions/getTransactionData.ts, src/App/hooks/useFetchPoolStats.ts, src/App/hooks/usePoolMetadata.ts, src/components/Global/TransactionDetails/TransactionDetailsModal.tsx, src/components/OrderDetails/OrderDetailsModal/OrderDetailsModal.tsx, src/components/Portfolio/PortfolioTabs/PortfolioTabs.tsx, src/components/RangeActionModal/RangeActionModal.tsx, src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx, src/components/Trade/TradeTabs/TradeTabs2.tsx, src/components/Trade/TradeTabs/Transactions/Transactions.tsx, src/contexts/PoolContext.tsx, src/contexts/TradeTokenContext.tsx, src/contexts/UserDataContext.tsx, src/pages/Trade/Reposition/Reposition.tsx
consolidate provider creation
Closes #3048
1.
2.
1.
2.
=> 3048 - consolidate provider creation

package.json, src/components/Global/Tabs/TableMenu/TableMenuComponents/OrdersMenu.tsx, src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx, src/styled/Components/TransactionTable.ts
hotfix: overlapping text & missing menu button in mobile tables
Closes #3055
1.
2.
1.
2.
=> 3055 hotfix: overlapping text & missing menu button in mobile tables

src/components/Form/TokenInputQuantity.tsx
=> Fix issue where unable to add decimal inputs

src/pages/Chart/Candle/CandleChart.tsx, src/pages/Chart/Chart.tsx
=> Fix buffer on range

src/components/RangeActionModal/RangeActionModal.tsx, src/components/Trade/TradeModules/SubmitTransaction/SubmitTransaction.tsx, src/components/Trade/TradeModules/SubmitTransaction/TransactionSubmitted/TransactionSubmitted.tsx
remove harvest transaction gatekeeping for positions without accumulated fees
Closes #3069
1.
2.
1.
2.
=> remove gatekeeping for harvests without accumulated fees

src/pages/Chart/Axes/yAxis/YaxisCanvas.tsx, src/pages/Chart/Chart.tsx, src/utils/hooks/useHandleSwipeBack.ts
-  Limit and Range labels should be draggable on mobile 
-  Bug fix : Range lines can be updated when click on balance mode for mobile
_Closes #0000_
1.
2.
1.
2.
=> Proven Last Changes - 051023 - Limit and Range labels should be draggable on mobile 

src/index.css
Removed styles in index css that are not used anywhere.
=> Clean up unused css classes in index.css

src/pages/Trade/Swap/Swap.tsx
fix swap initialization
Closes #3091
1.
2.
1.
2.
=> fix swap initialization

src/App/hooks/useAppChain.ts, src/pages/Swap/Swap.tsx
Refactor logic in `useAppChain.ts` file controlling network initialization.
Closes #3090
1. Load the app with both `0x1` and `0x5` URLs
2. Ensure the app always loads the correct URL regardless of network when the new URL is loaded
Test both cases where the new URL changes and does not change the current chain
This code is ugly and not well-written per best practices of React. It is written specifically to minimize changes to the file in question as to minimize difficulty with other ongoing work to refactor how the app manages network data. It should be fixed or discarded with future refactors.
=> complete logic to fix initialization of chain from url when wallet not connected

src/contexts/CandleContext.tsx, src/pages/Chart/Chart.tsx, src/pages/Chart/ChartUtils/zoom.ts
- The problem of not fetching new candles when zooming to the left has been fixed
- Fixed the appearance of the last candle
_Closes #0000_
1.
2.
1.
2.
=> Proven - 10122023

src/components/InitPool/InitPoolExtraInfo/InitPoolExtraInfo.tsx, src/components/LimitActionModal/LimitActionInfo/LimitActionInfo.tsx, src/components/RangeActionModal/RangeActionModal.tsx, src/components/Trade/TradeModules/ExtraInfo/ExtraInfo.tsx
=> hide network fee estimates on L2s

src/components/Trade/TableInfo/FeaturedBox.tsx, src/components/Trade/TableInfo/TableInfo.styles.ts, src/pages/InitPool/InitConfirmation.tsx, src/pages/InitPool/InitSkeleton.tsx
fix button layout and add figma paddings
_Closes #0000_
=> fix button layout and add figma paddings

src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx, src/utils/hooks/useLinkGen.ts
re-add missing lowTick/highTick to url for range copies
copy/add buttons no longer opened advanced mode when clicked on the portfolio
1.
2.
1.
2.
=> fix range copy/add from account

src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRowPlaceholder.tsx
fix range tx placeholder display in transactions table
Closes #3101
1.
2.
1.
2.
=> fix range tx placeholder display

src/App/hooks/useHandleRangeButtonMessage.ts
prevent range mint disabling when token collateral not required
Closes #3108
1.
2.
1.
2.
=> prevent range mint disabling when token collateral not required

src/components/Global/Modal/Modal.module.css, src/contexts/ENSAddressContext.tsx
- Removing the "pushdown" from top bias that modals used to have and instead vertically centering them so that they don't get cut off on smaller laptop screens
Closes #3103
1.
2.
1.
2.
=> Fix bottom of some modals being cut off

src/components/Portfolio/ExchangeBalance/ExchangeBalance.tsx, src/contexts/CrocEnvContext.tsx, src/pages/Portfolio/Portfolio.tsx
use mainnet provider for ENS resolutions on portfolio and exch. balance modules
Closes #3112
1.
2.
1.
2.
=> use mainnet provider for ENS resolutions on portfolio and exch. balance modules

src/components/InitPool/InitPoolExtraInfo/InitPoolExtraInfo.module.css, src/components/InitPool/InitPoolExtraInfo/InitPoolExtraInfo.tsx, src/components/LimitActionModal/LimitActionInfo/LimitActionInfo.tsx, src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx, src/components/Portfolio/ExchangeBalance/Transfer/Transfer.tsx, src/components/Portfolio/ExchangeBalance/Withdraw/Withdraw.tsx, src/components/RangeActionModal/RangeActionModal.tsx, src/pages/Trade/Range/Range.tsx
=> hide gas estimate on non-mainnet chains

src/components/Trade/Limit/LimitRate/LimitRate.tsx, src/pages/Trade/Limit/Limit.tsx
bug fix: cannot set limitTick to zero
Closes #3130
1.
2.
1.
2.
=> bug fix: cannot set limitTick to zero

src/styled/Components/TransactionTable.ts, src/utils/hooks/useProcessOrder.ts, src/utils/hooks/useProcessRange.ts, src/utils/hooks/useProcessTransaction.ts
=> prevent line wrapping in tx table

.github/ISSUE_TEMPLATE/BUG.yml
Add a `'No wallet connected'` option to the bug reporting workflow in the `BUG.yml` file. This is helpful for a user to indicate a bug exists in the app when no wallet is connected in addition to when other specific wallets are connected.
[no related issue - *de minimis* change]
none
none
none
=> add `No wallet connected` option to `BUG.yml` file

src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx, src/styled/Components/Header.ts
add active network to network selector
_Closes #0000_
=> add active network to network selector

src/pages/Home/Home.tsx, src/utils/functions/lookupChainId.ts
* Add logic to `Home.tsx` file to clear invalid search params from the URL bar
* Add logic to `Home.tsx` to process chain identifiers other than `0x` hex strings
* Clean up and annotate recently-added code in `Home.tsx` file 
Closes #3139
Same testing procedures as PR #3139 but also testing action when given unrecognized params in the URL
* fresh load of the app in a new tab vs already being in-session
* wallet connected vs no wallet connected to the platform
* regular browser window vs incognito browser
=> Clear invalid params on index route

src/components/Form/TokenInputWithWalletBalance.tsx, src/components/Form/WalletBalanceSubinfo.tsx
bug fix: max button not appearing when balance in subscript notation
Closes #3141
1.
2.
1.
2.
=> bug fix: max button not appearing when balance in subscript notation

src/components/Global/Analytics/PoolRow.tsx
change token icon size on mobile devices
_Closes #0000_
=> change token icon size on mobile devices

src/App/hooks/usePoolMetadata.ts, src/components/Swap/SwapTokenInput/SwapTokenInput.tsx, src/contexts/TradeTokenContext.tsx
fix swap copy reversal bug from portfolio
Closes #3036
1.
2.
1.
2.
=> fix swap copy reversal bug from portfolio

src/components/Form/TokenInputWithWalletBalance.tsx
=> fix ellipsis bug for usd token input value

src/components/Global/DropdownMenu2/DropdownMenu2.tsx
remove animation for network selector dropdown
Closes #3168
1.
2.
1.
2.
=> remove animation for network selector dropdown

package.json, yarn.lock
=> update scroll logo

src/App/functions/fetchTokenBalances.ts, src/contexts/ChainDataContext.tsx, src/index.tsx, src/pages/Portfolio/Portfolio.tsx
=> fix token balance queries

src/App/functions/fetchTokenPrice.ts
TVL values on scroll.ambient.finance were incorrect due to the price queries via the Analytics server failing for the ERC-20 tokens on scroll.
_Closes #0000_
1.
2.
1.
2.
=> hotfix: TVL values incorrect on scroll network

src/App/components/PageHeader/Account/WalletDropdown/WalletDropdown.tsx, src/App/functions/fetchTokenPrice.ts
=> Fix tvl calc on multi network deploys

src/components/Form/Button.tsx, src/components/Form/Form.styles.ts, src/components/RangeActionModal/WarningBox/WarningBox.tsx, src/pages/InitPool/InitPool.tsx
Add withdraw button on init page
_Closes #3179 _
=> add withdraw button on init page

src/utils/data/tokenListURIs.ts
=> add scroll token list

public/ambient-token-list.json, src/App/hooks/useTopPools.ts, src/contexts/CrocEnvContext.tsx, src/utils/data/defaultTokens.ts, src/utils/data/stablePairs.ts, src/utils/data/tokenListURIs.ts, src/utils/networks/scrollMainnet.ts
=> Add scroll token list restricted

src/App/hooks/useHandleRangeButtonMessage.ts, src/components/Trade/Range/RangeTokenInput/RangeTokenInput.tsx, src/pages/InitPool/InitButton.tsx, src/pages/InitPool/InitConfirmation.tsx, src/pages/InitPool/InitPool.tsx, src/pages/Trade/Range/useRangeInputDisable.tsx
=> fix pool init button disabling when token balance is zero

src/components/Form/TokenInputWithWalletBalance.tsx, src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx
=> reduce eth required to cover gas on scroll

src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx, src/pages/Trade/Limit/Limit.tsx, src/pages/Trade/Swap/Swap.tsx
=> prevent deposits, swaps, and limits when wallet insufficient to cover gas

src/App/components/Sidebar/Sidebar.tsx, src/App/components/Sidebar/SidebarSearchResults/PositionsSearchResults.tsx, src/components/Portfolio/PortfolioTabs/PortfolioTabs.tsx, src/components/Trade/TradeTabs/TradeTabs2.tsx
=> update 'Ranges' to 'Liquidity'

src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx, src/components/Chat/MessagePanel/InputBox/MessageInput.tsx, src/constants/index.ts, src/styled/Common/Text.ts, src/utils/types/chainType.ts, src/utils/types/chainsType.ts, src/utils/types/index.ts
* Change sequence of networks listed in the network selector dropdown (`NetworkSelector.tsx`)
* Add icon to Canto network indicating the resource is external to the platform
* Expand margin CSS options in `Text.ts` file for `<Text />` styled component
Closes #3206
1. Change the app to each of the four networks with no wallet connected and observe behavior
2. Repeat Step (1) with a wallet connected
none
None, ready for merge!
=> Resequence networks in selector

src/App/functions/fetchTokenBalances.ts, src/contexts/ChainDataContext.tsx, src/pages/Portfolio/Portfolio.tsx, src/utils/hooks/useLinkGen.ts
reduce wallet balance API queries to every two minutes
Closes #3209
1.
2.
1.
2.
=> reduce wallet balance API queries to every two minutes

src/App/functions/fetchTokenBalances.ts, src/App/functions/fetchTokenPrice.ts
=> add temporary default value for USDC

src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx
add a ? so the app doesn't crash when a particular chain is not in the network selector
1.
2.
1.
2.
=> prevent app crash from network selector

src/components/Trade/TradeTabs/Transactions/Transactions.tsx, src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx, src/styled/Components/TransactionTable.ts
Make timestamp display on trade tables for medium screens
none
1. View `/trade` route transactions table on a medium-width screen (timestamp should be visible)
2. View `/account` route transactions table on a medium-width screen (timestamp should be visible)
none
None, code is ready for merge.
=> Display transaction timestamp on laptop-sized screen

src/constants/index.ts
=> update fallback analytics url

src/components/Form/TokenInputQuantity.tsx, src/components/Global/InitPoolTokenSelect/InitPoolTokenSelect.tsx, src/components/Global/MultiStepTransaction/StepperComponent.tsx, src/components/Global/TokenSelectContainer/SoloTokenSelect.module.css, src/components/Global/TokenSelectContainer/SoloTokenSelect.tsx, src/css/GlobalCssClassnames.css, src/pages/InitPool/InitPool.tsx
Address  the following requested changes:
https://github.com/CrocSwap/ambient-ts-app/pull/3082#pullrequestreview-1728530932
_Closes #0000_
=> Pool Init Styling Bugs

package.json, src/App/functions/fetchTokenPrice.ts, src/utils/functions/fetchTimeout.ts
Added fetchTimeout in the function utils, for submitting a fetch with a timeout
_Closes #3229
1. price data should load
2. If the analytics server fails, the fetch requests should time out
1.
2.
=> Added in fetchTimeout

src/App/functions/fetchTokenPrice.ts, src/contexts/ChainDataContext.tsx, src/pages/Portfolio/Portfolio.tsx
add timeout for price queries to analytics server
=> add timeout for price queries to analytics server

package.json, src/components/Global/TransactionDetails/TransactionDetailsModal.tsx, src/components/Portfolio/PortfolioTabs/PortfolioTabs.tsx, src/components/RangeActionModal/RangeActionModal.tsx, src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx, src/contexts/UserDataContext.tsx, src/pages/Trade/Reposition/Reposition.tsx
skip ENS fetch for position stats 
Closes #3239
1.
2.
1.
2.
=> skip ENS fetch for position stats

src/components/Form/TokenInputWithWalletBalance.tsx, src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx, src/pages/Trade/Limit/Limit.tsx, src/pages/Trade/Swap/Swap.tsx
increase hardcoded scroll gas buffer to 0.0005 ETH
maximum swap/limit transactions on scroll may fail simulation
1.
2.
1.
2.
=> increase hardcoded scroll gas buffer to 0.0005 ETH

package.json, src/App/functions/fetchTokenPrice.ts, src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
hotfix for bug causing user input like "0.001" to get cleared while the user is typing, if the user pauses while the number would parse to zero like "0.00"
_Closes #0000_
1.
2.
1.
2.
=> bug fix: token a input qty = 0 disappearing

src/pages/Trade/Trade.tsx
* Pass `urlParamMap` to mobile version of trade route
Closes #3251 
1. Navigate to route `/trade/limit` on a desktop-size screen; app should work as expected
2. Repeat on a mobile-sized screen; app should not crash and work as expected
none
None, ready for merge!
=> pass `urlParamMap.ts` to mobile version of trade route

package.json, src/App/functions/fetchTokenPrice.ts
move hardcoded USD values for ETH & USDC to fallback
=> move hardcoded usd values to fallback

src/App/hooks/useCreateRangePosition.ts, src/App/hooks/useSendInit.ts, src/components/Form/TokenInputWithWalletBalance.tsx, src/components/LimitActionModal/LimitActionModal.tsx, src/components/RangeActionModal/RangeActionModal.tsx, src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx, src/components/Trade/Limit/ConfirmLimitModal/ConfirmLimitModal.tsx, src/components/Trade/Range/ConfirmRangeModal/ConfirmRangeModal.tsx, src/components/Trade/Reposition/ConfirmRepositionModal/ConfirmRepositionModal.tsx, src/components/Trade/TradeModules/SubmitTransaction/SubmitTransaction.tsx, src/components/Trade/TradeModules/SubmitTransaction/TransactionException/TransactionException.tsx, src/components/Trade/TradeModules/TradeConfirmationSkeleton.tsx, src/pages/InitPool/InitConfirmation.tsx, src/pages/InitPool/InitPool.tsx, src/pages/Trade/Limit/Limit.tsx, src/pages/Trade/Range/Range.tsx, src/pages/Trade/Reposition/Reposition.tsx, src/pages/Trade/Swap/Swap.tsx
Added the error message received from the RPC node to the exception display when a transaction fails simulation.
_Closes #0000_
1.
2.
1.
2.
=> hotfix: add tx error message

src/components/Trade/TradeTabs/Transactions/Transactions.tsx, src/css/GlobalCssClassnames.css, src/styled/Components/Trade.ts
=> Remove overflow-y causing another scrollbar to appear in trade table

src/components/Form/Chip.tsx, src/components/Global/Tabs/TableMenu/TableMenuComponents/TransactionsMenu.tsx, src/components/Swap/SwapTokenInput/SwapTokenInput.tsx, src/contexts/TradeDataContext.tsx
disable clicking the copy trade button for swaps while the reverse button is disabled.
Closes #3262
1.
2.
1.
2.
=> prevent swap copy when reverse disabled

.gitignore, e2e/example.spec.ts, e2e/helpers/mmask-fetch.ts, e2e/helpers/utils.ts, e2e/init-wallet.test.ts, e2e/swap.test.ts, package.json, playwright.config.ts, yarn.lock
Describe the purpose + content of these changes
Swap test added for dev env.
Dev Dependency changes
REMOVED
"@playwright/test": "^1.21.1", (due to conflicting with added lib)
ADDED
"adm-zip": "^0.5.10", (to unzip metamask extension into folder)
"@types/adm-zip": "^0.5.4",
"playwright": "^1.39.0", to run tests
"superagent": "^8.1.2" to fetch metamask extension from metamask github release
Due to change of playwright lib, some import statements changed on
playwright.config.ts
example.spec.ts
files
helper functions added inside e2e/helpers dir
(mmask-utils will be loaded with metamask related util funcions, for now all util funcs are located in utils.ts)
temporary using files added to .gitignore (metamask folder, metamask.zip and UserData dir that stores test browser data )
To run test …
=> Metamask tests added for last changes

src/App/hooks/useFetchBatch.ts, src/ambient-utils/api/fetchTokenPrice.ts, src/ambient-utils/types/fetchBatch.ts, src/utils/hooks/useProcessOrder.ts, src/utils/hooks/useProcessRange.ts, src/utils/hooks/useProcessTransaction.ts
- Errors thrown by the server would not result in entering the catch block. These changes should address that for fetchTokenPrice and also stricten typing on the fetch batch to handle error cases.
Motivated by first seeing $0.00 for USDC's price on Scroll
NOTE: it seems the batch_requests endpoint as of now does not support fetching prices for USDC
_Closes #0000_
1.
2.
1.
2.
=> Add more robust error checking to fetch batch endpoint

src/components/LimitActionModal/LimitActionModal.tsx, src/components/Trade/TradeModules/SubmitTransaction/SubmitTransaction.tsx, src/components/Trade/TradeModules/SubmitTransaction/TransactionException/TransactionException.tsx
fix claim token quantity/address
Closes #3275
1.
2.
1.
2.
=> fix claim token quantity/address

src/App/hooks/useFetchPoolStats.ts, src/App/hooks/usePoolMetadata.ts, src/App/hooks/usePoolPricing.ts, src/App/hooks/usePoolStats.ts, src/ambient-utils/api/fetchTokenPrice.ts, src/ambient-utils/constants/index.ts, src/ambient-utils/dataLayer/functions/getPoolStats.ts, src/contexts/AppStateContext.tsx, src/contexts/CachedDataContext.tsx, src/contexts/CandleContext.tsx, src/contexts/ExploreContext.tsx
=> add 60s cache for 24h change queries

README.md
Update content in `README.md` for v1.7 release notes
none
no functional changes in this PR
no functional changes in this PR
none
=> update `README.md` file

src/pages/Chart/Chart.tsx
…imit
_Closes #0000_
1.
2.
1.
2.
=> fixed: nogozone boundaries not shown correctly to the user when dragging the limit

package.json, src/components/Chat/MessagePanel/InputBox/MessageInput.tsx, src/components/Chat/MessagePanel/Room/Room.tsx
=> fix chat crash on favorite button click

src/components/Global/ContentContainer/ContentContainer.module.css
fix issue with not being able to scroll to bottom of range module on mobile
=> add dynamic scroll on mobile

src/components/Global/NotificationCenter/NotificationTable/NotificationTable.tsx, src/components/Portfolio/ExchangeBalance/ExchangeBalance.tsx, src/styled/Components/Portfolio.ts
Before:
After:
-----------
Before:
After:
_Closes #0000_
1.
2.
1.
2.
=> Misc Styling updates

src/App/components/Sidebar/SidebarSearchResults/PositionsSearchResults.tsx, src/components/Global/Sidebar/SidebarRangePositions/SidebarRangePositions.tsx, src/components/Global/TabComponent/TabComponent.module.css, src/components/Trade/TradeTabs/PositionsOnlyToggle/PositionsOnlyToggle.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx
fixes issue with automatic scroll to position missing a firstMintTx value
adds missing My Transactions / Limits / Liquidity toggle on mobile
=> Fix table issues

src/components/Global/Modal/Modal.tsx
=> add outside click to modals on mobile screens

src/pages/Chart/Axes/yAxis/YaxisCanvas.tsx, src/pages/Chart/Chart.tsx, src/pages/Chart/ChartUtils/chartUtils.ts
disabled drag and click for limit and range lines/labels according to isConfirmationActive
_Closes #0000_
1.
2.
1.
2.
=> Chart : disabled drag and click for limit and range lines/labels according to isConfirmationActive

src/App/components/Sidebar/SidebarSearchResults/OrdersSearchResults.tsx, src/ambient-utils/types/limitOrder/LimitModalAction.ts, src/ambient-utils/types/limitOrder/index.ts, src/ambient-utils/types/pool/RangeModalAction.ts, src/ambient-utils/types/pool/index.ts, src/components/Global/Sidebar/SidebarLimitOrders/SidebarLimitOrders.tsx, src/components/Global/Tabs/TableMenu/TableMenuComponents/OrdersMenu.tsx, src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx, src/components/Global/Tabs/TableMenu/TableMenuComponents/TransactionsMenu.tsx, src/components/Global/TransactionDetails/TransactionDetailsModal.tsx, src/components/LimitActionModal/LimitActionModal.tsx, src/components/RangeActionModal/RangeActionModal.tsx, src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx, src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx, src/components/Trade/TradeTabs/Orders/Orders.tsx, src/components/Trade/TradeTabs/Ranges/Leaderboard.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx, src/components/Trade/TradeTabs/TableRows.tsx, src/components/Trade/TradeTabs/TradeTabs2.tsx, src/components/Trade/TradeTabs/Transactions/Transactions.tsx, src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx, src/contexts/TradeTableContext.tsx
- Refactor modals attached to individual rows in the Trade Table and Account table to use a single modal instead
_Closes #0000_
1.
2.
1.
2.
=> Update table modals to be consistent as rows get added/removed on /Trade, /Account

package.json, src/components/Trade/Range/ConfirmRangeModal/SelectedRange/SelectedRange.tsx
fix hardcoded fee rate: 
_Closes #0000_
1.
2.
1.
2.
=> hotfix: replace hardcoded fee rate in confirm modal with dynamic fee rate for pool

src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx, src/components/Trade/TradeModules/TradeConfirmationSkeleton.tsx, src/pages/Trade/Swap/Swap.tsx
add price impact to swap confirm modal
_Closes #0000_
=> add price impact to swap confirm modal

src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx, src/components/Trade/Limit/ConfirmLimitModal/ConfirmLimitModal.tsx, src/components/Trade/TradeModules/TradeConfirmationSkeleton.tsx
=> add extra precision in swap/limit confirm modals

src/pages/Chart/Chart.css, src/pages/Chart/Chart.tsx
=> Tooltip Added for Limit and Range Lines During Confirmation

src/contexts/UserDataContext.tsx
added a backup fetch of a user's ENS address from the analytics server when the wagmi hook does not resolve any ENS
these addresses should have been resolved to benwolski.eth
1.
2.
1.
2.
=> add backup ENS resolution from analytics server

src/ambient-utils/api/fetchXp.ts
=> Add map function for future userXp object

src/ambient-utils/constants/networks/ethereumMainnet.ts
this replaces the call to the etherscan gas oracle api with a provider call to retrieve the price of gas on eth mainnet.
=> remove etherscan api call for gas price

src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx, src/components/Trade/TradeTabs/TradeTabs2.tsx, src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx
this PR removes seemingly unnecessary outside click handlers
modals were closing unexpectedly on mobile. a user could not interact with any modal.
1.
2.
1.
2.
=> remove outsideClickHandlers to fix mobile modal interactions

src/components/Chat/ChatPanel.tsx
prevent crash when userAddress is undefined
##
=> fix mobile chat crash when user not logged in

src/App/App.tsx
=> add sidebar on swap small screen

.github/pull_request_template.md, docs/CODING-STYLE.md
Hello again. I accidentally deleted the file that I was planning to correct, so I had to close the file. https://github.com/CrocSwap/ambient-ts-app/pull/3324
I thought it would be better to redo it. Thank you for your understanding. Have a nice day
=> fix typos 

src/pages/Chart/Chart.tsx
=> fixed : disable drag limit when start confirmation

src/ambient-utils/dataLayer/transactions/swap.ts, src/components/Swap/SwapExtraInfo/SwapExtraInfo.tsx, src/components/Swap/SwapTokenInput/SwapTokenInput.tsx, src/pages/Trade/Swap/Swap.tsx
re-added buy transaction support
a bug had been introduced on the Develop branch causing all swaps to be sent as "buy" transactions
note the amount of ETH being sent to the contract here:
1.
2.
1.
2.
=> fix swap bug - all swaps sent as "sell" transactions

src/components/Global/Tabs/TableMenu/TableMenuComponents/OrdersMenu.tsx
Moved the details button to the overflow menu to be consistent.
Details button was appearing on Limits tab (unlike other tabs) and overlapping other information.
1.
2.
1.
2.
=> move order details button to overflow menu

src/components/Global/Tabs/TableMenu/TableMenuComponents/OrdersMenu.tsx
abbreviate the Copy Trade button at larger window sizes
1.
2.
1.
2.
=> prevent overlap on limit tab on account

src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx, src/components/Trade/Range/ConfirmRangeModal/ConfirmRangeModal.tsx, src/components/Trade/Range/ConfirmRangeModal/SelectedRange/SelectedRange.tsx, src/components/Trade/TradeModules/SubmitTransaction/SubmitTransaction.tsx, src/components/Trade/TradeModules/SubmitTransaction/TransactionSubmitted/TransactionSubmitted.tsx, src/components/Trade/TradeModules/TradeConfirmationSkeleton.tsx, src/pages/Trade/Range/Range.tsx
The values outlined below should not change after the user submits the transaction, until the modal is closed or the user clicks 'Reset'.
_Closes #0000_
1.
2.
1.
2.
=> prevent token quantity update after tx sent

src/styled/Components/Trade.ts
Fix page header Z index issue
_Closes #0000_
=> fix header z issue

src/components/Trade/TradeModules/TradeConfirmationSkeleton.tsx
prevent  token quantity updates after swap
_Closes #0000_
1.
2.
1.
2.
=> prevent  token quantity updates after swap (no-modal)

src/components/Swap/SwapExtraInfo/SwapExtraInfo.tsx, src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
increases the maximum positive price impact for a swap from 200% to 1,000,000% before disabling the swap due to insufficient liquidity.
_Closes #0000_
1.
2.
1.
2.
=> allow swaps up to 1,000,000% impact

src/App/hooks/useAppChain.ts
keeps the user on the Swap/Market/Limit/Pool components when they switch networks (but still reverts to the default pool)
_Closes #0000_
1.
2.
1.
2.
=> keep user on same component when switching networks

src/components/Portfolio/PortfolioTabs/PortfolioTabs.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.tsx
fixes a bug where "No Ranges Found" was displaying prematurely when viewing the portfolio of another user.
_Closes #0000_
1.
2.
1.
2.
=> fix early setting of data loading to false for lookup user's limits/liquidity

src/ambient-utils/dataLayer/functions/getFormattedNumber.ts, src/pages/Chart/Axes/yAxis/YaxisCanvas.tsx, src/pages/Chart/Chart.tsx, src/pages/Chart/Draw/DrawCanvas/DrawCanvas.tsx
fix display of small number in D&P box
1.
2.
1.
2.
=> fix display of small number in D&P box

src/pages/Chart/Chart.tsx, src/pages/Chart/Draw/DrawCanvas/DrawCanvas.tsx
added flag to mark D3 event handlers as passive
1.
2.
1.
2.
=> prevent console warnings of missing passive event handler

src/utils/hooks/useProcessOrder.ts, src/utils/hooks/useProcessRange.ts, src/utils/hooks/useProcessTransaction.ts
=> prevent user's ENS name from appearing in pool tx table on /trade

src/ambient-utils/api/fetchXp.ts, src/contexts/GlobalContexts.tsx, src/contexts/XpLeadersContext.tsx, src/pages/Level/Level.tsx, src/pages/Level/RankTable/RankTable.tsx
=> add weekly and byChain mock xp leaders data

src/components/Trade/TradeTabs/Transactions/Transactions.tsx, src/contexts/GraphDataContext.tsx
remove transaction placeholder rows only when the indexed transaction data includes the completed tx hash or a tx failure receipt is received
transaction table placeholders weren’t disappearing in sync with the appearance of data from the indexer
1.
2.
1.
2.
=> prevent temporary duplicate and missing tx placeholders after tx completion

src/App/components/Sidebar/SidebarSearchResults/OrdersSearchResults.tsx, src/App/components/Sidebar/SidebarSearchResults/PositionsSearchResults.tsx, src/App/components/Sidebar/SidebarSearchResults/TxSearchResults/TxLI.tsx
added missing $ prefix in sidebar search results
1.
2.
1.
2.
=> fix missing $ prefix for USD values in sidebar search results

src/App/hooks/useSimulatedIsPoolInitialized.ts, src/components/NoChartData/NoChartData.tsx, src/pages/Trade/Trade.tsx
fix logic to display the prompt to refresh the chart data when candle data is unavailable from unexpectedly showing the prompt when switching networks.
1.
2.
1.
2.
=> fix erroneous chart unavailable message when switching chains

src/components/Global/NotificationCenter/NotificationTable/NotificationTable.tsx
receipts should now display in order of the time of transaction, rather than grouped by success/fail status.
_Closes #0000_
1.
2.
1.
2.
=> display receipts in notification center in order of time

src/components/Form/TokenInputWithWalletBalance.tsx, src/components/OrderDetails/OrderDetailsModal/OrderDetailsModal.tsx, src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx, src/components/Trade/TradeTabs/Ranges/rangeRowConstants.tsx, src/utils/hooks/useProcessOrder.ts, src/utils/hooks/useProcessRange.ts, src/utils/hooks/useProcessTransaction.ts
display small USD values with subscript in tables
previously, USD values smaller the $0.01 were appearing as $0.00
1.
2.
1.
2.
=> display small USD values with subscript in tables

src/components/Global/RangeStatus/RangeStatus.module.css, src/components/Global/Tabs/TableMenu/TableMenuComponents/OrdersMenu.tsx, src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx, src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx, src/components/Trade/TradeTabs/Orders/Orders.tsx, src/components/Trade/TradeTabs/Ranges/Leaderboard.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangeHeader.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx, src/components/Trade/TradeTabs/Ranges/rangeRowConstants.tsx, src/components/Trade/TradeTabs/Transactions/Transactions.tsx, src/styled/Components/TransactionTable.ts
updated column width minimums to prevent button overlap
before: 
after: 
1.
2.
1.
2.
=> update table row displays to prevent button overlap

src/components/Trade/Reposition/RepositionHeader/RepositionHeader.tsx, src/pages/Trade/Reposition/Reposition.tsx
use the same truncated position hash in the reposition header as displayed in the tables
position hashes did not match: 
1.
2.
1.
2.
=> fix position hash mismatch in reposition header

src/App/functions/approve.ts, src/App/hooks/useCreateRangePosition.ts, src/App/hooks/useSendInit.ts, src/components/LimitActionModal/LimitActionModal.tsx, src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx, src/components/Portfolio/ExchangeBalance/Transfer/Transfer.tsx, src/components/Portfolio/ExchangeBalance/Withdraw/Withdraw.tsx, src/components/RangeActionModal/RangeActionModal.tsx, src/components/Trade/TradeTabs/Orders/Orders.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.tsx, src/contexts/ReceiptContext.tsx, src/pages/InitPool/InitPool.tsx, src/pages/Trade/Limit/Limit.tsx, src/pages/Trade/Reposition/Reposition.tsx, src/pages/Trade/Swap/Swap.tsx
add filter based on connected wallet's address to prevent placeholder rows from reappearing after switching wallets
_Closes #0000_
1.
2.
1.
2.
=> bug fix: placeholder rows appearing for disconnected wallet

src/pages/Chart/Chart.tsx
temporary fix for candle update interval - reverting changes
candles were not updating on an interval
1.
2.
1.
2.
=> temporary fix for candle update interval - reverting changes

src/components/Trade/TradeModules/TradeModuleSkeleton.tsx, src/contexts/TradeDataContext.tsx
prevent flash of ack tokens prompt on scroll trade page load
during initial load for any trade page on Scroll the acknowledge tokens prompt would appear for a split second. 
1.
2.
1.
2.
=> prevent flash of ack tokens prompt on scroll trade page load

package.json, src/ambient-utils/dataLayer/functions/getPositionHash.ts, src/ambient-utils/dataLayer/functions/getSlot.ts, src/ambient-utils/dataLayer/transactions/swap.ts, src/ambient-utils/types/position/PositionServerIF.ts, src/components/Global/TransactionDetails/TransactionDetailsPriceInfo/TransactionDetailsPriceInfo.tsx, src/components/Global/TransactionDetails/TransactionDetailsSimplify/TransactionDetailsSimplify.tsx, src/components/LimitActionModal/LimitActionInfo/LimitActionInfo.tsx, src/components/LimitActionModal/LimitActionModal.tsx, src/components/RangeActionModal/RangeActionModal.tsx, src/components/RangeDetails/RangeDetailsSimplify/RangeDetailsSimplify.tsx, src/pages/Trade/Reposition/Reposition.tsx, yarn.lock
update SDK to 0.2.80
this fixes partial limit order removals. related changes to improve displays of partial limit order removals in removal modal and transaction details is also included.
_Closes #0000_
1.
2.
1.
2.
=> update SDK to 0.2.80

src/ambient-utils/constants/defaultTokens.ts, src/ambient-utils/constants/networks/ethereumMainnet.ts, src/ambient-utils/constants/networks/scrollMainnet.ts, src/components/Global/Analytics/PoolRow.tsx, src/components/Global/Analytics/TopPools.tsx, src/components/Global/Analytics/useSortedPools.ts, src/components/Global/Sidebar/PoolsListItem.tsx, src/styled/Components/Home.ts
add USDT/USDC and USDC/WBTC to Top Pools for Scroll
_Closes #0000_
1.
2.
1.
2.
=> add USDT/USDC and USDC/WBTC to Top Pools for Scroll

package.json, src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
=> temporary fix to prevent chart flicker on pool change

src/App/hooks/useFetchPoolStats.ts, src/ambient-utils/constants/networks/TopPool.ts, src/ambient-utils/types/pool/PoolIF.ts
fix initialization of order of token symbols of Top Pools
the order of some of the token symbols for the Top Pools on the homepage would invert after initial page load
1.
2.
1.
2.
=> fix initialization of order of token symbols of Top Pools

src/App/hooks/useAppChain.ts, src/contexts/CrocEnvContext.tsx, src/contexts/TradeDataContext.tsx, src/pages/Home/Home.tsx, src/pages/Trade/Swap/Swap.tsx, src/utils/hooks/useUrlParams.ts
fix network switch loop fix on swap when wallet connected (only an issue on hosted site for some reason)
_Closes #0000_
1.
2.
1.
2.
=> fix network switch loop fix on swap

src/App/hooks/useAppChain.ts, src/components/Home/TopPools/TopPools.tsx, src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx, src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx, src/pages/Chart/Draw/FloatingToolbar/FloatingToolbar.tsx, src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
prevent navigation to homepage when user switches chains while viewing the portfolio for another user
_Closes #0000_
1.
2.
1.
2.
=> prevent navigation away from portfolio when user switches chains

package.json, src/components/Trade/TradeTabs/Orders/Orders.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.tsx, src/components/Trade/TradeTabs/TradeTabs2.tsx, src/components/Trade/TradeTabs/Transactions/Transactions.tsx, src/contexts/DataLoadingContext.tsx, src/contexts/GraphDataContext.tsx, src/contexts/TradeTableContext.tsx
fix temporary display of 'No Transactions Found' switching pools
when switching pools the message "No Transactions Found" would display in the trade tables for a second 
1.
2.
1.
2.
=> fix temporary display of 'No Transactions Found' switching pools

src/pages/Chart/Chart.tsx
=> fixed: clicking on canvas for range/limit

src/pages/Trade/TradeCharts/TradeCharts.tsx, src/pages/Trade/TradeCharts/TradeChartsComponents/OrderHistoryDisplay.tsx
change default to show buys/sells overlay on chart when user connects wallet and has not disabled buys/sells.
_Closes #0000_
1.
2.
1.
2.
=> default to show buys/sells on chart

public/ambient-token-list.json, src/App/hooks/useSimulatedIsPoolInitialized.ts, src/ambient-utils/constants/ambient-token-list.json, src/components/Global/Analytics/TopPools.tsx, src/components/Global/Analytics/useSortedPools.ts, src/contexts/ExploreContext.tsx, src/pages/Explore/Explore.tsx
=> fetch Top Pools data in two batches

src/pages/Chart/Chart.css, src/pages/Chart/Chart.tsx
=> fixed last candle tooltip location

src/components/Chat/MessagePanel/SentMessagePanel/SentMessagePanel.tsx
Empty username problem fixed for new users on chat, also directing problem fixed for these users.
_Closes #0000_
1.
2.
1.
2.
=> handling empty str ens_name case on chat messages

src/components/Global/TransactionDetails/TransactionDetailsSimplify/TransactionDetailsSimplify.tsx, src/components/OrderDetails/OrderDetailsSimplify/OrderDetailsSimplify.tsx, src/components/RangeDetails/RangeDetailsSimplify/RangeDetailsSimplify.tsx
add elapsed time to tx/order/range details cards
_Closes #0000_
1.
2.
1.
2.
=> add elapsed time to tx/order/range details cards

src/App/hooks/usePoolMetadata.ts, src/contexts/GraphDataContext.tsx
=> Fix my tx table reset on token reversal

src/App/hooks/useCreateRangePosition.ts, src/App/hooks/useHandleRangeButtonMessage.ts, src/components/Form/TokenInputWithWalletBalance.tsx, src/components/Trade/Range/RangeTokenInput/RangeTokenInput.tsx, src/contexts/GraphDataContext.tsx, src/contexts/ReceiptContext.tsx, src/contexts/SidebarContext.tsx, src/contexts/TradeTokenContext.tsx, src/pages/InitPool/InitPool.tsx, src/pages/Trade/Limit/Limit.tsx, src/pages/Trade/Range/Range.tsx, src/pages/Trade/Swap/Swap.tsx, src/utils/numbers.ts
Doug requested that the trade inputs clear when a max swap is confirmed, rather than presenting the insufficient balance notification.
_Closes #0000_
1.
2.
1.
2.
=> clear trade inputs when balance becomes insufficient during swap

src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.tsx
=> Range shareable chart changed according to advanced card mockup 

src/ambient-utils/constants/ambient-token-list.json, src/ambient-utils/constants/defaultTokens.ts
=> fix Dai moneyness on Scroll

src/components/Trade/TradeTabs/Transactions/Transactions.tsx
https://github.com/CrocSwap/ambient-ts-app/issues/3335
_Closes #3335 _
=> add full screen height to loading on transactions mobile

src/ambient-utils/dataLayer/transactions/swap.ts
=> make performSwap default param values constent

src/App/hooks/usePoolMetadata.ts, src/contexts/GraphDataContext.tsx, src/pages/Chart/Candle/CandleChart.tsx, src/pages/Chart/Chart.tsx, src/pages/Chart/Liquidity/LiquidityChart.tsx, src/pages/Chart/RangeLine/RangeLinesChart.tsx, src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
=> Proven - attempt reduce chart loading

src/ambient-utils/constants/networks/TopPool.ts
fix chat rooms appearing empty
1.
2.
1.
2.
=> fix chat room dropdown selection

src/styled/Components/TradeModules.ts
increase relative width of TokenQuantityInput
1.
2.
1.
2.
=> prevent token quantity inputs appearing cut off

src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.tsx
=> added limit line on transaction details card

src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.css, src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.tsx
=> range lines on liquidity details card limited by txTime

src/components/Form/CurrencySelector.tsx, src/components/Form/TokenInputQuantity.tsx, src/components/Form/TokenInputWithWalletBalance.tsx, src/components/Swap/SwapTokenInput/SwapTokenInput.tsx, src/pages/InitPool/FormExample.tsx
prevent previously calculated quantity from momentarily appearing after price impact calculation on swap
_Closes #0000_
1.
2.
1.
2.
=> prevent quantity flicker after price impact calculation on swap

package.json, public/ambient-token-list.json, src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx, src/App/hooks/useAppChain.ts, src/ambient-utils/constants/defaultTokens.ts, src/ambient-utils/constants/networks/ethereumSepolia.ts, src/ambient-utils/constants/networks/index.ts, src/ambient-utils/dataLayer/functions/lookupChainId.ts, src/contexts/CrocEnvContext.tsx, yarn.lock
=> add sepolia network

src/pages/InitPool/InitPool.tsx
fix logic to open initial pool price input field on click
clicking input field not working when field disabled
1.
2.
1.
2.
=> fix click to open edit mode for initial pool price

src/App/hooks/useFetchPoolStats.ts
improve error handling when apr for pool not yet available
_Closes #0000_
1.
2.
1.
2.
=> fix missing pool stats for new pool

src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx, src/pages/Trade/Swap/Swap.tsx
=> add output destination to swap confirmation modal

src/components/Global/TransactionDetails/TransactionDetailsModal.tsx, src/components/Global/TransactionDetails/TransactionDetailsPriceInfo/TransactionDetailsPriceInfo.tsx, src/components/RangeDetails/PriceInfo/PriceInfo.tsx, src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx
remove zero APR display from details cards
I think it looks odd to show the ellipsis for APR when we don't have any accumulated fee data for new positions or removed positions: 
1.
2.
1.
2.
=> remove zero APR display from details cards

public/ambient-token-list.json, src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx, src/ambient-utils/constants/defaultTokens.ts, src/ambient-utils/constants/networks/ethereumSepolia.ts, src/ambient-utils/constants/networks/scrollSepolia.ts, src/ambient-utils/dataLayer/functions/stablePairs.ts, src/ambient-utils/dataLayer/functions/tokenMap.ts, src/components/Global/DropdownMenu2/DropdownMenu2.tsx
Add scroll sepolia to network selector
_Closes #0000_
1.
2.
1.
2.
=> Add scroll sepolia to network selector

src/pages/Trade/Range/useRangeInputDisable.tsx
prevent 'Single-asset deposit only' message from momentarily appearing when the user refreshes the page while on the Pool module.
_Closes #0000_
1.
2.
1.
2.
=> prevent early range input disabling

src/App/hooks/usePoolList.ts
=> add temporary filter to top pools data

src/components/Trade/TradeTabs/Transactions/Transactions.tsx, src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRowPlaceholder.tsx, src/contexts/ReceiptContext.tsx, src/pages/Trade/Reposition/Reposition.tsx
=> fix reposition tx placeholder row display logic

src/pages/Chart/Chart.tsx, src/pages/Chart/ChartUtils/chartUtils.ts, src/pages/Chart/Liquidity/LiquidityChart.tsx, src/pages/Chart/OrderHistoryCh/OrderHistoryTooltipCss.ts, src/pages/Chart/RangeLine/RangeLinesChart.tsx, src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
=> Proven - attempt reduce chart loading 2

src/App/hooks/useAppChain.ts
fix an issue hopefully only relevant on local dev environments where the last selected network is no longer supported by the app
_Closes #0000_
1.
2.
1.
2.
=> add fallback when locally stored chain not supported

src/ambient-utils/constants/index.ts, src/ambient-utils/constants/networks/blastNetwork.ts, src/index.tsx
update from https://rpc.ankr.com/blast/ to https://rpc.blast.io/
=> update RPC endpoint for Blast to rpc.blast.io

src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.tsx
temporarily force 5 minute candle durations until we have a week's worth of data on blast. Otherwise, we pull 1 hr candles for a very short period of time.
1.
2.
1.
2.
=> temporarily force 5 minute candle duration for tx details charts on blast

src/App/hooks/useFetchPoolStats.ts, src/App/hooks/usePoolStats.ts
pool stats for the pool info tab were not fetching reliably when switching pools
=> fix pool stats fetch when switching pools

src/contexts/ChainDataContext.tsx
strip the dev infura key and replace with the infura key from the build environment, if available, for the websocket connection to infura (used for block polling)
_Closes #0000_
1.
2.
1.
2.
=> use env variable for websocket infura key

src/App/hooks/useTokens.ts, src/ambient-utils/constants/defaultTokens.ts, src/ambient-utils/dataLayer/functions/getPoolStats.ts, src/components/Home/Stats/AmbientStats.tsx, src/contexts/ChainDataContext.tsx
=> use local decimals values for pool stats

package.json, src/ambient-utils/api/fetchTokenPrice.ts
fix blast token price fetches from coingecko
=> fix blast token price fetches

src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx, src/components/Trade/TradeTabs/TableRows.tsx, src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx, src/pages/Chart/Chart.tsx
prevent unnecessary table scrolling
fix disappearing row highlighting when denom changes and when modal closes
_Closes #0000_
1.
2.
1.
2.
=> Fix table scrolling

src/ambient-utils/api/fetchTokenPrice.ts
=> add hardcoded dai value on scroll

package.json, src/ambient-utils/constants/index.ts, src/ambient-utils/constants/networks/scrollMainnet.ts, src/index.tsx
switch to Ankr as the primary scroll RPC (block polling still on rpc.scroll.io)
_Closes #0000_
1.
2.
1.
2.
=> use ankr for scroll rpc

src/components/Trade/TradeTabs/TableRows.tsx, src/contexts/ChainDataContext.tsx, src/pages/Explore/Explore.tsx
=> Release 2.3.9 scroll rpc update to Ankr

src/components/Trade/TradeTabs/Ranges/Ranges.tsx
=> temporarily remove empty position filter on trade

src/ambient-utils/constants/networks/blastNetwork.ts
add yes/eth to homepage and Top Pools in sidebar
=> bump yes/eth to featured pools

src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
=> when changing period flickering chart problem is fixed

src/ambient-utils/api/fetchTokenPrice.ts, src/ambient-utils/constants/defaultTokens.ts, src/ambient-utils/constants/index.ts, src/components/Home/Stats/AmbientStats.tsx, src/contexts/ChainDataContext.tsx, src/contexts/CrocEnvContext.tsx, src/utils/hooks/useUrlParams.ts
=> remove filter by network for ambient stats on subdomains

public/ambient-token-list.json, src/ambient-utils/api/fetchTokenBalances.ts, src/ambient-utils/constants/ambient-token-list.json, src/ambient-utils/constants/defaultTokens.ts
add mim on blast: https://blastscan.io/token/0x76da31d7c9cbeae102aff34d3398bc450c8374c1
=> add mim token on blast

src/App/components/PageHeader/Account/UserProfileCard.tsx, src/ambient-utils/dataLayer/functions/getPoolStats.ts, src/components/Chat/MessagePanel/PositionBox/PositionBox.tsx, src/components/Global/LevelsCard/UserLevelDisplay.tsx, src/components/Global/TransactionDetails/TransactionDetailsSimplify/TransactionDetailsSimplify.tsx, src/components/RangeDetails/RangeDetailsSimplify/RangeDetailsSimplify.tsx
to be consistent, and avoid a bug switching networks while on a lookup portfolio with '/account/' in the url (user gets redirected to portfolio for connected wallet), remove the extra '/account' for lookup portfolio urls (e.g. https://scroll-us.ambient.finance/proteinpowpow.eth)
_Closes #0000_
1.
2.
1.
2.
=> remove extra "/account" in portfolio uls for lookup users

src/ambient-utils/constants/networks/arbitrumGoerli.ts, src/ambient-utils/constants/networks/blastNetwork.ts, src/ambient-utils/constants/networks/blastSepolia.ts, src/ambient-utils/constants/networks/ethereumMainnet.ts, src/ambient-utils/constants/networks/ethereumSepolia.ts, src/ambient-utils/constants/networks/scrollMainnet.ts, src/ambient-utils/constants/networks/scrollSepolia.ts, src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx, src/pages/Trade/Swap/Swap.tsx
use same SDK function throughout app to get a floating point number from a BigNumber to be consistent
_Closes #0000_
1.
2.
1.
2.
=> switch to using bigNumToFloat from SDK

src/components/Portfolio/ExchangeBalance/Transfer/Transfer.tsx, src/components/Portfolio/ExchangeBalance/Withdraw/Withdraw.tsx
check if a resolved destination address for an exchange balance withdrawal or transfer is a contract address or the zero address (ETH) and prevent such transactions.
bus raised the issue that some eth was lost by a user who transferred their exchange balance to the USDC token contract: https://scrollscan.com/tx/0x310fa5c87265c8c2800ad8dc70b4026a1109995280885b7362d09701e7449143
1.
2.
1.
2.
=> prevent withdraw/transfer to contract addresses

src/App/hooks/useFetchPoolStats.ts, src/ambient-utils/api/fetchDepositBalances.ts, src/ambient-utils/api/fetchTokenBalances.ts, src/ambient-utils/dataLayer/functions/getLimitOrderData.ts, src/ambient-utils/dataLayer/functions/getPoolStats.ts, src/ambient-utils/dataLayer/functions/getPositionData.ts, src/ambient-utils/dataLayer/functions/getTransactionData.ts, src/components/Home/Stats/AmbientStats.tsx, src/contexts/ChainDataContext.tsx, src/contexts/ExploreContext.tsx, src/pages/Portfolio/Portfolio.tsx
=> reduce unnecessary on-chain provider calls

src/components/Trade/TradeTabs/Orders/Orders.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.tsx, src/components/Trade/TradeTabs/Transactions/Transactions.tsx
remove View More button when rows available to show do not exceed the number of rows shown
1.
2.
1.
2.
=> only show View More button when more to show exist

src/pages/Chart/Chart.tsx
=> Fix banner problems for chart

src/App/hooks/usePoolPricing.ts, src/ambient-utils/dataLayer/functions/getFormattedNumber.ts, src/ambient-utils/dataLayer/functions/getPositionData.ts, src/ambient-utils/types/position/PositionIF.ts, src/components/RangeDetails/PriceInfo/PriceInfo.tsx, src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx, src/components/Trade/TradeModules/SubmitTransaction/TransactionException/TransactionException.tsx, src/components/Trade/TradeTabs/Orders/OrderTable/OrderRowPlaceholder.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRowPlaceholder.tsx, src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRowPlaceholder.tsx, src/contexts/ChainDataContext.tsx, src/pages/Trade/Limit/Limit.tsx, src/pages/Trade/Range/Range.tsx, src/pages/Trade/Swap/Swap.tsx, src/styled/Components/TransactionTable.ts
make on-chain calls every block while a position mint is pending to check for liquidity and show a row for the new position. 
When the indexer is lagging, the user may wonder whether their newly minted position was successful.
1.
2.
1.
2.
=> add liquidity polling for pending position mints

package.json, src/ambient-utils/api/fetchTokenBalances.ts
=> fix exchange balance fetching

src/ambient-utils/api/fetchPositionRewards.ts, src/ambient-utils/dataLayer/functions/getFormattedNumber.ts, src/ambient-utils/types/xp/PositionRewardsIF.ts, src/components/RangeDetails/PriceInfo/PriceInfo.tsx, src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx, src/components/RangeDetails/RangeDetailsSimplify/RangeDetailsSimplify.tsx
add blast points to details side of shareable card
=> add blast points to range card extra details

src/ambient-utils/api/fetchBatch.ts
reduce the timeout durations of batched queries to the analytics server.
the user needed to wait 6-8 seconds after an initial load of the app to see dollarized values on homepage, e.g.  pool TVL/24h. Volume and cumulative Ambient Finance stats .
1.
2.
1.
2.
=> decrease timeouts for token price batch queries

src/components/Global/Account/AccountTabs/Points/Points.tsx
add View Details button to Points tab on /account linking to the /xp details
=> add View Details button to Points tab on /account

src/contexts/ChainDataContext.tsx
=> use blast rpc env var. for block polling

src/ambient-utils/api/fetchBatch.ts
increase timeouts by 200ms
on a VPN the queries were failing and showing infinity for TVL, Volume, Fees on the homepage
1.
2.
1.
2.
=> increase fetch batch timeouts by 200ms

src/components/Global/Analytics/DexTokens.tsx, src/components/Global/Analytics/TokenRow.tsx
* Move early return logic from `TokenRow.tsx` to `DexTokens.tsx` parent
none
1.
2.
1.
2.
none
=> Fix conditional hook call

src/components/Global/LevelsCard/LevelsCard.tsx, src/components/Global/LevelsCard/PointsHistoryDisplay/PointsHistoryDisplay.tsx
=> specify 'Ambient Points' on xp details

src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx
=> hide harvest button when fees zero except mainnet

src/components/Home/Landing/MobileLandingSections.tsx, src/pages/Home/Home.tsx
this CTA was mistakenly set to only show in dev environments
_Closes #0000_
1.
2.
1.
2.
=> show points homepage CTA in all environments

src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.tsx, src/components/Global/TransactionDetails/TransactionDetailsModal.tsx, src/components/Global/TransactionDetails/TransactionDetailsSimplify/TransactionDetailsSimplify.tsx, src/components/OrderDetails/OrderDetailsModal/OrderDetailsModal.tsx, src/components/OrderDetails/OrderDetailsSimplify/OrderDetailsSimplify.tsx, src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx, src/components/RangeDetails/RangeDetailsSimplify/RangeDetailsSimplify.tsx
pass memoized value from tx details modal instead of child graph component to not get lost when switching to details side of card
_Closes #0000_
1.
2.
1.
2.
=> fix collapsing shaded area on tx details card for ranges

src/components/Global/Analytics/DexTokens.tsx, src/components/Global/Analytics/PoolRow.tsx, src/components/Global/Analytics/TokenRow.tsx, src/styled/Components/Analytics.ts
- remove pool name on slightly larger screens
- remove fees column on mobile phones
token names appear on multiple lines on commonly sized phones
token names overlap other data on commonly sized phones:
1.
2.
1.
2.
=> improve display of Top Pools/Active Tokens table on mobile

package.json, src/App/hooks/useCreateRangePosition.ts, src/App/hooks/usePoolPricing.ts, src/ambient-utils/dataLayer/transactions/range.ts, src/ambient-utils/tests/sequential/transactions/range.test.ts, src/components/Swap/SwapTokenInput/SwapTokenInput.tsx, src/components/Trade/Limit/LimitTokenInput/LimitTokenInput.tsx, src/components/Trade/Range/RangeTokenInput/RangeTokenInput.tsx, src/components/Trade/TradeModules/SubmitTransaction/TransactionException/TransactionException.tsx, src/contexts/RangeContext.tsx, src/pages/Chart/Chart.tsx, src/pages/InitPool/InitPool.tsx, src/pages/Trade/Range/Range.tsx
previously, the user needed to enter a separate quantity for the pool module. This was probably more annoying than helpful, so the primary quantity for pool is now in sync with the primary quantity for swap/limit.
_Closes #0000_
1.
2.
1.
2.
=> consolidate primary quantity tracking for swap/limit/range

package.json, src/App/components/PageHeader/PageHeader.tsx, src/App/hooks/useFetchPoolStats.ts, src/App/hooks/usePoolMetadata.ts, src/App/hooks/usePoolPricing.ts, src/components/Portfolio/PortfolioTabs/PortfolioTabs.tsx, src/components/Trade/TradeTabs/TradeTabs2.tsx, src/contexts/AppStateContext.tsx, src/contexts/CandleContext.tsx, src/contexts/ExploreContext.tsx, src/contexts/GraphDataContext.tsx, src/contexts/PoolContext.tsx, yarn.lock
paused all gcgo requests while the user is idle
we were calling gcgo for updates while the user was idle. this was causing excessive load on the servers.
1.
2.
1.
2.
=> add idle timer for server requests

src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.tsx
=> Last changes to shareable range cards

src/components/Trade/TradeTabs/Orders/Orders.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.tsx, src/components/Trade/TradeTabs/Transactions/Transactions.tsx
=> attempt to scroll to top after switching pages

src/App/components/PageHeader/Account/Account.tsx, src/ambient-utils/dataLayer/functions/getFormattedNumber.ts, src/components/Global/LevelsCard/UserLevelDisplay.tsx
=> fix current level formatting

src/App/hooks/useFetchPoolStats.ts, src/App/hooks/usePoolMetadata.ts, src/App/hooks/usePoolPricing.ts, src/components/Portfolio/PortfolioTabs/PortfolioTabs.tsx, src/contexts/CandleContext.tsx, src/contexts/GraphDataContext.tsx
change the complete pause of graph cache queries to a slowdown
_Closes #0000_
1.
2.
1.
2.
=> change gcgo query pause on idle to slowdown

src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
remove the disabling of swap reversal during impact calculations
_Closes #0000_
1.
2.
1.
2.
=> remove swap reversal disabling

package.json, public/ambient-token-list.json, src/App/hooks/useTokenSearch.ts, src/ambient-utils/api/fetchTokenBalances.ts, src/ambient-utils/api/fetchTokenList.ts, src/ambient-utils/constants/ambient-token-list.json, src/components/Global/TokenSelect/TokenSelect.tsx, src/contexts/ChainDataContext.tsx, src/pages/Portfolio/Portfolio.tsx, yarn.lock
remove Covalent dependency and instead use provider to query for balances of any token on the ambient token list or in the list of tokens the user has made a transaction with on Ambient (returned by user_balance_tokens gcgo endpoint).
Covalent was too expensive and slow.
1. token wallet and exchange balances fetches
2. displays of balances on /account and in token selectors
1.
2.
=> Remove covalent dependency

src/ambient-utils/dataLayer/functions/getFormattedNumber.ts, src/ambient-utils/dataLayer/functions/getPositionData.ts, src/components/RangeActionModal/RangeActionModal.tsx, src/components/Trade/Reposition/RepositionPriceInfo/RepositionPriceInfo.tsx, src/pages/Trade/Reposition/Reposition.tsx
add value and est. impact to reposition panel:
_Closes #0000_
1.
2.
1.
2.
=> Fix liq removal usd value estimation

src/pages/Trade/Reposition/Reposition.tsx
=> fix reposition bug: rapid fire updates to range width

src/App/hooks/useTokenSearch.ts, src/App/hooks/useTokens.ts, src/ambient-utils/api/fetchTokenBalances.ts, src/components/Global/TokenIcon/TokenIcon.tsx, src/components/Global/TokenIcon/processLogoSrc.ts, src/contexts/TokenContext.tsx
remove filtering preventing tokens not in any token list from appearing in the token selector
_Closes #0000_
1.
2.
1.
2.
=> Fix missing tokens in token selector

src/components/Global/DropdownMenu2/DropdownMenu2.tsx
add escape key handler to dropdown menus
_Closes #0000_
=> add escape key handler to dropdown menus

src/ambient-utils/api/fetchCandleSeries.ts
=> fix tvl calculations for subchart

src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
=> fix missing conversion rate on swap confirm

src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
=> attempt to fix swap output overwrite by block update

src/ambient-utils/api/fetchPositionRewards.ts, src/ambient-utils/api/fetchXp.ts, src/ambient-utils/types/xp/PositionRewardsIF.ts, src/ambient-utils/types/xp/UserXpIF.ts, src/components/Global/Account/AccountTabs/Points/Points.tsx, src/components/RangeDetails/PriceInfo/PriceInfo.tsx, src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx, src/components/RangeDetails/RangeDetailsSimplify/RangeDetailsSimplify.tsx
=> add blast gold queries

src/components/Form/WalletBalanceSubinfo.tsx, src/components/Global/ConfirmationModalControl/ConfirmationModalControl.tsx, src/components/Global/SendToDexBalControl/SendToDexBalControl.module.css, src/components/Global/SendToDexBalControl/SendToDexBalControl.tsx, src/components/Global/TransactionSettingsModal/TransactionSettingsModal.tsx, src/components/Trade/TradeModules/TradeModuleHeader.tsx, src/pages/Trade/Swap/Swap.tsx
disabled the toggle between save to wallet/dex in swap module...moved toggle to swap settings
people were accidentally toggling on Save to Exchange balance and wondering where their tokens went
1.
2.
1.
2.
=> add Save to exchange balance toggle to swap settings

src/ambient-utils/api/fetchPositionRewards.ts, src/ambient-utils/api/fetchXp.ts, src/ambient-utils/types/xp/PositionRewardsIF.ts, src/ambient-utils/types/xp/UserXpIF.ts
=> fix blast gold mapping

src/ambient-utils/api/fetchPositionRewards.ts, src/ambient-utils/api/fetchXp.ts, src/ambient-utils/types/xp/UserXpIF.ts, src/components/Global/Account/AccountTabs/Points/Points.tsx
add up to two decimal points of precision to blast gold quantity displays
_Closes #0000_
1.
2.
1.
2.
=> add precision to blast gold displays

src/App/hooks/useFetchPoolStats.ts, src/ambient-utils/dataLayer/functions/getPoolStats.ts, src/contexts/ExploreContext.tsx
=> remove token universe caching with pool stats requests

src/App/hooks/useFetchPoolStats.ts, src/ambient-utils/dataLayer/functions/getLimitOrderData.ts, src/ambient-utils/dataLayer/functions/getPositionData.ts, src/ambient-utils/dataLayer/functions/getTransactionData.ts, src/ambient-utils/types/limitOrder/LimitOrderIF.ts, src/ambient-utils/types/position/PositionIF.ts, src/ambient-utils/types/transaction/TransactionIF.ts, src/components/Global/TokenIcon/processLogoSrc.ts, src/components/Trade/TradeTabs/Transactions/txRowConstants.tsx, src/contexts/PoolContext.tsx, src/utils/hooks/useProcessOrder.ts, src/utils/hooks/useProcessRange.ts, src/utils/hooks/useProcessTransaction.ts
use pool price to calculate missing base/quote token prices for dollarized displays
=> fix inconsistent dollarized display

src/components/Trade/Range/RangePriceInfo/RangePriceInfo.tsx, src/pages/Chart/Axes/yAxis/YaxisCanvas.tsx
Changes were made to RangePriceInfo.tsx because the decimal parts of min price and max price are different from those used in the chart.
_Closes #0000_
1.
2.
1.
2.
=> Reflect market and range prices in dollars

package.json, src/ambient-utils/api/fetchCandleSeries.ts, src/ambient-utils/dataLayer/functions/getPoolStats.ts, src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.tsx, src/contexts/CandleContext.tsx
use the current pool price to estimate the USD value of a token missing a USD value from coin gecko
missing token prices resulted in lower than expected pool TVL displays
1.
2.
1.
2.
=> use pool price to estimate missing token prices for pool tvl

public/ambient-token-list.json, src/App/hooks/useFetchPoolStats.ts, src/ambient-utils/constants/ambient-token-list.json, src/ambient-utils/dataLayer/functions/getPoolStats.ts, src/contexts/ExploreContext.tsx
Use the current pool price to estimate the token price for pool stats.
24h volume changes were not correct when one token price was unknown.
1.
2.
1.
2.
=> use current pool price for estimating pool stats when token price unknown

src/pages/Chart/Axes/yAxis/YaxisCanvas.tsx
=> fixed negative number issue for scientific number on y-axis

src/components/Form/TokenInputWithWalletBalance.tsx, src/components/Swap/SwapTokenInput/SwapTokenInput.tsx, src/components/Trade/Limit/LimitTokenInput/LimitTokenInput.tsx, src/components/Trade/Range/RangeTokenInput/RangeTokenInput.tsx
use pool price to estimate USD value of token with unknown USD value
1.
2.
1.
2.
=> add missing usd values in swap/limit/pool token input fields

src/contexts/CrocEnvContext.tsx
infura key environment variable was not used to create a crocEnv provide on Testnet
_Closes #0000_
1.
2.
1.
2.
=> use env variable for testnet crocEnv provider node override

src/App/components/PageHeader/PageHeader.tsx, src/ambient-utils/dataLayer/functions/getLimitPrice.ts, src/components/Global/Analytics/PoolRow.tsx, src/components/Global/Analytics/TopPools.tsx, src/components/Global/Sidebar/SidebarLimitOrders/SidebarLimitOrdersCard.tsx, src/components/Global/Sidebar/SidebarRangePositions/SidebarRangePositionsCard.tsx, src/components/Portfolio/PortfolioBanner/PortfolioBanner.tsx, src/components/Swap/SwapExtraInfo/SwapExtraInfo.tsx, src/components/Trade/Limit/LimitExtraInfo/LimitExtraInfo.tsx, src/components/Trade/Range/RangeExtraInfo/RangeExtraInfo.tsx, src/components/Trade/Range/RangePriceInfo/RangePriceInfo.tsx, src/components/Trade/TradeTabs/Orders/orderRowConstants.tsx, src/components/Trade/TradeTabs/Ranges/rangeRowConstants.tsx, src/components/Trade/TradeTabs/Transactions/txRowConstants.tsx, src/contexts/ExploreContext.tsx, src/contexts/PoolContext.tsx, src/pages/Chart/Axes/yAxis/YaxisCanvas.tsx, src/pages/Chart/ChartUtils/getDollarPrice.ts, src/pages/Explore/Explore.tsx, src/pages/Trade/TradeCharts/TradeChartsComponents/TradeChartsTokenInfo.tsx, src/pages/Trade/TradeCharts/TradeChartsHeader/TradeChartsHeader.tsx
=> track explore dollarization in local storage

src/contexts/CrocEnvContext.tsx, src/contexts/TradeDataContext.tsx
Initialize the app with a default token pair based on the last token pair viewed on that domain. If either token matches by symbol with a listed token on the new chain, then use that token instead of the default token for that chain.
https://github.com/CrocSwap/ambient-ts-app/assets/570819/826420c0-1c95-4bd8-a9ca-0a5a3374a18c
=> persist token selection though network switching

src/components/Global/Analytics/DexTokens.tsx, src/components/Global/Analytics/TopPools.tsx
=> change top pools height to 85%

src/components/Global/Analytics/DexTokens.tsx, src/components/Global/Analytics/TopPools.tsx, src/pages/Explore/Explore.tsx
update Explore, Top Pools and Active Tokens styling to keep the gap at the bottom consistent.
the bottom footer had become too large on desktop
=> update explore styling for footer padding

src/components/Global/Analytics/PoolRow.tsx, src/components/Global/Analytics/TopPools.tsx
The Top Pools page has unused space on mobile since removing the token symbols, so price has be re-added.
1.
2.
1.
2.
=> show top pools prices on mobile

src/index.css
UPDATE DARK COLORS
| Before | After |
|--------|-------|
| ![Before](https://github.com/CrocSwap/ambient-ts-app/assets/83131501/f7ee4beb-e7ac-439c-aba4-3fe53a788f57) | ![After](https://github.com/CrocSwap/ambient-ts-app/assets/83131501/4b33b885-ce94-4b57-8110-50989db1753c) |
_Closes #0000_
=> update dark colors

src/App/App.css, src/App/components/PageHeader/PageHeader.tsx, src/styled/Components/Analytics.ts, src/styled/Components/Home.ts
fix z index issue on explore page header on mobile devices
| Before | After |
|--------|-------|
| ![Before](https://github.com/CrocSwap/ambient-ts-app/assets/83131501/f9490104-ddc3-4288-a653-f29063fae91d) | ![After](https://github.com/CrocSwap/ambient-ts-app/assets/83131501/fadf5485-9ecd-42d5-abcd-7cd5cd9953cb) |
_Closes #0000_
=> fix z index issue on explore page header on mobile devices

src/components/Trade/TradeTabs/Orders/Orders.tsx, src/components/Trade/TradeTabs/Ranges/Ranges.tsx, src/components/Trade/TradeTabs/Transactions/Transactions.tsx, src/pages/Trade/TradeCharts/TradeChartsHeader/TradeChartsHeader.tsx, src/styled/Components/Portfolio.ts
base the height of the transactions/limits/ranges lists on the available viewport.
excessively large gaps at bottom of tables on mobile
1.
2.
1.
2.
=> fix trade table height on mobile

src/App/App.tsx, src/components/Global/PointSystemPopup/PointSystemPopup.tsx, src/pages/FAQ/FAQ.module.css, src/pages/FAQ/FAQPoints.tsx, src/pages/Swap/Swap.tsx, src/utils/hooks/useLinkGen.ts, src/utils/hooks/useUrlParams.ts
Add direct-linking to questions in FAQ page.
none
Go to `/faq/points` and ensure:
* when a question is hovered, the cursor changes a link icon appears
* when a question is clicked, a functional URL is copied to the clipboard
* pasting that URL into the URL bar of the browser scrolls to that question
The URL construction logic will use one of two domains:
1. `localhost:3000` (if a local build)
2. `ambient.finance` (all other builds)
Note that the deploy preview will generate links in the second format, so testing link quality requires either deployment or running the code locally. All other functionality should be in place for the deploy …
=> Link questions in faq

src/App/hooks/useSidebarSearch.ts
Fix issue trimming whitespace to search an ENS address from the sidebar.
none
Search an ENS address in the sidebar with whitespace before/after the input. This should not break the search.
none
none
=> Fix search whitespace issue

src/ambient-utils/api/fetchBatch.ts, src/ambient-utils/api/fetchTokenPrice.ts, src/contexts/CrocEnvContext.tsx
prevent USD values = Infinity from being set as the mainnet ETH value or any value returned from CoinGecko's API.
sometimes USD values on homepage and gas estimates would appear as Infinity
1.
2.
1.
2.
=> prevent USD values appearing as Infinity

src/components/Swap/SwapExtraInfo/SwapExtraInfo.tsx, src/components/Swap/SwapTokenInput/SwapTokenInput.tsx, src/components/Trade/TradeModules/ExtraInfo/ExtraInfo.tsx, src/pages/Trade/Swap/Swap.tsx
add red to extra info section
_Closes #0000_
1.
2.
1.
2.
=> Fix price impact warning styling

src/ambient-utils/dataLayer/functions/pinTick.ts, src/components/Trade/Limit/LimitRate/LimitRate.tsx, src/contexts/TradeDataContext.tsx, src/pages/Chart/Chart.tsx, src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
need to add buttons to pre-populate limit input field with values
1.
2.
1.
2.
=> add top of book button to limit module

public/ambient-token-list.json, src/ambient-utils/constants/ambient-token-list.json, src/ambient-utils/constants/defaultTokens.ts, src/ambient-utils/dataLayer/functions/stablePairs.ts, src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx
- fix range removal button not appearing when USD value of position is zero, but liquidity is non-zero
- add wrsETH on Blast to ambient token list
=> fix missing remove button when USD value zero but liquidity non-zero

package.json, public/ambient-token-list.json, src/ambient-utils/constants/ambient-token-list.json, src/ambient-utils/constants/defaultTokens.ts, src/ambient-utils/dataLayer/functions/stablePairs.ts, src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx, src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx, src/pages/Trade/Swap/Swap.tsx
- fixed missing liquidity removal button when USD value for position is zero and liquidity non-zero
- added wrsETH on Blast to Ambient Token List
=> Release 2.4.13

src/pages/Chart/Chart.tsx
=> fixed disappear chart when click chart

src/ambient-utils/dataLayer/functions/stablePairs.ts, src/components/Form/RangeSlider.tsx, src/components/Form/RangeWidth/RangeWidth.tsx
=> allow sub-5% range support

src/ambient-utils/constants/networks/blastNetwork.ts, src/ambient-utils/constants/networks/ethereumMainnet.ts, src/ambient-utils/dataLayer/functions/stablePairs.ts, src/components/Form/RangeWidth/RangeWidth.tsx, src/components/Global/PoolCard/PoolCard.tsx
=> Handle multi staked eth pairs

src/ambient-utils/constants/networks/blastNetwork.ts, src/ambient-utils/constants/networks/blastSepolia.ts, src/ambient-utils/constants/networks/ethereumMainnet.ts, src/ambient-utils/constants/networks/ethereumSepolia.ts, src/ambient-utils/constants/networks/scrollMainnet.ts, src/ambient-utils/constants/networks/scrollSepolia.ts
Fix chain objects to correctly add chains to wallets via web3modal.
=> Fix ethers chain objects

src/index.tsx
use the app's default color scheme and fonts for Web3Modal, instead of Web3Modal's default 
default:
with app's defaults for color/fonts
1.
2.
1.
2.
=> use Ambient color theme for Web3Modal

netlify/edge-functions/country-block.ts, netlify/edge-functions/country-redirect.ts, package.json
- Re-adds the page refresh on initial page load as a workaround for a bug between Metamask and Chrome
- Updates the appearance of the wallet connection component to use the app's default color/font scheme
=> Release 2.5.1

src/pages/Chart/Chart.tsx
1. Open the chart
2. Switch to 1 day
3. Change browser tab
4. Return to chart after 1 minute
=> fixed: chart disappear when switch browser tab

package.json, src/index.tsx, yarn.lock
bus's change to fix an issue where the user can dismiss the unsupported network modal and remain logged in.
user's will now be disconnected if they dismiss the unsupported network modal.
_Closes #0000_
1.
2.
1.
2.
=> force disconnect if unsupported network modal dismissed

src/index.tsx
force reload when web3modal closes after switching networks
https://github.com/CrocSwap/ambient-ts-app/assets/570819/ed5e6692-cea8-4d70-b3ea-5cf7e4ff58cc
https://github.com/CrocSwap/ambient-ts-app/assets/570819/b2587fe1-88c7-49cf-a01e-799579c66c95
1.
2.
1.
2.
=> force reload on network switch to fix unknown account #0 bug

package.json, yarn.lock
rolled back the web3modal dependency to 4.1.11
1.
2.
1.
2.
=> roll back web3modal to v4.1.11

src/components/Global/Sidebar/SidebarFooter/SidebarFooter.tsx
replace sidebar toggle button with link to homepage
sidebar link no longer has an effect
1.
2.
1.
2.
=> replace mobile nav sidebar toggle with link to home

src/components/Global/DropdownSearch/DropdownSearch.tsx
=> remove search dropdown option selection animation

src/ambient-utils/constants/blacklist.ts, src/components/Global/DropdownSearch/DropdownSearch.module.css, src/components/Global/DropdownSearch/DropdownSearch.tsx, src/pages/Trade/TradeCharts/TradeCharts.module.css, src/pages/Trade/TradeCharts/TradeCharts.tsx, src/pages/Trade/TradeCharts/TradeChartsComponents/CurveDepth.module.css, src/pages/Trade/TradeCharts/TradeChartsComponents/TimeFrame.module.css, src/pages/Trade/TradeCharts/TradeChartsComponents/VolumeTVLFee.module.css, src/styled/Common/Container.ts, src/styled/Components/Chart.ts, src/styled/Components/Sidebar.ts
* Added `--dark3` hover state to token pair dropdown button
* Added `--dark3` hover state to other buttons in the trade chart header
* Changed purple background glow effect to a muted off-black
* Changed token pair dropdown search field background color to `--dark3`
none
1.
2.
1.
2.
=> complete style changes requested by miyu

src/App/hooks/useKeyPress.ts, src/components/Global/DropdownSearch/DropdownSearch.tsx, src/components/Global/Sidebar/FavoritePools.tsx, src/components/Global/Sidebar/PoolsListItem.tsx, src/components/Global/Sidebar/RecentPools.tsx, src/components/Global/Sidebar/TopPools.tsx, src/styled/Components/Sidebar.ts
=> add 24h price change column to dropdown search

src/App/hooks/useAppChain.ts, src/contexts/CrocEnvContext.tsx, src/contexts/UserDataContext.tsx
Disgusting, but worse yet it probably doesn't work
=> Gross chain switching fix attempt

src/App/hooks/useAppChain.ts, src/App/hooks/useFetchPoolStats.ts, src/ambient-utils/api/fetchTopPairedToken.ts, src/ambient-utils/api/index.ts, src/ambient-utils/constants/index.ts, src/ambient-utils/dataLayer/functions/getTopPairedTokenAddress.ts, src/contexts/CachedDataContext.tsx, src/pages/Explore/Explore.tsx, src/utils/hooks/useUrlParams.ts
=> Support ds hotlinking

src/components/Global/Sidebar/PoolsListItem.tsx
=> add white color to pool price change in dropdown when there is no change

package.json, public/ambient-token-list.json, src/ambient-utils/constants/ambient-token-list.json
change SCRIBES token on scroll from
https://scrollscan.com/token/0x122aD65A36ab6Dc12261C977e5e63a54ED1bA9E6
to  
https://scrollscan.com/token/0x750351a9F75F98f2c2E91D4eDb3BeB14e719557E
per Jeff's request
_Closes #0000_
1.
2.
1.
2.
=> Update scribes token

package.json, src/App/hooks/useFetchPoolStats.ts, src/ambient-utils/constants/networks/blastNetwork.ts, src/ambient-utils/constants/networks/ethereumMainnet.ts, src/ambient-utils/constants/networks/scrollMainnet.ts, src/components/Home/Stats/AmbientStats.tsx
- fixed missing USD value for pool prices on homepage
=> fix USD value displays for pool prices on homepage

package.json, src/components/Home/Stats/AmbientStats.tsx
remove greater than symbol from ambient stats
1.
2.
1.
2.
=> remove greater than symbol from ambient stats

src/components/Global/Explore/PoolRow.tsx, src/components/Global/Explore/TokenRow.tsx
add click handler to trade button and add propagation preventer to row element
_Closes #3524_
=> fix nested clickables on /explore

package.json, src/App/hooks/useFetchPoolStats.ts, src/App/hooks/useTokens.ts, src/ambient-utils/constants/defaultTokens.ts, src/ambient-utils/constants/networks/blastNetwork.ts, src/ambient-utils/constants/networks/ethereumMainnet.ts, src/ambient-utils/constants/networks/scrollMainnet.ts, src/ambient-utils/dataLayer/functions/getPoolStats.ts, src/ambient-utils/dataLayer/functions/stablePairs.ts, src/components/Global/Explore/PoolRow.tsx, src/components/Global/Explore/TokenRow.tsx, src/components/Home/Stats/AmbientStats.tsx, src/components/Trade/TradeModules/TradeModuleSkeleton.tsx, src/pages/Trade/Limit/Limit.tsx, src/pages/Trade/Range/Range.tsx, src/pages/Trade/Swap/Swap.tsx
- fixed bug sometimes causing token acknowledgement prompt to appear for default token pair
- added fallback on mainnet ETH price for staked ETH tokens missing token price from CoinGecko
=> Release 2.5.14

package.json, src/App/hooks/useFetchPoolStats.ts, src/ambient-utils/constants/networks/blastNetwork.ts, src/ambient-utils/constants/networks/ethereumMainnet.ts, src/ambient-utils/constants/networks/scrollMainnet.ts
- fix bug where USD price estimation not updating once mainnet ETH price is available
=> Release 2.5.15

src/pages/Trade/Swap/Swap.tsx
=> add extra warning when estimated loss of value exceeds 10%

src/components/LimitActionModal/LimitActionModal.tsx, src/components/RangeActionModal/RangeActionModal.tsx, src/pages/Trade/Reposition/Reposition.tsx
add smolrefuel to limi/range action and reposition components
_Closes #0000_
1.
2.
1.
2.
=> add smolrefuel to limi/range action and reposition components

public/ambient-token-list.json, src/App/hooks/useTokens.ts, src/ambient-utils/constants/ambient-token-list.json, src/ambient-utils/constants/defaultTokens.ts, src/components/Global/TokenIcon/TokenIcon.tsx
=> fix missing token logos for pufETH and rETH

src/App/hooks/useTokenSearch.ts, src/App/hooks/useTokens.ts, src/ambient-utils/constants/defaultTokens.ts, src/ambient-utils/constants/tokenListURIs.ts
check default token list before querying for onchain token data
app was not checking default token list before querying for onchain data
https://dev-ambi.netlify.app/trade/market/chain=0x82750&tokenA=0x0000000000000000000000000000000000000000&tokenB=0xc4d46E8402F476F269c379677C99F18E22Ea030e
1.
2.
1.
2.
=> check default token list on token lookup

package.json, src/App/hooks/useTokenSearch.ts, src/ambient-utils/constants/index.ts, src/ambient-utils/constants/networks/blastNetwork.ts, src/ambient-utils/constants/networks/ethereumMainnet.ts, src/ambient-utils/constants/networks/scrollMainnet.ts, src/ambient-utils/constants/tokenListURIs.ts
- fix bug causing failure to load some token logos on initial app load
- fix bug causing token list fetches to fail at a Cloudflare gateway
=> Release 2.5.17

package.json, public/ambient-token-list.json, src/ambient-utils/constants/ambient-token-list.json, src/ambient-utils/constants/defaultTokens.ts, src/ambient-utils/constants/networks/blastNetwork.ts, src/ambient-utils/constants/networks/ethereumMainnet.ts, src/utils/hooks/useUrlParams.ts, yarn.lock
- improved handling of missing chain param when only a single token is in URL (like in Dexscreener links)
=> Release 2.5.19

src/contexts/TokenBalanceContext.tsx
=> Fix token balance resets

package.json, public/ambient-token-list.json, src/ambient-utils/constants/ambient-token-list.json, src/ambient-utils/constants/defaultTokens.ts, src/ambient-utils/constants/networks/blastNetwork.ts, src/ambient-utils/constants/networks/ethereumMainnet.ts, src/ambient-utils/constants/networks/scrollMainnet.ts, src/ambient-utils/dataLayer/functions/stablePairs.ts, src/assets/images/tokens/OLE.svg, src/assets/images/tokens/exports.ts, src/contexts/TokenBalanceContext.tsx, src/utils/hooks/useUrlParams.ts, yarn.lock
- fixed issue with token balance displays flickering when switching wallets
=> Release 2.5.21

src/pages/Chart/Chart.tsx
=> bug fixed : latest func when auto mode is off

src/pages/Trade/TradeCharts/TradeChartsHeader/TradeChartsHeader.tsx
=> update USD mode switcher

src/ambient-utils/dataLayer/functions/getPositionData.ts
this adds a fallback query for position liquidity and rewards for when the graph cache server is in the process of restarting and has not yet indexed liquidity.
_Closes #0000_
1.
2.
1.
2.
=> Add sdk query fallback when liq refresh time zero

package.json, src/ambient-utils/constants/networks/blastNetwork.ts, src/ambient-utils/constants/networks/ethereumMainnet.ts, src/ambient-utils/constants/networks/scrollMainnet.ts
=> add ETH/BLAST to top pools

package.json, src/contexts/PoolContext.tsx
automatically toggle on dollar mode for any pair that isn’t either a pair of stable tokens or a pair of ETH/Staked ETH tokens, and toggles off dollar mode when any pair that is a pair of stable tokens or a pair of ETH/Staked ETH tokens
also removes the saving of dollar mode preference to local storage
_Closes #0000_
1.
2.
1.
2.
=> add auto switch to $ mode

src/components/Global/NotificationCenter/NotificationTable/NotificationTable.styles.ts
=> fix z index on account

src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
=> Condensed mode disable if have not enough candles

src/pages/Explore/Explore.tsx, src/pages/Trade/TradeCharts/TradeChartsHeader/TradeChartsHeader.tsx
=> revert dollar mode icon switch

public/ambient-token-list.json, src/ambient-utils/constants/ambient-token-list.json, src/ambient-utils/constants/defaultTokens.ts, src/ambient-utils/dataLayer/functions/getMoneynessRank.ts, src/ambient-utils/dataLayer/functions/stablePairs.ts
added https://scrollscan.com/token/0x01f0a31698c4d065659b9bdc21b3610292a1c506 to Ambient Token List
_Closes #0000_
1.
2.
1.
2.
=> add weETH on Scroll

src/ambient-utils/constants/index.ts, src/components/Chat/ChatPanel.tsx, src/contexts/ChainDataContext.tsx
=> fix alchemy api key

src/components/Chat/ChatConstants/ChatEndpoints.ts, src/components/Chat/ChatPanel.tsx, src/components/Chat/ChatToaster/ChatToaster.module.css, src/components/Chat/MessagePanel/Room/Room.tsx, src/components/Chat/Service/ChatApi.tsx
- Css fix for chat toastr component to not block confirm button.
- Verification message string will be fetched from chat-server app
_Closes #0000_
1.
2.
1.
2.
=> Chat toastr css fix, verification message fetch from backend

src/components/Futa/Chart/ScatterChart/ScatterChart.tsx
=> Futa : changed circle hover fill color

package.json, src/App/components/PageHeader/PageHeader.tsx, src/contexts/TradeDataContext.tsx
change default pool range width to +/-0.5% for pairs of stable tokens and pairs of ETH/Staked ETH tokens.
All other pool still default to +/-10%
###
=> default range width to 0.5% for stable pools

index.html
add dynamic site metadata to index.html
requires the following env variables:
VITE_META_DESCRIPTION="Swap cryptocurrencies like a pro with Ambient. Decentralized trading is now better than ever."
VITE_META_KEYWORDS="Ambient, swap, trade, decentralized, trading, cryptocurrencies, crypto, blockchain, finance, defi, defi trading, defi swap, defi exchange, defi liquidity, defi protocol"
VITE_OG_TITLE="Ambient Finance"
VITE_OG_DESCRIPTION="Swap cryptocurrencies like a pro with Ambient. Decentralized trading is now better than ever."
VITE_OG_URL="https://ambient.finance"
VITE_SITE_TITLE="Ambient Finance"
VITE_OG_IMAGE="https://us.ambient.finance/previewimage.png"
VITE_TWITTER_SITE="@ambient_finance"
_Closes #0000_
1.
2. …
=> add dynamic site metadata

src/components/Form/Button.tsx, src/index.css, src/pages/Swap/Swap.module.css, src/styled/Components/Header.ts
=> Add styled changes

src/components/Chat/Service/useChatSocket.tsx
added condition to use chat-server to open ws connection
_Closes #0000_
1.
2.
1.
2.
=> checking address to open ws connection

src/components/Global/DollarizationModalControl/DollarizationModalControl.module.css, src/components/Global/DollarizationModalControl/DollarizationModalControl.tsx, src/components/Global/TransactionSettingsModal/TransactionSettingsModal.tsx, src/components/Swap/SwapExtraInfo/SwapExtraInfo.tsx, src/components/Trade/Limit/LimitExtraInfo/LimitExtraInfo.tsx, src/components/Trade/Range/ConfirmRangeModal/SelectedRange/SelectedRange.tsx, src/components/Trade/Range/RangeExtraInfo/RangeExtraInfo.tsx, src/contexts/PoolContext.tsx, src/pages/Trade/Trade.tsx
add dollarization mode toggle to setting so users can disable on /swap
_Closes #0000_
1.
2.
1.
2.
=> add dollarization mode toggle to setting modals

src/components/Futa/Chart/ScatterChart/ScatterChart.tsx, src/components/Futa/Chart/ScatterChart/Xaxis.tsx, src/components/Futa/Chart/ScatterChart/useScatterChartData.ts, src/components/Futa/SearchableTicker/SearchableTicker.tsx, src/contexts/AuctionsContext.tsx
- increased the size of all types of circles by 2 px each
- removed the '12h' labels
- added 'd' after the numbers below each of the lines marking days
-  filtered the dots visible on the chart to only the auctions shown in the displayed list
=> scatter chart last changes

src/components/Portfolio/PortfolioBanner/PortfolioBannerAccount/PortfolioBannerAccount.tsx
patch to fix default jazzicons for avatars
https://scroll-us.ambient.finance/0x76f9E4F8d044c6bc100245Bafb688918F001Dc80
1.
2.
1.
2.
=> fix missing jazz icon default avatars

src/components/Futa/Chart/ScatterChart/ScatterChart.tsx, src/components/Futa/Chart/ScatterChart/Xaxis.tsx
=> Fix scatter chart x scale updated based on the data when show Complete was turned on

src/App/components/Sidebar/SidebarAccordion.tsx, src/ambient-utils/types/mediaQueries/index.ts, src/ambient-utils/types/mediaQueries/maxWidth.ts, src/ambient-utils/types/mediaQueries/minWidth.ts, src/components/Trade/TradeTabs/Orders/orderRowConstants.tsx, src/components/Trade/TradeTabs/Ranges/rangeRowConstants.tsx, src/components/Trade/TradeTabs/Transactions/txRowConstants.tsx, src/pages/Home/Home.tsx, src/utils/hooks/useMediaQuery.ts
* Create types to define common breakpoints as string-literal unions
* Apply typeguarding throughout app where common breakpoints are used
[ none ]
This refactor is syntactic sugar only. There should be no functional changes in how the app behaves.
[ none ]
None, ready for merge
=> Centralize media query breakpoints

src/App/App.css, src/App/components/PageHeader/PageHeader.tsx, src/components/Global/ContentContainer/ContentContainer.module.css, src/components/Global/ContentContainer/ContentContainer.tsx, src/components/Global/DropdownMenu2/DropdownMenu2.styles.ts, src/components/Global/DropdownMenu2/DropdownMenu2.tsx, src/index.css, src/pages/Swap/Swap.tsx
=> fix swap overflow and page header

package.json, src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx, src/App/hooks/useCreateRangePosition.ts, src/App/hooks/useSendInit.ts, src/components/LimitActionModal/LimitActionModal.tsx, src/components/RangeActionModal/RangeActionModal.tsx, src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx, src/components/Trade/Limit/ConfirmLimitModal/ConfirmLimitModal.tsx, src/components/Trade/Range/ConfirmRangeModal/ConfirmRangeModal.tsx, src/components/Trade/Reposition/ConfirmRepositionModal/ConfirmRepositionModal.tsx, src/components/Trade/TradeModules/SubmitTransaction/SubmitTransaction.tsx, src/components/Trade/TradeModules/SubmitTransaction/TransactionException/TransactionException.tsx, src/components/Trade/TradeModules/TradeConfirmationSkeleton.tsx, src/contexts/CrocEnvContext.tsx, src/pages/InitPool/InitConfirmation.tsx, src/pages/InitPool/InitPool.tsx, src/pages/Trade/Limit/Limit.tsx, src/pages/Trade/Range/Range.tsx, src/pages/Trade/Reposition/Reposition.tsx, src/pages/Trade/Swap/Swap.tsx, src/utils/TransactionError.ts, yarn.lock
Made error handling less verbose and added handling for the edge case of provider-signer chain mismatch (but the most measures to address this are in [this SDK PR](https://github.com/CrocSwap/sdk/pull/49)).
_Closes #0000_
1. Try to somehow force a rare condition of a chain mismatch? I could never get it to happen on its own.
1. Every wallet is its own unique pile of bugs and weird behaviors.
Merge the SDK PR and update its version here.
=> Clean up error handling and improve chain switching

public/scroll-badge/1.json, public/scroll-badge/2.json, public/scroll-badge/3.json, public/scroll-badge/4.json
Update the badge description as per Scroll team's request.
=> update scroll badge description

src/components/Chat/ChatRenderUtils.tsx
=> fix wallet dropdown avatar
