src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx

The minimum ETH balance requirement had been set to 0.1 ETH to avoid situations where a user could not cover the cost of gas in addition to the deposit quantity.
This value has been reduced to 0.025 ETH and extra logic has been added to specifically alert the user when their ETH balance is not sufficient to cover gas.
_Closes #0000_

reduce minimum eth balance for deposits

---

src/components/Global/PoolCard/PoolCard.module.css
src/components/Global/PoolCard/PoolCard.tsx

update pool cards on homepage to reflect that APR is a 24h stat and clarify 'Vol.' refers to volume and not volatility.
new: 
old: 
_Closes #0000_

update display of pool card on homepage

---

src/components/Global/Tabs/Apy/Apy.tsx
src/utils/hooks/useProcessRange.ts

Range positions with an APR calculated to exceed 1,000% have the APR display overflowing the container.
this PR updates the display to not show the decimal value:

update APR truncation to display "1,000%+" apr

---

src/components/Trade/TradeTabs/TradeTabs2.module.css
src/components/Trade/TradeTabs/Transactions/Transactions.tsx

fixes issue where some transaction rows are cut off when a candle is selected. 
This seems to happen only when 6-9 transactions are intended to be displayed.
_Closes #0000_
1. clicking various candles display expected number of rows
2.
1. different candles will have different number of transactions to display, some requiring a 'View More' button
2.

bug fix: some transaction rows cut off when candle selected

---

src/components/Global/TransactionDetails/TransactionDetailsSimplify/TransactionDetailsSimplify.tsx
src/utils/hooks/useProcessTransaction.ts

add logic to display full account and token addresses when space is sufficient in transaction details:
before update:
after update:
_Closes #0000_
1.
2.
1.
2.

show full addresses in tx details

---

src/components/Portfolio/ExchangeBalance/Deposit/Deposit.module.css
src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx
src/components/Portfolio/ExchangeBalance/Deposit/DepositCurrencySelector/DepositCurrencySelector.module.css
src/components/Portfolio/ExchangeBalance/ExchangeBalance.tsx
src/components/Portfolio/ExchangeBalance/Transfer/Transfer.module.css
src/components/Portfolio/ExchangeBalance/Transfer/Transfer.tsx
src/components/Portfolio/ExchangeBalance/Withdraw/Withdraw.module.css
src/components/Portfolio/ExchangeBalance/Withdraw/Withdraw.tsx

fix momentary display of incorrect token balances when user switches token selection in Exchange Balance module.
Closes #2523
1. switch between tokens for which you have wallet/dex balances and tokens for which you do not
2. observe temporary display of '...' when initially loading the module and when switching tokens
3.  verify that incorrect numbers do not appear for wallet/dex balances
4. verify that '0.00' is displayed when a user's wallet or dex balance is zero (depending on which section is open - deposit/withdraw/transfer)
1. This issue is most apparent when using a slow connection (e.g. using a VPN)
2.

fix momentary display of incorrect balances in Exchange Balance module

---

src/components/Chat/FullChat/FullChat.tsx
src/components/Global/Account/AccountTabs/Exchange/ExchangeCard.tsx
src/components/Global/Tabs/TokenQty/TokenQty.tsx
src/components/Global/TokenSelectContainer/SoloTokenImport.tsx
src/components/Global/TransactionDetails/TransactionDetailsPriceInfo/TransactionDetailsPriceInfo.tsx
src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx
src/components/Swap/CurrencySelector/CurrencySelector.tsx
src/components/Swap/SwapButton/BypassConfirmSwapButton.tsx
src/components/Trade/Limit/ConfirmLimitModal/ConfirmLimitModal.tsx
src/components/Trade/Limit/LimitButton/BypassLimitButton.tsx
src/components/Trade/Limit/LimitCurrencySelector/LimitCurrencySelector.tsx
src/components/Trade/Range/ConfirmRangeModal/ConfirmRangeModal.tsx
src/components/Trade/Range/RangeButton/BypassConfirmRangeButton.tsx
src/components/Trade/Range/RangeCurrencySelector/RangeCurrencySelector.tsx
src/components/Trade/Reposition/BypassConfirmRepositionButton/BypassConfirmRepositionButton.tsx
src/components/Trade/Reposition/ConfirmRepositionModal/ConfirmRepositionModal.tsx
src/pages/InitPool/InitPool.module.css
src/pages/InitPool/InitPool.tsx
src/pages/Swap/Swap.tsx
src/pages/Trade/Trade.tsx
src/utils/hooks/useProcessOrder.ts

fix remaining token logo references that were not using the httpToUri transformation for IPFS addresses:
Example: ETH-UNI:  https://develop--ambient-finance.netlify.app/trade/market/chain=0x5&tokenA=0xD87Ba7A50B2E7E660f678A895E4B72E7CB4CCd9C&tokenB=0x1f9840a85d5af5bf1d1762f925bdaddc4201f984
_Closes #0000_
1.
2.
1.
2.

fix missing ipfs token logos

---

src/App/hooks/usePoolMetadata.ts
src/components/Trade/TradeTabs/Orders/Orders.tsx
src/components/Trade/TradeTabs/Ranges/Ranges.tsx
src/contexts/TradeTokenContext.tsx
src/utils/state/graphDataSlice.ts

This change implements the user_pool_limit_orders and user_pool_positions server endpoints for retrieving data specific to a user and the pool in view on the /trade route.
Closes #2525
Closes #2526
1.
2.
1.
2.

implement user/pool endpoints for position & limit retrieval

---

src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx
src/components/Portfolio/ExchangeBalance/Withdraw/WithdrawButton/WithdrawButton.module.css
src/components/Trade/Range/RangeButton/RangeButton.tsx
src/components/Trade/Reposition/RepositionHeader/RepositionHeader.tsx
src/components/Trade/TradeTabs/Ranges/Ranges.tsx
src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx
src/contexts/RangeContext.tsx
src/css/GlobalCssClassnames.css
src/pages/Trade/Range/Range.tsx
src/pages/Trade/Reposition/Reposition.tsx

When a user is repositioning or adding to a transaction, it is easy for them to lose track of which transaction they clicked on. This PR adds an active hover state to the position that is being repositioned.

Add figma hover states

---

src/App/functions/getFormattedNumber.ts
src/App/functions/swap/getPriceImpactString.ts
src/App/hooks/usePoolPricing.ts
src/components/Global/PoolCard/PoolCard.tsx
src/components/Global/Tabs/Apy/Apy.tsx
src/components/RangeDetails/RangeDetailsSimplify/RangeDetailsSimplify.tsx
src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx
src/components/Swap/CurrencySelector/CurrencySelector.tsx
src/components/Trade/Limit/LimitCurrencySelector/LimitCurrencySelector.tsx
src/components/Trade/Range/AdvancedModeComponents/AdvancedPriceInfo/AdvancedPriceInfo.tsx
src/components/Trade/Range/RangeCurrencySelector/RangeCurrencySelector.tsx
src/components/Trade/Range/RangePriceInfo/RangePriceInfo.tsx
src/components/Trade/Reposition/RepositionPriceInfo/RepositionPriceInfo.tsx
src/pages/InitPool/InitPool.tsx
src/pages/Swap/Swap.tsx
src/pages/Trade/Limit/Limit.tsx
src/utils/hooks/useProcessRange.ts

This change forces all number to get locally formatted into strings using US number formatting conventions (i.e. periods as decimal separators). 
Closes #2623
1.
2.
1.
2.

force US number formatting

---

src/App/components/PageHeader/PageHeader.tsx
src/App/hooks/useRecentPools.ts
src/components/Global/Sidebar/RecentPools/RecentPools.tsx
src/contexts/SidebarContext.tsx

* Gatekeep functionality in `PageHeader.tsx` to prevent addition of non-existent pools to the **Recent Pools** sidebar list
* Remove redundant action to add a pool to the **Recent Pools** sidebar list (existed both in `useRecentPools.ts` and `PageHeader.tsx`)
* General improvements to code in `useRecentPools.ts` file
I did consult with @miyuki-eto prior to documenting the issue to confirm that adding non-existent pools to the **Recent Pools** list is a bug and not a feature.
Closes #2583
1. Go to the deployed production [Ambient Finance](https://ambient.finance/) site
2. Navigate between token pairs, note that every token pair is added to the **Recent Pools** sidebar list regardless of whether a pool exists for that pair …

Remove uninitialized pools from recent list

---

src/utils/hooks/useOnClickOutside.ts

- Initially the bug was noticed while using the mouse to select input in the exchange balance modal in the header and then clicking outside.
- This would cause the modal to close
- This behaviour seemed to happen for any modals/dropdowns using the `useOnClickOutside` hook
NOTE: Any modals/dropdowns will now close as soon as you click outside i.e. you won't be able to "hold your mouse" outside the given div and then let go to close the modal
_Closes #2628 
- Open any header element i.e. exhcangebalance modal
- Drag the mouse from the modal to outside the modal
- Verify that this does not close the given modal
- Clicking outside the modal however should still close the given modal
**Environmental conditions which may …

Revert `useOnClickOutside`'s handler from using mouseup to mousedown

---

src/App/hooks/usePoolMetadata.ts

Increase the number of pool limit and range records requested when a user loads a pool from 50 to 200.
Closes #2635
1. ETH-USDC pool ranges tables should now display close to 200 records by default
2.
1.
2.

increase pool limit/range records requested from 50 to 200

---

src/App/hooks/useTokenSearch.ts

Add a tertiary sort to `useTokenSearch.ts` for alphanumeric sorting (eg: 1 => 2 => A => B)
_none_
1. Open Token Select modal; confirm tokens appear in anticipated sequence.
2. Enter search input; confirm tokens appear in anticipated sequence.
* First sort: Ambient vs other lists
* Second sort: number of lists a token appears on
* Third sort: alphanumeric
* Final sort: original sequence
_none_
Logic is self-contained on line 173 of `useTokenSearch.ts`, feel free to tweak

refactor `useTokenSearch.ts` to use tiebreaker sort alphanumeric

---

src/pages/Chart/Chart.tsx

This one was a tricky one despite the simplicity of the change. Since the chart container is static, scrolling doesn't work naturally, which is why every action needs to be customized. This is trickier when taking into account that both trackpad and mouse (scrollwheel) behaviour needs to be taken into account, with no way to distinguish between the two when analyzing the mouseEvents. 
Since scrollwheel cannot scroll horizontally, I kept the option + vertical scroll = horizontal scroll functionality that currently exists, and then added functionality for horizontal scroll via the trackpad. By using that physical limitation to distinguish between the two sources of scrolling, I was able to implement a version of horizontal scrolling via the trackpad. 
Unfortunately, due to the non-linear …

Allow panning in chart

---

src/App/components/PageHeader/PageHeader.tsx

ens supports unicode. if a user goes to `ambient.finance/김정은.eth`, since ze page title issa read from ze url path, it will display `%EA%B9%80...eth ~ Ambient`. dis commit fixes it so it shows `김정은.eth ~ Ambient`
none
1. jussa smol change. go try to peek into a random ens with emojis or special characters in it n u will see ze correct title shown
1. dunno

fix page title for ens with special characters

---

src/App/components/Sidebar/Sidebar.module.css
src/components/Global/Analytics/Analytics.styles.ts
src/components/Global/Analytics/PoolRow.tsx
src/components/Global/SIdebarFooter/SidebarFooter.module.css
src/components/Global/SIdebarFooter/SidebarFooter.tsx

Fix sticky footer moving on mobile devices.
There are small screen widths at which it would make sense to continue showing the combined logo/symbol column after removing the Price column.
-Added a fix where we show the pool names whenever we have the space.
_Closes #0000_
1.
2.
1.
2.

fix sticky footer

---

src/pages/Trade/Trade.tsx

Chart will now jump closed when the height of it starts to fail to shrink the chart further. 
_Closes #2735_

Chart will now jump closed if it is left in a too small state

---

src/components/Global/Analytics/TopPools.tsx

Remove the limiter on line items to display in `TopPools.tsx` in the `Explore.tsx` module
Closes #2794
1. Navigate to the `/explore` URL path
2. Observe the pools rendered in the DOM
3. Sort by various sortable criterial (click column headers) and observe if any pools disappear
1. Number of pools on `0x5` (Goërli) may not hit the limiter
Open to requests to tweak any of the sort logic. Otherwise ready for merge UwU

remove `POOL_COUNT` limiter from `TopPools.tsx` component file

---

src/App/functions/fetchContractDetails.ts

Some old tokens, most notably MKR, don't fully adhere to ERC-20 ABI and return `bytes32` instead of `string` for `name()` and `symbol()` methods. Currently this breaks transaction and range pages where such tokens are displayed.
This PR fixes that by trying to decode `bytes32` to `string` in the event of an exception while calling those methods. I think this is the simplest solution and should handle all cases, or at least I couldn't find any popular tokens with non-`string` and non-`bytes32` types for those methods. This fix doesn't affect tokens that implement ERC-20 properly.
None
1. Open [MKR/ETH pool](https://ambient.finance/trade/market/chain=0x1&tokenA=0x0000000000000000000000000000000000000000&tokenB=0x9f8F72aA930 …

Fix fetching non-string token name and symbol

---

src/App/hooks/useTokenSearch.ts

Add a sort priority level in `useTokenSearch.ts` to tokens in the universe for tokens that are also in the user's connected wallet
Closes #2823
1. Open the app and connect a wallet
2. Open the token selector modal
3. Selectable tokens should appear in the following order when no search input has been entered: native token => USDC => tokens in the user's wallet AND a recognized list => other tokens in lists
1. Will only be testable when a wallet is connected to the app
2. User must have a token in their wallet which is on one of the recognized lists (currently Ambient, Uniswap, CoinGecko) and on the current chain other than USDC or native …

Add Wallet tokens to modal

---

src/components/Global/TokenSelectContainer/SoloTokenSelectModal.tsx
src/components/RangeActionModal/WarningBox/WarningBox.module.css

Increasing the width of the warning box button to accommodate the text causes an overflow issue.
As tgus us a reusable component, we should avoid adding an explicit width or height to any of its elements.
This PR resolves that issue.
The warning text for WETH has been changed from 'I understand, use WETH' to simply 'use WETH'.
This is to make sure the text fits nicely inside of the modal without messing up the existing layout.
The text can be changed to any other text but let's keep it on the short side if possible.
Another option is to simply move that button unto the next line. We couldn't need it in the same row as the text in that case.
_Closes #0000_

fix warning box button overflow issue

---

src/utils/hooks/useUrlParams.ts

Fix token race condition that causes the logoUri to be empty
Issue was that on initial load, there is no token lookup, so it fetches the actual contract (async call intended for custom tokens), which doesn't contain logoUri
Then the token lookup appears, and the lookup is made, which happens immediately 
Finally, the contract call returns, sets the token, which overrides the (correct) lookup 
Solution: Add a flag to the useEffect so that if the lookup occurs during a call to fetch contract, it will accept the first return and stop any subsequent attempts to set token. An assumption is made that the lookup will always return first. 
_Closes #2846_

Fix token race condition

---

docs/CODING-STYLE.md
src/components/Chat/ChatPanel.tsx
src/components/Chat/MessagePanel/InputBox/MessageInput.tsx
src/components/Global/SlippageTolerance/SlippageTolerance.tsx
src/components/Global/TransactionSettingsModal/TransactionSettingsModal.tsx
src/pages/Trade/TradeCharts/TradeCharts.tsx

* Refactor app to respond to keyboard events defined by `KeyboardEvent.code` and `KeyboardEvent.key` over `KeyboardEvent.charCode` and `KeyboardEvent.keyCode`
* `KeyboardEvent.code` maps to a physical key on the keyboard and is functionally equivalent to `KeyboardEvent.keyCode `
* `KeyboardEvent.key` maps to a character produced by a keyboard event (ie a keypress) and is functionally equivalent to `KeyboardEvent.charCode`
* Both [KeyboardEvent.charCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode) and [KeyboardEvent.keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) per MDN are deprecated features
* Eliminate use of `any` type annotation in updated function declarations
* Updated docs in `CODING-STYLE.md` to reflect this new …

Refactor char code and key code

---

package.json
src/components/Global/Analytics/Analytics.styles.ts
src/components/Global/Analytics/TokenDisplay.tsx
src/components/Global/DropdownMenu2/DropdownMenu2.styles.ts
src/components/Global/NotificationCenter/ActivityIndicator/ActivityIndicator.styles.ts
src/components/Global/NotificationCenter/NotificationTable/NotificationTable.styles.ts
src/components/Home/Landing/TradeNowButton/TradeNowButton.styles.ts
src/components/Trade/TableInfo/TableInfo.styles.ts
src/pages/Explore/Explore.tsx
src/pages/TestPage/TestPage.tsx
src/styled/Common.ts
src/styled/Components/Header.ts
src/styled/Components/Range.ts
src/styled/Components/Sidebar.ts
yarn.lock

Adds class names that will link you back to the component in question. 
Adds babel-plugin-styled-components

Add use styled components macro to display class names

---

src/components/Trade/TradeModules/ExtraInfo/ExtraInfo.tsx

There is an ongoing issue where the `ExtraInfo` remains visible even when the input fields are empty. To replicate this, please enter an amount in the 'swap quantities' field, expand the extra information by selecting the dropdown, and then remove the entered amount. The expected functionality is for the extra information to retract, but it persists in its expanded state. This pull request is intended to rectify this behavior.
Current:
Expected:

Fix Extra Info persistent logic

---

package.json
src/index.tsx

A bunch of these warnings were appearing since the addition of styled components.  This keeps from forwarding those props.
Solution from https://github.com/styled-components/styled-components/issues/4049

Add isValidProp to keep from forwarding styled-component props

---

src/components/Global/Tabs/TableMenu/TableMenuComponents/OrdersMenu.tsx
src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx
src/components/Global/Tabs/TableMenu/TableMenuComponents/TransactionsMenu.tsx
src/contexts/TradeTableContext.tsx
src/pages/Trade/Trade.tsx

clicking or tapping a Copy button from a trade or account page should now load the relevant module as the active mobile component.
Closes #2922

move active mobile component to trade context

---

src/assets/images/info.svg
src/components/Global/TabComponent/TabComponent.module.css
src/components/Global/TabComponent/TabComponent.tsx
src/components/Trade/TradeTabs/TradeTabs2.tsx

add info icon and background to trade icons to keep them consistent
_Closes #3001 _

add info icon and background to trade icons to keep them consistent

---

src/styled/Components/Trade.ts

fix dropdown menu being partially obscured on mobile
_Closes #3020 _

fix dropdown menu being obscured on mobile

---

src/components/NoChartData/NoChartData.module.css
src/components/NoChartData/NoChartData.tsx
src/components/Trade/Reposition/RepositionHeader/RepositionHeader.module.css
src/pages/Trade/Trade.tsx

Fix Refresh button  appearing while the trade table is fully expanded
_Closes #3018_

hide refresh button when trade table is expanded

---

src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx

deposit button was not getting disabled when the user had input a quantity greater than their approval or wallet balance.
_Closes #0000_
1.
2.
1.
2.

bug fix: deposit button not disabled when balance/approval insufficient

---

package.json
src/pages/Trade/Trade.tsx
src/styled/Components/Trade.ts
yarn.lock

- This visually fixes the two pivot points/handles that are present courtesy of the re-resizable container. 
- The actual fix for this bug is to disable the pivot points/handles for all locations except bottom. Having tried that and looking at their implementation, there seems to be a bug with their library. Leaving the actual fix in there for when it gets resolved
- Our chart is actually capable of being resized from its bottom corners which results in some interesting sizing (I wouldn't recommend doing that)
Before:
After:
_Closes #0000_
1.
2.
1.
2.

Chart ui fixes based off release-v1.5

---

src/App/hooks/useHandleRangeButtonMessage.ts
src/components/Trade/Range/RangeTokenInput/RangeTokenInput.tsx
src/pages/InitPool/InitPool.tsx
src/pages/Trade/Range/Range.tsx
src/pages/Trade/Range/useRangeInputDisable.tsx

To test:
- Creating range in normal tap should still function as normal (message when inputting above your balance etc)
- Pool init now has this kind of messaging when trying to create range positions.

Refactor range button message + InitPool reorder state fxns

---

src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx
src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx

- position data is linked to the specific row in the transactions table
- when a pool transaction is submitted, it changes row positions automatically (sorted by latest transaction)
- this results in the confirmation modal "updating" itself to show position data for the pool transaction for the previous row 
- we now cache the position data such that the position data is only passed down to the modals if its for the same position or the modal's being opened
_Closes #0000_
1.
2.
1.
2.

Fix RangeActionModal showing incorrect position after submitting transaction

---

src/components/Global/Account/AccountTabs/Exchange/ExchangeCard.module.css
src/components/Global/Account/AccountTabs/Wallet/WalletCard.module.css

- Auto aligning the symbol and giving the token name 40% of space in the exchange balance and wallet balance rows
Closes https://github.com/CrocSwap/ambient-ts-app/issues/3121
1.
2.
1.
2.

Fixing overlap of token name and symbol when token name is long

---

src/App/functions/fetchTokenPrice.ts

USDC value queries to the Analytics server were failing due to a missing parameter. Adding the asset_platform parameter should fix the TVL calculations in the Top Pools.

hotfix: USD token value queries on scroll

---

src/App/components/PageHeader/Account/WalletDropdown/WalletDropdown.tsx
src/utils/interfaces/NetworkIF.ts

* Refactor `WalletDropdown.tsx` logic to pull wallet balance and USD equiv for second default token on chain
* Minor update to the shape of `NetworkIF`
Closes #3200
1. Connect to each supported network in sequence
2. Confirm the wallet dropdown correctly shows quantity and USD equiv for the default token pair
Values rendered are network-specific and not available if the user does not have a connected wallet
None, ready for merge!

Fix wallet dropdown balances

---

src/components/Global/ContentContainer/ContentContainer.module.css
src/components/Global/ContentContainer/ContentContainer.tsx
src/components/Trade/TradeModules/TradeModuleSkeleton.tsx
src/pages/Trade/Trade.tsx
src/styled/Components/Trade.ts

The padding on the trade module on mobile devices occupies too much space.
This PR should reduce that and give us more horizontal space to work with:
_Closes #0000_
1.
2.
1.
2.

refactor trade mobile padding and dropdown size

---

src/components/Form/TokenInputWithWalletBalance.tsx
src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
src/components/Trade/Limit/LimitTokenInput/LimitTokenInput.tsx
src/pages/Trade/Limit/Limit.tsx
src/pages/Trade/Swap/Swap.tsx

add dynamic ETH offset for swaps/limits
Closes #3222
1.
2.
1.
2.

add dynamic ETH offset for swaps/limits

---

src/App/functions/fetchTokenPrice.ts

Prices for ETH and USDC were hardcoded to get returned regardless of server availability to return up-to-date prices. This change moves these hardcoded values to only get returned when the server fails to respond with prices in a timely manner.
1.
2.
1.
2.

move hardcoded usd prices for ETH / USDC to fallback

---

src/App/components/PageHeader/Account/WalletDropdown/WalletDropdown.tsx
src/App/functions/fetchCandleSeries.ts
src/App/functions/fetchPoolLiquidity.ts
src/App/functions/fetchTokenPrice.ts
src/App/functions/getLimitOrderData.ts
src/App/functions/getPoolStats.ts
src/App/functions/getPositionData.ts
src/App/functions/getTransactionData.ts
src/components/Form/TokenInputWithWalletBalance.tsx
src/components/Global/Account/AccountTabs/Exchange/ExchangeCard.tsx
src/components/Global/Account/AccountTabs/Wallet/WalletCard.tsx
src/components/Trade/Range/RangePriceInfo/RangePriceInfo.tsx
src/contexts/CrocEnvContext.tsx
src/pages/InitPool/InitPool.tsx

this change removes the hardcoded fallback value for ETH and replaces it with an on-chain call for the current price of the ETH-USDC pool on the active chain.
_Closes #0000_
1.
2.
1.
2.

use ETH-USDC pool price as ETH value fallback

---

package.json
src/App/components/PageHeader/Account/WalletDropdown/WalletDropdown.tsx
src/App/functions/fetchCandleSeries.ts
src/App/functions/fetchPoolLiquidity.ts
src/App/functions/fetchTokenPrice.ts
src/App/functions/getLimitOrderData.ts
src/App/functions/getPoolStats.ts
src/App/functions/getPositionData.ts
src/App/functions/getTransactionData.ts
src/components/Form/TokenInputWithWalletBalance.tsx
src/components/Global/Account/AccountTabs/Exchange/ExchangeCard.tsx
src/components/Global/Account/AccountTabs/Wallet/WalletCard.tsx
src/components/Trade/Range/RangePriceInfo/RangePriceInfo.tsx
src/contexts/CrocEnvContext.tsx
src/pages/InitPool/InitPool.tsx

this change removes the hardcoded fallback value for ETH and replaces it with an on-chain call for the current price of the ETH-USDC pool on the active chain.
1.
2.
1.
2.

Hotfix: use eth/usdc pool price as eth value

---

src/pages/Chart/Chart.tsx

Ben Wolski, [Dec 12, 2023 at 4:37:42 PM]:
This PR adjusts the boundaries of the noGoZone. I think the only thing left to investigate/fix is the unexpected trade direction reversal when you drop the limit line exactly on the boundary. Sometimes this causes the trade direction to reverse and sometimes it does not. https://github.com/CrocSwap/ambient-ts-app/pull/3282
The test for proper functionality is that when you drop the limit line on the high boundary and click the minus button, then the 'Limit Below Minimum Price' message should appear. Conversely, when you drop the limit line on the low boundary and click the plus button, then the 'Limit Above Maximum Price' message should appear. You shouldn't have to click the minus/plus buttons multiple times to get that message to appear after …

adjust noGoZone boundaries basked on ticks

---

src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
src/components/Trade/Limit/LimitTokenInput/LimitTokenInput.tsx

adds three significant digits to small estimated input/output quantities for swaps/limits
e.g.
_Closes #0000_
1.
2.
1.
2.

increase precision to 6 digits in swap/limit estimations

---

src/components/Trade/TradeTabs/Transactions2/Transactions2.tsx
src/components/Trade/TradeTabs/Transactions2/TxHeader.module.css
src/components/Trade/TradeTabs/Transactions2/TxHeader.tsx

Speed up the trade tables, and make sure they consistently render to completion. The major change is a split of the width monitor from the column storage code. The columns are now memoized, instead, (vs useRef) which speeds things up. The reason for the speed up, is that the code in the useRef was recalculated every time the parent code updated, which was several times a second. After fixing this, The table also seemed to render blank upon load.
There seems to be a lingering and intermittent issue related to dynamic resizing. When resizing the window from large to small, the event observer seems to stop firing. This is an unsolved issue that may need solving in a new PR
```
// STEP 1: What is our target width, and how do we monitor it?
useEffect(() => {
const adjustColumnization = () => { …
```

Refactor new trade tables: for speed

---

src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx

Jeff asked to change Canto link from `beta.canto.io/lp` to `canto.io/lp`

update canto external URL

---

src/components/Global/PoolCard/PoolCard.module.css

Currently, the mobile version of the top pool card when on a scroll network is not the expected dimension.
This should resolve it.
_Closes #0000_

fix top pool card mobile on scroll

---

src/components/Global/NotificationCenter/ReceiptDisplay/ReceiptDisplay.tsx
src/components/Trade/TradeModules/SubmitTransaction/TransactionSubmitted/TransactionSubmitted.tsx
src/components/Trade/TradeModules/SubmitTransaction/TransactionSubmitted/TxSubmiitedSimplify.tsx
src/pages/Trade/Reposition/Reposition.tsx

updates hardcoded instances of buttons displaying the text 'View on Etherscan' to 'View on Block Explorer' in order to be correct on the scroll network.

update verbiage to 'View on Block Explorer'

---

src/components/Trade/Limit/ConfirmLimitModal/ConfirmLimitModal.tsx
src/components/Trade/TradeModules/TradeConfirmationSkeleton.tsx
src/pages/Trade/Limit/Limit.tsx

disable submit button on confirm modal for limit that will fail; display same error message that would be visible before confirm.
When the pool price moves while the user is mid-confirmation for a limit order and that order becomes invalid, the submit button was not getting disabled.
1.
2.
1.
2.

disable submit button on confirm modal for limit that will fail

---

src/contexts/TradeTableContext.tsx

prevent trade table from automatically switching when user reverses trade direction or updates limit line
trade table was automatically switching away from the limit or liquidity table when user reverses swap direction and away from transactions or liquidity when the limit line changes.
1.
2.
1.
2.

limit trade tab navigation automation to when module switches

---

src/components/Home/Stats/AmbientStats.tsx

the homepage should now show the sum of mainnet and scroll dex stats 
dex stats were appearing differently on Mainnet and Scroll
1.
2.
1.
2.

aggregate scroll and mainnet dex stats on homepage

---

src/components/RangeActionModal/RangeActionModal.tsx

prevent harvest confirmation modal from updating values after tx sent
harvest confirmation modals were updating after the position was reindexed to no longer contain accumulated fees
1.
2.
1.
2.

prevent harvest confirmation modal from updating values after tx sent

---

src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx
src/contexts/TradeTableContext.tsx

remove logic that keeps the trade tab from automatically switching when a transaction or liquidity position row is highlighted. Add logic to clear previous row highlighting when switching trade modules.
_Closes #0000_
1.
2.
1.
2.

fix trade tabs not switching when tx or position selected

---

package.json
src/pages/Portfolio/Portfolio.tsx

re-initialize the token balance list when user switches portfolios (possible without reloading page by clicking a username in chat)
previously, the token balance lists were not getting cleared out when a new name was clicked
1.
2.
1.
2.

fix wallet balance display bug when switching portfolios

---

src/App/hooks/useSidebar.ts
src/contexts/SidebarContext.tsx

* Change the global default status for the sidebar to be closed (overridden by persisted data and user actions)
* General code cleanup in `SidebarContext.tsx` and `useSidebar.tsx` files
Closes #3416
1. Open various pages on the app and see if the sidebar renders per expected patterns.
- Always closed by default unless a preference otherwise is persisted
- Opens if relevant depending on page and user actions
2. No page in the app should render with the sidebar open and have it immediately close
none

Collapse sidebar by default

---

src/components/Global/Pagination/usePagination.tsx
src/components/Trade/TradeTabs/Orders/Orders.tsx
src/components/Trade/TradeTabs/Ranges/Leaderboard.tsx
src/components/Trade/TradeTabs/Ranges/Ranges.tsx
src/components/Trade/TradeTabs/TableRows.tsx
src/components/Trade/TradeTabs/Transactions/Transactions.tsx

pull data for details modals from full data set, rather than just the data currently displayed on the paginated table
transaction details modals would disappear if the table updates and the transaction being viewed in the modal was no longer visible on the table.
1.
2.
1.
2.

prevent tx modal from disappearing when tx row no longer on displayed page

---

package.json
src/App/hooks/useAppChain.ts
src/ambient-utils/constants/networks/index.ts

add logic to use different lists of supported networks on different domains
It was possible to have the app on scroll.ambient.finance initialize connected to mainnet and send a swap to the scroll contract address on mainnet
1.
2.
1.
2.

fix missing unsupported network modal on network specific deploy

---

public/ambient-token-list.json
src/App/hooks/useSlippage.ts
src/ambient-utils/constants/slippage.ts
src/contexts/ChainDataContext.tsx
src/contexts/UserPreferenceContext.tsx

Refactors to `slippage.ts` file:
* Reorganize structure of central data file
* Improve use of explicit typing and deriving types from data
* Add a new L2 default slippage value to every transaction type
* Add a new L2 slippage preset array to every transaction type
Refactors to `useSlippage.ts` file:
* Access slippage defaults via webpack import rather than function params
* Manage (persist to and consume from) slippage tolerance value for L2 in local storage separately from L1; values should not overwrite each other
* Centralize local storage keygen logic
* Improve use of explicit typing
* Update logic in return statement to preferentially return L1 vs L2 data and methods depending on the type of active network
General
* Update other files interacting with `slippage.ts` and …

Update l2 slippage

---

src/App/hooks/usePoolMetadata.ts
src/App/hooks/useTokenPairAllowance.ts
src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx
src/components/Trade/Reposition/RepositionHeader/RepositionHeader.tsx
src/contexts/TradeDataContext.tsx
src/pages/Trade/Reposition/Reposition.tsx

create a method by which a custom default range width can be set for a specific pool
set default range/reposition width to +/-5% for ETH/USDB on Blast network.

set default range width to 5% on ETH-USDB

---

package.json
src/pages/Explore/Explore.tsx

only fetch fresh Top Pools data if user loads /explore before the pre-fetch is complete, or if they click the refresh button.
Top Pools on /explore was re-fetching when data was already available
1.
2.
1.
2.

prevent auto re-fetch of Top Pools for Explore

---

src/components/Trade/TradeTabs/Orders/orderRowConstants.tsx
src/components/Trade/TradeTabs/Ranges/rangeRowConstants.tsx
src/components/Trade/TradeTabs/Transactions/txRowConstants.tsx

keep user in same app instance when navigating to a /trade route from their own portfolio, but still open new app instance when opening a pool from another user's account.
_Closes #0000_
1.
2.
1.
2.

open /trade links in same tab when navigating from own portfolio

---

src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx

for some reason the .toNumber() function from the ethers bignumber library was failing, but switching to parseFloat seems to work.
rewards obtained from an SDK call were not appearing for some positions.
1.
2.
1.
2.

fix bignumber parsing for some rewards displays

---

src/pages/Trade/Reposition/Reposition.tsx

Cengiz re-added a useEffect (with an added if statement) to sync the chart and the slider that had been removed to fix an issue where clicking Reposition from /account for a pool other than the one active resulted in an unpredictable range width.
1.
2.
1.
2.

bug fix: liq. chart highlighting not full width for ambient repos.

---

src/pages/Trade/Range/Range.tsx
src/pages/Trade/Range/useRangeInputDisable.tsx

prevent disabling when range ticks not yet calculated
pool inputs sometimes getting stuck in a disabled state:
1.
2.
1.
2.

attempt to fix disabled pool inputs

---

docs/CODING-STYLE.md
src/ambient-utils/api/fetchContractDetails.ts
src/ambient-utils/types/token/TokenIF.ts
src/utils/hooks/useUrlParams.ts

* Refactor `fetchContractDetails.ts` such that the `fromList` property of the token data object can be populated a custom value for its provenance.
* Refactor `TokenIF` such that `fromList` is typed as a string-union to force tokens to be labeled with a recognized provenance.
* Refactor `TokenIF` into `ServerTokenIF` (conforms to Uniswap standard) and an extended `TokenIF` (describes our internal specification).
Closes #3515
Import a custom token by its hex address through the token selector.
None.
none, ready for merge!

Refactor imported token provenance

---

src/contexts/TradeDataContext.tsx

reset default range width to +/-10% for ETH/USDB
Doug
[12:34 PM]
Probably should push default range in ETH/USDB back to 10% since volatility is high
1.
2.
1.
2.

reset default range width to +/-10% for ETH/USDB

---

src/components/Trade/TradeTabs/Orders/orderRowConstants.tsx
src/components/Trade/TradeTabs/Ranges/rangeRowConstants.tsx
src/components/Trade/TradeTabs/Transactions/txRowConstants.tsx

prevent automatic uppercasing of token symbols in token pair displays on /account
these token symbols should start with a lowercase letter:
1.
2.
1.
2.

fix token symbol casing for token pair on /account

---

src/ambient-utils/api/fetchBatch.ts
src/ambient-utils/dataLayer/functions/getFormattedNumber.ts
src/components/Global/TransactionDetails/TransactionDetailsModal.tsx
src/components/Global/TransactionDetails/TransactionDetailsPriceInfo/TransactionDetailsPriceInfo.tsx
src/components/Global/TransactionDetails/TransactionDetailsSimplify/TransactionDetailsSimplify.tsx
src/components/OrderDetails/OrderDetailsModal/OrderDetailsModal.tsx
src/components/OrderDetails/OrderDetailsSimplify/OrderDetailsSimplify.tsx
src/components/OrderDetails/PriceInfo/PriceInfo.tsx
src/components/RangeDetails/PriceInfo/PriceInfo.module.css
src/components/RangeDetails/PriceInfo/PriceInfo.tsx
src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx
src/components/Trade/TradeTabs/Orders/orderRowConstants.tsx
src/utils/hooks/useProcessOrder.ts
src/utils/hooks/useProcessRange.ts

in some scenarios, the token logos appeared in reverse order of the active denomination: 
1.
2.
1.
2.

fix token logo order based on denom in tx/order/range details cards

---

src/contexts/CrocEnvContext.tsx
src/utils/batchedProvider.ts

Added a proxy RPC provider that batches `eth_call` requests and sends them to the [multicall](https://github.com/mds1/multicall) contract. Currently it's configured to send batches of either 20 requests or as many as have been collected within a 20ms stall window. If there's any kind of error during a multicall then a direct call will be attempted, so there should be no downside compared to the current code.
The proxy also caches forever responses to `eth_chainId` and `eth_accounts` requests. I don't think this will break anything, but usually these aren't supposed to be cached for very long. I don't think this applies to our use case though.
Most of the code here is adapted from [ethers v6](https://github.com/ethers-io/ethers.js/blob/main/src.ts/providers/provider-jsonrpc.ts#L504), so …

Add batched RPC proxy

---

src/components/Form/TokenInputWithWalletBalance.tsx
src/components/Form/WalletBalanceSubinfo.tsx
src/components/Swap/SwapTokenInput/SwapTokenInput.tsx

improve handling of scenario in which price impact query fails (Doug is looking into why it would fail) 
1.
2.
1.
2.

fix neverending input spinner when impact query fails

---

src/components/Global/Analytics/DexTokens.tsx
src/components/Global/Analytics/TopPools.tsx
src/pages/Explore/Explore.tsx

updated viewport height calculations to calculate based on the smallest viewport height 'svh' instead of the default 'vh' which made the styling look different in a browser window without a URL bar.
_Closes #0000_
1.
2.
1.
2.

update explore styling for installed mobile app

---

package.json
src/pages/Trade/Range/Range.tsx
yarn.lock

fixed in SDK. the amount of ETH required for a range mint was getting overestimated due to an incorrect calculation of the deposit skew by using the pool price + slippage instead of just the pool price.
_Closes #0000_
1.
2.
1.
2.

Fix eth overestimation for range mints

---

package.json
src/pages/Trade/Range/Range.tsx
yarn.lock

- bump SDK version to 0.3.9-1 to fix ambient liquidity queries
- also adds extra padding to swap and approval gas limits

Release 2.4.3

---

src/ambient-utils/constants/networks/ethereumMainnet.ts
src/components/Home/Landing/TradeNowButton/TradeNowButton.tsx
src/contexts/TradeDataContext.tsx

update homepage Trade Now link to use same link generation logic as the Trade button in the page header
also fix an issue where empty strings for the token symbols of the user's last selected pool were being interpreted as the token symbol of the Lenny Face token on the CoinGecko list, which has an empty string for a token symbol.
_Closes #0000_
1.
2.
1.
2.

fix trade now button on homepage reverting to previous token pair

---

src/components/Form/Button.tsx
src/components/Form/Form.styles.ts
src/components/Swap/SwapExtraInfo/SwapExtraInfo.tsx
src/components/Trade/TradeModules/ExtraInfo/ExtraInfo.tsx
src/pages/Trade/Swap/Swap.tsx

add different button styling when price impact exceeds 10% for the swap
previously, there was only a small warning when price impact was very large and the confirm/submit buttons looked the same
1.
2.
1.
2.

add extra warning when price impact greater than 10%

---

package.json
src/pages/Explore/useTokenStats.ts

Added a fallback on the price of the pool for that token with ETH when the CoinGecko price was missing.
previously, tokens for which the CoinGecko Price API  did not have a USD value available showed $0 for volume, TVL and fees on the Active Tokens table.
1.
2.
1.
2.

add ETH pool fallback for Active Token USD values

---

src/pages/Explore/useTokenStats.ts

- add ETH-[token] pool price fallback for USD values for tokens on Active Tokens missing a USD value from CoinGecko

Release 2.4.5

---

package.json
src/contexts/CrocEnvContext.tsx
src/contexts/TradeDataContext.tsx

If "ETH" is saved in local storage, use the first default token instead of searching the token universe for a match.
Native Ether saved to local storage as "ETH" could be confused with a different "ETH" token on the CoinGecko list.
1.
2.
1.
2.

fix ETH persistence bug

---

src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx

fix logic to prevent same token from being copied as both TokenA and TokenB
From bus:
Repro steps on Scroll with benwolski.eth connected and local storage cleared:
1. Go to home page and click on the wrsETH/ETH pool button
2. Click on the arrow to switch the swap tokens so that wrsETH is the input
3. Go to your account page, open the liquidity tab
4. Find the out of range position and click on its link, it will take you to a pool where both tokens are zero addresses
1.
2.
1.
2.

fix reposition copy button bug

---

src/App/hooks/useCreateRangePosition.ts
src/App/hooks/useSendInit.ts
src/components/LimitActionModal/LimitActionModal.tsx
src/components/RangeActionModal/RangeActionModal.tsx
src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx
src/components/Trade/Limit/ConfirmLimitModal/ConfirmLimitModal.tsx
src/components/Trade/Range/ConfirmRangeModal/ConfirmRangeModal.tsx
src/components/Trade/Reposition/ConfirmRepositionModal/ConfirmRepositionModal.tsx
src/components/Trade/TradeModules/SubmitTransaction/SubmitTransaction.tsx
src/components/Trade/TradeModules/SubmitTransaction/TransactionException/TransactionException.module.css
src/components/Trade/TradeModules/SubmitTransaction/TransactionException/TransactionException.tsx
src/components/Trade/TradeModules/TradeConfirmationSkeleton.tsx
src/pages/InitPool/InitConfirmation.tsx
src/pages/InitPool/InitPool.tsx
src/pages/Trade/Limit/Limit.tsx
src/pages/Trade/Range/Range.tsx
src/pages/Trade/Reposition/Reposition.tsx
src/pages/Trade/Swap/Swap.tsx
src/utils/TransactionError.ts

- update parseErrorMessage logic
- added button to copy entire error object as a string to clipboard
from bus: 
And one more thing, can you add error?.error?.data?.message || as the first selector to [parseErrorMessage](https://github.com/CrocSwap/ambient-ts-app/blob/develop/src/utils/TransactionError.ts#L61)? I noticed MetaMask returns the most useful error message in that field, otherwise "Internal JSON-RPC Error" gets selected and it's like the good old days of error messages being useless. Also would be nice if we had a button to copy the whole error object.
1.
2.
1.
2.

update parseErrorMessage logic

---

src/components/Form/TokenInputWithWalletBalance.tsx
src/components/Form/WalletBalanceSubinfo.tsx
src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx
src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
src/components/Trade/Limit/ConfirmLimitModal/ConfirmLimitModal.tsx
src/components/Trade/Limit/LimitTokenInput/LimitTokenInput.tsx
src/components/Trade/TradeModules/TradeConfirmationSkeleton.tsx
src/pages/Trade/Limit/Limit.tsx
src/pages/Trade/Swap/Swap.tsx
src/styled/Components/TradeModules.ts

add usd value difference percentage in swap & limit modules and confirmation modals when loss in value > 10%
bus
[1:42 PM](https://crocodile-labs.slack.com/archives/D06BRRNK6RW/p1712770948552519)
People keep losing money by swapping in illiquid pools. I don't know if other warnings show up for them, but I think the thing that will help the most is making the output value red if it's significantly lower than the input value: https://crocodile-labs.slack.com/archives/C03D4TRT2UC/p1708755917499229
Previously the USD values weren't showing up sometimes, but I haven't seen that happen in a while. I also haven't seen the swap impact warning not be displayed when it ideally should be (like I saw it happen once https://crocodile-labs.slack.com/archives/D06BRRNK6RW/p1709417493711649) but still I …

add percent diff in USD value

---

src/pages/Trade/Limit/Limit.tsx
src/pages/Trade/Swap/Swap.tsx

clear the secondary input quantity when token pair changes. This prevents the secondary input quantity from being used to calculate an incorrect USD value when the USD price changes before the input quantity is updated.

Fix usd diff warning flash on pair change

---

src/index.tsx

A year later, Metamask and Chrome still haven't fixed the issue where the wallet connection would fail if preloading is enabled. This PR brings back our old page reloading hack but now only applying it to Chrome (and its forks).

Bring back Metamask Chrome preloading fix

---

src/utils/hooks/useUrlParams.ts

If the swap page receives a single `tokenB` param instead of `token` or both `tokenA` and `tokenB`, the single token behavior will trigger.

support only tokenB

---

package.json

add support for links to swap page containing only a tokenB without a tokenA parameter, e.g. https://ambient.finance/swap/chain=0x13e31&tokenB=0x4fee793d435c6d2c10c135983bb9d6d4fc7b9bbds

Release 2.5.9

---

src/App/hooks/useTokens.ts
src/components/Trade/TradeModules/TradeModuleSkeleton.tsx
src/pages/Trade/Limit/Limit.tsx
src/pages/Trade/Range/Range.tsx
src/pages/Trade/Swap/Swap.tsx

added memoization to the needConfirmTokenA/B variables to try to avoid an intermittent issue (that cannot be intentionally reproduced) where the user is prompted to acknowledge tokens already on a list.
1.
2.
1.
2.

fix token acknowledgement request getting stuck on first load

---

src/App/hooks/useFetchPoolStats.ts
src/ambient-utils/constants/defaultTokens.ts
src/ambient-utils/dataLayer/functions/getPoolStats.ts
src/ambient-utils/dataLayer/functions/stablePairs.ts

instead of immediately falling back on the pool price when the CoinGecko token price is missing, first check if the token is a staked ETH token and fallback on the mainnet price of ETH instead
1.
2.
1.
2.

add ETH price fallback for staked ETH tokens

---

src/App/functions/checkPoolForWETH.ts
src/ambient-utils/api/fetchTopPairedToken.ts
src/ambient-utils/constants/index.ts
src/ambient-utils/dataLayer/functions/removeWrappedNative.ts
src/ambient-utils/dataLayer/functions/stablePairs.ts
src/components/Global/Explore/DexTokens.tsx
src/components/Global/TokenSelectContainer/SoloTokenSelect.tsx
src/components/Global/TokenSelectContainer/SoloTokenSelectModal.tsx
src/contexts/PoolContext.tsx
src/pages/Explore/useTokenStats.ts
src/utils/hooks/useUrlParams.ts

Dexscreener doesn't support native ETH and currently we need to remap it so the largest ETH/X pairs can get properly routed automatically.
Visiting `/swap/tokenB=0x5300000000000000000000000000000000000004&chain=0x82750` will now resolve to `USDC/ETH` pair on Scroll instead of `USDC/wETH` or `ETH/wETH` pair.

remap WETH to native ETH while fetching top paired token

---

src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx

Just a simple URL change in NetworkSelector.tsx. The current link to the Canto LP page is broken (gives a 404).
_Closes #0000_
n/a
n/a

Fix link to Canto

---

src/contexts/CrocEnvContext.tsx

this new change (now commented out) was causing metamask to automatically prompt the user to switch back to a network they just left if the new network was not supported by an Ambient app currently running in the same or different tab.
_Closes #0000_
1.
2.
1.
2.

remove auto network switching on mismatch

---

src/components/Global/TabComponent/TabComponent.tsx
src/components/Global/Tabs/TableMenu/TableMenuComponents/TransactionsMenu.tsx
src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx
src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx
src/utils/hooks/useProcessTransaction.ts

the zeros for the buy side of limit mint transactions were confusing people. 
also, as an interim solution to users getting confused as to why they can't remove limit orders or liquidity positions from the transactions table, a 'View Status' link has been added to the transactions rows for limits and ranges in place of a 'Copy Trade' button for a user's own limits and ranges.
1.
2.
1.
2.

add ellipsis for buy side of limit mint txs and view status button for limit and range transactions

---

src/components/Trade/Limit/ConfirmLimitModal/ConfirmLimitModal.tsx

clarified the wording to better indicate that the user is required to make a subsequent transaction in order to claim the output of a limit order:
several users had reached out for help indicating that they were not aware that a separate transaction was needed to receive the output of a limit order.
previous wording:
1.
2.
1.
2.

update limit confirmation wording

---

src/ambient-utils/dataLayer/functions/getPositionData.ts
src/components/RangeActionModal/RangeActionModal.tsx
src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx
src/components/Trade/TradeTabs/Ranges/Ranges.tsx

switched from `(await pos.queryAmbient()).seeds;` to `(await pos.queryAmbientPos()).liq`
ambient position liquidity values were not consistent due to an incorrect SDK call
1.
2.
1.
2.

fix ambient position liquidity queries

---

src/components/Trade/TradeTabs/Transactions/Transactions.tsx

re-implemented the switching functionality
switching to My Transactions no longer switched the view to display only the user's transactions
1.
2.
1.
2.

fix ability to switch to user's tx table on /trade

---

public/ambient-token-list.json
src/App/hooks/useFetchPoolStats.ts
src/ambient-utils/constants/ambient-token-list.json
src/ambient-utils/constants/defaultTokens.ts

for some reason the pool stats fetch was getting triggered with the default token addresses with the lastBlockNum === 0 useEffect dependency, so i removed it. This was causing pools with a token not on any token list to temporarily display the incorrect pool stats when the app was launched on that pool.
_Closes #0000_
1.
2.
1.
2.

fix pool stats fetch for ETH-Sinu on first app load

---

package.json
src/App/hooks/useHandleRangeButtonMessage.ts

- fixed crash when navigating directly to the Range module on /trade from /account/liquidity without first entering a value in the trade module

fix crash navigating to range module from liquidity table on /account

---

src/App/hooks/useTokens.ts

change Promise.all to Promise.allSettled for token list retrieval so the successfully retrieved lists are saved even when one fails.
_Closes #0000_
1.
2.
1.
2.

prevent failure to save token lists when one URI fails

---

src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx

added the value of the accumulated fees to the total value displayed on the initial screen of the range details cards
USD values shown on the default screen of the range details modal did not add the value of accumulated rewards/fees.
1.
2.
1.
2.

fix total value display in range details modal

---

src/App/hooks/useFetchPoolStats.ts
src/contexts/ExploreContext.tsx
src/contexts/PoolContext.tsx
src/pages/Trade/TradeCharts/TradeChartsComponents/TradeChartsTokenInfo.tsx

- display the inverted pool price change percentage when trade denomination switches
- use the current pool price from the provider instead of from gcgo for comparing with the 24h past price to determine 24h change percent
_Closes #0000_
1.
2.
1.
2.

fix pool price change percentage displays

---

src/index.css

minor syntax issue
Before
After

fix typo in `index.css` file

---

src/ambient-utils/constants/index.ts
src/components/Futa/Navbar/Navbar.tsx
src/components/Global/TutorialComponent/TutorialComponent.tsx
src/components/Global/TutorialOverlay/TutorialOverlayUrlBased.tsx
src/contexts/Futa/FutaHomeContext.tsx

- Auction page empty tutorial set problem fixed once navigated from profile page
- Show tutorials default option added into menu (will use env value if user not set it from toggle)
_Closes #0000_
1.
2.
1.
2.

Futa Tutorials | Auction page fix & Default option feature for users

---

src/components/Chat/FullChat/FullChat.tsx

Fixes [https://github.com/CrocSwap/ambient-ts-app/security/code-scanning/1](https://github.com/CrocSwap/ambient-ts-app/security/code-scanning/1)
To fix the problem, we need to ensure that all occurrences of the `&` character in the `params` string are replaced with ` / `. This can be achieved by using a regular expression with the global flag (`g`). The `replace` method will then replace all occurrences of the `&` character, not just the first one.
- Update the `params.replace('&', ' / ')` call to use a regular expression with the global flag.
- The change will be made in the `src/components/Chat/FullChat/FullChat.tsx` file on line 118.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert no. 1: Incomplete string escaping or encoding

---

e2e/helpers/utils.ts

Fixes [https://github.com/CrocSwap/ambient-ts-app/security/code-scanning/2](https://github.com/CrocSwap/ambient-ts-app/security/code-scanning/2)
To fix the problem, we should avoid logging the entire `process.env` object. Instead, we can log only non-sensitive information or remove the logging statements altogether if they are not necessary. If specific environment variables need to be logged for debugging purposes, ensure they do not contain sensitive information.
1. Identify and remove or replace the logging of `process.env` on lines 76, 77, and 78.
2. Ensure that no sensitive information is logged by replacing the logging statements with safer alternatives.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert no. 2: Clear-text logging of sensitive information

---

src/components/Portfolio/PortfolioBanner/PortfolioBannerAccount/PortfolioBannerAccount.tsx

* Fix display bug on `/account` page
[ none ]

hotfix to displayed address on `PortfolioBannerAccount.tsx` file

---

src/App/App.tsx
src/App/components/PageHeader/ExchangeBalanceDropdown/ExchangeBalanceDropdown.tsx
src/components/Global/BottomSheet/BottomSheet.module.css
src/components/Global/BottomSheet/BottomSheet.tsx
src/components/Global/DropdownMenu2/DropdownMenu2.tsx
src/components/Global/Modal/Modal.module.css
src/components/Global/Modal/Modal.tsx
src/components/Global/TokenSelectContainer/SoloTokenSelectModal.module.css
src/components/Global/TokenSelectContainer/SoloTokenSelectModal.tsx
src/contexts/BottomSheetContext.tsx
src/contexts/GlobalContexts.tsx
src/pages/common/TestPage/TestPage.tsx
src/pages/platformAmbient/Trade/TradeCharts/TradeChartsComponents/ChartSkeleton.module.css
src/pages/platformAmbient/Trade/TradeCharts/TradeChartsComponents/ChartSkeleton.tsx

CREATE BOTTOM SHEET COMPONENT WITH SWIPE GESTURES ON MOBILE
_Closes #0000_
1.
2.
1.
2.

Improve slide animation for bottom sheet modal

---

src/assets/images/tokens/exports.ts

temporarily remove the locally hosted SCR token logo so as to not apply the real SCR logo to fake SCR tokens before launch

temporarily remove SCR local token logo

---

public/ambient-token-list.json
src/App/hooks/useTokens.ts
src/ambient-utils/constants/ambient-token-list.json
src/ambient-utils/constants/defaultTokens.ts
src/ambient-utils/dataLayer/functions/stablePairs.ts

Add list of tokens found on trusted lists to be excluded from token universe. 
Coingecko's token list for the scroll network was found to have a mistaken listing for the mainnet address:
_Closes #0000_
1.
2.
1.
2.

Remove incorrect token listing for stakestone on scroll

---

src/contexts/ExploreContext.tsx

remove delay before fetching top pools
the delay had been added to stagger provider calls made on initial app load. The relevant provider calls are no longer being made on /explore. 
_Closes #0000_
1.
2.
1.
2.

remove delay before fetching top pools

---

package.json
src/App/hooks/useTokens.ts
src/ambient-utils/constants/tokenListURIs.ts

- re-enable scrollTech's token list for testnet
- specifically exclude scrollTech's sepolia USDC

Release 2.9.14

---

src/App/hooks/useFetchPoolStats.ts
src/ambient-utils/dataLayer/functions/getPoolStats.ts
src/contexts/ExploreContext.tsx

use the current pool price to infer USD token prices when calculating pool stats for 24 hours prior, instead of the pool price 24 hours prior, in order to avoid unexpected volume and fee differences.
1.
2.
1.
2.

fix token price inference for pool stats

---

src/components/Global/PoolCard/PoolCard.tsx
src/components/Home/Landing/TradeNowButton/TradeNowButton.tsx

initiate the navigation on mouse down, rather than on mouse up for the top pools buttons and the Trade Now button on the homepage, in order to prevent accidentally dragging the buttons, instead of clicking.
_Closes #0000_
1.
2.
1.
2.

prevent accidental dragging of buttons on homepage

---

src/index.tsx

prevent the automatic reattempt to switch chains when the modal is open
the user is prompted by their wallet to switch networks even when the modal is open asking for the user to initiate switching networks. this causes the user to get stuck after the user completes this action in their wallet without first initiating from the app.
1.
2.
1.
2.

fix stuck wallet modal after adding network

---

src/pages/platformAmbient/InitPool/InitButton.tsx
src/pages/platformAmbient/InitPool/InitPool.tsx
src/pages/platformAmbient/Trade/Range/Range.tsx

due to a rounding issue, approvals for the exact amount of a token to be minted as a range position might fail when the approval amount is the exact amount estimated. This PR adds 1% to the approval amount for the non-primary token when the user needs to approve that token.
_Closes #0000_
1.
2.
1.
2.

add buffer for mint approvals on plume

---

src/App/hooks/usePoolMetadata.ts
src/components/Trade/TradeTabs/Transactions/Transactions.tsx

…e on tx tab
Disabled code block which merges new found txs with existing list on  `usePoolMetaData` hook which was causing removal from end of `transactionsByPool`
That emoval was changing oldest tx time on transactions.tsx component, once backend services provides refreshed list, transactions.tsx component assuming it got new coming txs so was increasing page count
_Closes #0000_
1.
2.
**Environmental conditions that may result in expected but …

Infinite scroll  | Fix empty tx table issue after opening position

---

src/App/components/PageHeader/ExchangeBalanceDropdown/ExchangeBalanceDropdown.module.css
src/App/components/PageHeader/ExchangeBalanceDropdown/ExchangeBalanceDropdown.tsx
src/components/Portfolio/ExchangeBalance/ExchangeBalance.module.css
src/components/Portfolio/ExchangeBalance/ExchangeBalance.tsx

Fix a visual bug preventing the exchange balance dropdown from expanding vertically to show all content
[ none ]
-   [x] Is this PR ready for merge? (Please convert to a draft PR otherwise)
-   [x] I have performed a self-review of my code.
-   [x] Did I request feedback from a team member prior to the merge?
-   [x] Does my code following the style guide at `docs/CODING-STYLE.md`?
1. Access exchange balance dropdown menu on a desktop device.
2. Open the Withdraw and Transfer tabs in succession.
3. Select option to transfer to a different wallet.
4. Enter a token quantity.
5. Ensure the modal expands to show the disclaimer text below the CTA button.
6. Repeat on the account page to ensure functionality/display is …

exchange balance height bugfix

---

src/utils/hooks/useOnClickOutside.ts

Dismissing the notification center requires two clicks outside the element. This reduces it to one click.
[ none ]
-   [x] Is this PR ready for merge? (Please convert to a draft PR otherwise)
-   [x] I have performed a self-review of my code.
-   [x] Did I request feedback from a team member prior to the merge?
-   [x] Does my code following the style guide at `docs/CODING-STYLE.md`?
The changed file `useOnOutsideClick.tsx` is used in many places throughout the app. I believe I've tracked down and tested all of them to ensure they work as expected.
[ none ]
See testing notes.

change event listener from 'mousedown' to 'click'

---

src/components/Futa/Navbar/Navbar.module.css
src/components/Futa/Navbar/Navbar.tsx
src/components/Global/TutorialOverlay/TutorialOverlayUrlBased.tsx

Replay tutorial btn has been moved into Navbar component to position relatively to other navbar elements
(it was positioning with fixed, left, right rules)
_Closes #0000_
1.
2.
1.
2.

Futa | Fix replay-tutorial btn positioning

---

src/ambient-utils/constants/index.ts
src/components/Futa/Navbar/Navbar.tsx
src/contexts/Futa/FutaHomeContext.tsx
src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaNewLanding.tsx

**Added Conditional Navigation to Auctions on Page Load:**
Implemented a _useEffect_ in the _LandingPage_ component that automatically navigates users to the _/auctions/_ route if the _skipLandingPage_ setting is enabled in the context. This respects user preferences to bypass the landing page while keeping the landing page functional for users who do not have this setting enabled.
**Enabled Intentional Access to Landing Page via Logo Click:**
Updated the navigation flow to allow users to explicitly view the landing page by clicking the site logo in the navbar. Clicking the logo bypasses the _skipLandingPage_ logic, rendering the landing page without altering the _skipLandingPage_ value in local storage. This ensures users can revisit the landing page without impacting their saved …

Update FUTA landing page local storages

---

src/App/App.tsx
src/pages/platformFuta/Home/FutaLandings/FutaLandingNav.module.css
src/pages/platformFuta/Home/FutaLandings/FutaLandingNav.tsx
src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding.module.css
src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding1.tsx

This PR addresses the following frontend issues on the Home Page and implements the requested fixes:
Corrected the font during the initial animation to match the design specifications.
Fixed the background color and CSS to ensure it covers the entire window, eliminating the black bar at the bottom of the screen.
Adjusted the background graphic dots pattern to apply correctly across the entire page. (To be discussed in the product meeting.)
Enlarged the center “/ENTER” button for better visibility and alignment with the design.
Increased the spacing between the smaller “/ENTER” button and the FUTA text in the bottom left corner for improved readability.
Increased the text size of the smaller “/ENTER” button to make it more prominent.
Reduced the thickness of the arrow that transitions to …

Address frontend review home

---

src/components/Swap/SwapTokenInput/SwapTokenInput.tsx

hide the swap impact calculation refresh button until a primary quantity has been input by the user.
1.
2.
1.
2.

hide swap refresh button when no primary quantity

---

src/App/App.css
src/components/Form/Button.module.css
src/components/Form/TokenInputQuantity.module.css
src/components/Form/TokenInputQuantity.tsx
src/components/Form/TokenInputWithWalletBalance.tsx
src/components/Futa/TickerComponent/TickerComponent.tsx
src/components/Global/TooltipComponent/TooltipComponent.module.css
src/components/Global/TooltipComponent/TooltipComponent.tsx
src/components/Swap/SwapExtraInfo/SwapExtraInfo.tsx
src/components/Trade/TradeModules/ExtraInfo/ExtraInfo.tsx
src/components/Trade/TradeModules/TradeModuleHeader.module.css
src/components/Trade/TradeModules/TradeModuleHeader.tsx
src/index.tsx
src/pages/platformAmbient/Trade/TradeCharts/TradeCharts.module.css
src/pages/platformAmbient/Trade/TradeCharts/TradeCharts.tsx
src/pages/platformAmbient/Trade/TradeCharts/TradeChartsComponents/VolumeTVLFee.module.css
src/pages/platformAmbient/Trade/TradeCharts/TradeChartsComponents/VolumeTVLFee.tsx
src/pages/platformAmbient/Trade/TradeCharts/TradeChartsHeader/TradeChartsHeader.tsx
src/pages/platformFuta/Account/Account.tsx
src/pages/platformFuta/Auctions/Auctions.tsx
src/pages/platformFuta/Home/Animations/HexReveal.tsx
src/pages/platformFuta/SwapFuta/SwapFuta.module.css
src/pages/platformFuta/SwapFuta/SwapFuta.tsx
src/styled/Components/Chart.ts
src/styled/Components/TradeModules.ts

Can all the chart buttons have a similar style to the timeframe buttons (background fill, and outline when selected/hovered)
Volume/TVL/Fee Rate
Reset/Auto
Hide Empty/USD/Settings
Remove the chart fullscreen and snapshot buttons entirely
Make the Volume/TVL/Fee Rate/Reset/Auto button text all caps
Remove the header entirely
Order and Comments headings should have the hexreveal wrapper applied like on the auctions page
Add typical button styling to the swap settings button
Add typical button styling to the refresh button in the mockup
Swap info should be all caps
Swap button Should be caps too
Remove the dropdown section and just make the extra info table visible all the time
Move the gas fee into the table like the mockup(extra info)
Remove the token logos

Add swap changes

---

src/contexts/PoolContext.tsx
src/pages/Chart/ChartSettings/ChartSettingsContent.tsx

changed default dollar mod value according to pool

---

src/components/Trade/TradeModules/TradeModuleSkeleton.tsx

The regex for unknown token warnings was using a lookbehind and that was crashing old versions of Safari. This PR rewrites that regex to not use that feature while retaining the same behavior.
_Closes #0000_
1. In Safari on iOS 15.5 open an existing pool with a token that's not in any of the token lists (for example [this one](https://blast.ambient.finance/trade/market/chain=0x13e31&tokenA=0x0000000000000000000000000000000000000000&tokenB=0x5f59ecf360f194 …

Remove lookbehind from a regex for outdated Safari versions

---

src/components/Futa/Comments/CommentCard/CommentCard.module.css
src/components/Futa/Comments/Comments.module.css
src/components/Futa/Comments/Comments.tsx

Comments wrapper section padding changed with global padding rules
Bottom alignment fixed to make it parallel with left section
Scroll back offsets has been changed to adapt new padding rules (auto scroll after fetching old messages)
_Closes #0000_
1.
2.
1.
2.

Futa Comments | Comments component styling fix for global rules

---

src/App/hooks/useDrawSettings.ts
src/contexts/ChartContext.tsx
src/pages/Chart/ChartSettings/ChartSettingsContent.tsx

fix crash when dismissing chart setting modal for users with previously saved chart settings before the addition of separate overlay colors.
_Closes #0000_
1.
2.
1.
2.

Chart theme colors bugfix

---

src/components/Trade/InfiniteScroll/useMergeWithPendingTxs.tsx
src/contexts/GraphDataContext.tsx
src/contexts/ReceiptContext.tsx

Created alternate list to keep pendings for infinite scroll component in `ReceiptContext` (named: `transactionsByTypeIfs`)
GraphDataContext has been modified to trigger with that alternate list changes.
Clear method added for that new alternate list and called in useMergeWithPendingTxs hook.
_Closes #0000_
1.
2.
1.
2.

Infinite Scroll | Remove pendings from context after related data has been indexed

---

src/utils/numbers.ts

Fix a bug with number string to BigInt conversion where exponential normalization changed the value of the number due to float precision errors, which breaks the behavior of the Max button. For example, without this fix `stringToBigInt("0.100000000000000056", 18)` returns `100000000000000061`.
_Closes #0000_
1. Press "Max" on some the input for some token with 18 decimals. It's not hard to find examples, currently I have one in my wallet - ETH on Monad. …

Fix small errors in string to BigInt conversion

---

src/App/hooks/usePoolMetadata.ts
src/ambient-utils/api/fetchPoolLiquidity.ts
src/components/Global/DetailModals/TransactionDetailsGraph/TransactionDetailsLiquidityGraph.tsx
src/components/Global/Sidebar/FavoritePools.tsx
src/components/Global/Sidebar/RecentPools.tsx

- only trigger the fetch when pool liquidity changes by > 1%
- bypass downloading new data when pool price changes and only re-process
a couple issues with the current logic that would be resulting in excessive calls to /pool_liq_curve:
- we request new liq. curve data every time the total liquidity of the positions shown in the table changes
this is useful for low liquidity pools, but not as useful for high liquidity pools
- we request new liq. curve data every time the pool price changes
this isn’t helpful at all…but we’d need to separate the processing of liq. data from the downloading of liq. data in fetchPoolLiquidity.ts to only re-process when pool price changes
-   [ ] I have performed a self-review of my …

reduce redundant liquidity curve requests

---

src/components/Trade/InfiniteScroll/InfiniteScroll.tsx
src/components/Trade/InfiniteScroll/TableRowsInfiniteScroll.tsx
src/components/Trade/TradeTabs/TableRows.tsx

Ref used in InfiniteScroll addMoreData method to check if fix monad issue
LastRowRef assignment has been changed for last changes
_Closes #0000_
1.
2.
1.
2.

Change LastRowRef on TableRows according to new client side filtering

---

src/components/Trade/TradeModules/TradeConfirmationSkeleton.tsx

trim the end of estimated swap input / output quantity displays to a maximum length based on the length of the token symbol.
1.
2.
1.
2.

prevent swap confirmation display overflow

---

src/ambient-utils/constants/networks/plumeLegacy.ts
src/ambient-utils/types/NetworkIF.ts
src/components/Trade/InfiniteScroll/useGenFakeTableRow.tsx
src/components/Trade/InfiniteScroll/useMergeWithPendingTxs.tsx

These changes targets to remove placeholder row if synthetic row match missed on first try.
Also defining timeout per network can be used with assigning `indexerTimeout` prop on `NetworkIF` (which is optional)
_Closes #0000_
1.
2.
1.
2.

Remove placeholder if second try needed

---

package.json
src/components/Global/Explore/PoolRow/PoolRow.tsx

added logic to preserve the input/output token if the user is switching pools by clicking a Top Pool on /explore that shares a token with the previously selected pool.
e.g. user is trying to buy 100 USDC and switches between USDT/USDC and DAI/USDC by clicking DAI/USDC on explore page
in the above example, the user would then have to manually reverse the trade order and retype 100 for USDC as the fixed output.
1.
2.
**Environmental conditions that may …

Preserve trade order navigating from top pools

---

src/components/Chat/MessagePanel/InputBox/MessageInput.module.css
src/components/Chat/MessagePanel/InputBox/MessageInput.tsx

Updated MessageInput.tsx and MessageInput.module.css file to solve send Message button stays highlighted on ios
_Closes #0000_
1.
2.
1.
2.

Senmessage button stays highlighted

---

src/components/Swap/SwapTokenInput/SwapTokenInput.tsx

Currently the frontend keeps spinning even after the `calcImpact` call reverted, which should [typically only happen in low liquidity situations](https://github.com/CrocSwap/ambient-ts-app/blob/1c915aac27ff97cbd1f7ed58879567e9a40f5236/src/App/functions/calcImpact.ts#L18-L19). This PR makes the fronted stop the loading spinner and show the insufficient liquidity error.
_Closes #0000_
-   [X] Did I request feedback from a team member prior to the merge?
1. Estimating a swap that reverts, for example by asking for swap output …

Fix endless loading when swap impact call fails

---

package.json
src/ambient-utils/constants/networks/baseSepolia.ts
src/ambient-utils/constants/networks/blastMainnet.ts
src/ambient-utils/constants/networks/blastSepolia.ts
src/ambient-utils/constants/networks/ethereumMainnet.ts
src/ambient-utils/constants/networks/ethereumSepolia.ts
src/ambient-utils/constants/networks/monadTestnet.ts
src/ambient-utils/constants/networks/plumeLegacy.ts
src/ambient-utils/constants/networks/plumeMainnet.ts
src/ambient-utils/constants/networks/scrollMainnet.ts
src/ambient-utils/constants/networks/scrollSepolia.ts
src/ambient-utils/constants/networks/swellMainnet.ts
src/ambient-utils/constants/networks/swellSepolia.ts
src/ambient-utils/dataLayer/functions/chains.ts
src/components/Global/DetailModals/RangeDetails/RangeDetailsSimplify/RangeDetailsSimplify.tsx
src/components/Global/NotificationCenter/ReceiptDisplay/ReceiptDisplay.tsx
src/components/Trade/TableInfo/FeaturedBox.tsx
src/components/Trade/TradeModules/SubmitTransaction/TransactionSubmitted/TransactionSubmitted.tsx
src/contexts/CrocEnvContext.tsx
src/contexts/SidebarContext.tsx
src/utils/hooks/useProcessOrder.ts
src/utils/hooks/useProcessRange.ts
src/utils/hooks/useProcessTransaction.ts

Remove dependency on the crocswap SDK for looking up the block explorer address on a particular chain. 
This will allow easier front-end updates in case the block explorer address changes.
(This PR also switches to using the primary RPC for chain stat generation and ENS lookups)
_Closes #0000_
1.
2.
1.
2.

remove SDK dependency for block explorer lookup

---

src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx
src/pages/platformAmbient/Trade/Swap/Swap.tsx

- fixes bug causing price change warning to appear when the user is buying the base token and the price of the base token decreases
- uses the existing price impact data to determine if the price has changed since the confirmation modal was opened instead of making separate price queries
The initial price of ETH when this swap confirmation modal was opened was 2478.1663733329506, so the warning should not be showing.
1.
2.
**Environmental conditions that …

fix logic for displaying price change warnings in swap confirmation

---

src/ambient-utils/api/fetchCandleSeries.ts
src/ambient-utils/types/candleData/CandleDataIF.ts
src/pages/Chart/ChartUtils/discontinuityScaleUtils.ts

Previously, TVL was calculated only using current USD multipliers, which caused misleading changes in TVL even when the underlying token amounts didn’t change. This PR introduces a raw TVL value based on actual token amounts.
Condensed mode and comparison logic now use tvlRaw for stable results.
Using current prices caused artificial TVL fluctuations in historical data. 
**Because we take candles at 1 minute intervals, so the first 200 candles use the dollar equivalent of the different base Price and quote Price when calculating the tvl** 
1. Open this pool on Plume /trade/market/chain=0x18232&tokenA=0xca59ca09e5602fae8b629dee83ffa819741f14be&tokenB=0xda6087e69c51e7d31b6dbad276a3c44703dfdcad
2. wait 1 minute
3. click …

fixed: condensed mode tvl changes comparison

---

package.json

- temporarily disable MEV protection on Monad Testnet during upgrade

Release 3.7.6

---

package.json
src/ambient-utils/constants/blacklist.ts

blocking the following tokens from appearing on the front-end:
https://explorer.plume.org/token/0xAeDd65F2168ecC1f8aBC609f0D09CA364fe7DcDC (WPLUME - 2 holders)
https://explorer.plume.org/token/0x81e68577ad6a499b422f52908fa88b1f0769e9b5 (PLC - 4 holders)
https://explorer.plume.org/token/0x9786198803ba261d4c06344e6698b76e2db6ad1c (PLC - 7 holders)
https://explorer.plume.org/token/0xf07f47f3c160c2f3b2190fc81be38a61337250d6 (aUSD - 2 holders)

Block fake plume tokens sep 29
