CrocSwap/ambient-ts-app

- package.json
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
- fixed wallet dropdown avatar jazzicon fallback
> Release 2.6.13

- src/components/Futa/Comments/CommentInput/CommentInput.module.css
- src/components/Futa/Comments/CommentInput/CommentInput.tsx
- src/components/Futa/Comments/Comments.module.css
- src/components/Futa/Comments/Comments.tsx
- Added button for not connected state on futa chat
- Mobile css for comments panel
- Not showing fetch prev messages button once it fetched all messages
- Text info for fetched all messages state
_Closes #0000_
1.
2.
1.
2.
> Adding button for not connected state

- src/components/Futa/Chart/ScatterChart/ScatterChart.tsx
- src/components/Futa/Chart/ScatterChart/Xaxis.tsx
- src/components/Futa/Chart/ScatterChart/Yaxis.tsx
- fixed: horizontal flickering issue when resize scatter chart
- buffer enlarged for left side
- afterOneWeek condinations fixed
> Fix scatter chart bugs

- src/App/App.tsx
- src/components/Trade/TradeTabs/NoTableData/NoTableData.tsx
- src/components/Trade/TradeTabs/Orders/Orders.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
- src/pages/Portfolio/Portfolio.tsx
Add link to portfolio when user has liquidity in other pools on the same chain, but not in current pool.
Same for limits
_Closes #0000_
1.
2.
1.
2.
> add links to specific portfolio tabs  from /trade table

- package.json
- public/scroll-badge/1.json
- public/scroll-badge/2.json
- public/scroll-badge/3.json
- public/scroll-badge/4.json
- src/App/App.tsx
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/components/Chat/ChatRenderUtils.tsx
- src/components/Portfolio/PortfolioBanner/PortfolioBannerAccount/PortfolioBannerAccount.tsx
- src/components/Trade/TradeTabs/NoTableData/NoTableData.tsx
- src/components/Trade/TradeTabs/Orders/Orders.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
- src/pages/Portfolio/Portfolio.tsx
- yarn.lock
> Update plume from develop july 17

- src/components/Trade/TradeTabs/Orders/Orders.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
> fix no tx found message on lookup account view

- package.json
- src/components/Chat/ChatRenderUtils.tsx
- src/components/Portfolio/PortfolioBanner/PortfolioBannerAccount/PortfolioBannerAccount.tsx
notable change:
- fixed no data available message for lookup user portfolio when wallet is connected
> Release 2.6.16

- src/ambient-utils/constants/index.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/contexts/ChainDataContext.tsx
- src/contexts/CrocEnvContext.tsx
- src/contexts/TradeTokenContext.tsx
replace infura key for mainnet
need to follow up to fix ETH-Sepolia
_Closes #0000_
1.
2.
1.
2.
> replace infura key for mainnet

- src/components/Futa/Chart/ScatterChart/ScatterChart.tsx
- src/components/Futa/Chart/ScatterChart/Yaxis.tsx
- src/pages/platformAmbient/Chart/ChartUtils/chartUtils.ts
> Scatter chart y axis domain calculate according to filtered auctions data

- src/components/Futa/TickerComponent/TickerComponent.module.css
- src/components/Futa/TickerComponent/TickerComponent.tsx
> make ticker header static

- src/ambient-utils/constants/index.ts
- src/ambient-utils/constants/networks/ethereumSepolia.ts
- src/contexts/ChainDataContext.tsx
- src/contexts/CrocEnvContext.tsx
> fix sepolia rpc endpoint

- src/styled/Components/Portfolio.ts
Fix hidden text on transfer address inputs
_Closes #0000_
1.
2.
1.
2.
> Fix color input

- src/components/Futa/Chart/ScatterChart/ScatterChart.tsx
> removed auction unselect ability in scatter chart

- package.json
- src/components/Chat/ChatConstants/ChatEndpoints.ts
- src/components/Chat/ChatEnums.ts
- src/components/Chat/ChatPanel.tsx
- src/components/Chat/Service/ChatApi.tsx
- src/components/Chat/Service/useChatSocket.tsx
Verification from metamask moved into ChatApi hook as a service method for calling from different components like NftBannerAccount etc..
REST service calls which related with verification moved also ChatApi
IsVerified state variable moved into ChatPanel component
Toastr text for verifying messages and wallet is changed into `"Your wallet and messages verified!"`
_Closes #0000_
1.
2.
1.
2.
> Moving wallet verification into ChatApi hook

- src/components/Trade/TradeTabs/NoTableData/NoTableData.tsx
- src/components/Trade/TradeTabs/Orders/Orders.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
> improve prompts to view user data when no pool data available

- src/pages/Chart/Axes/xAxis/XaxisCanvas.tsx
- src/pages/Chart/Axes/yAxis/YaxisCanvas.tsx
- src/pages/Chart/Chart.css
- src/pages/Chart/Chart.tsx
- src/pages/Chart/FeeRate/FeeRateChart.tsx
- src/pages/Chart/Tvl/TvlChart.tsx
- src/pages/Trade/TradeCharts/TradeCharts.tsx
> fixed disappears triangles on Limit and Pool

- src/components/Trade/TradeTabs/Orders/Orders.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
- src/contexts/GraphDataContext.tsx
calculation of the number of a user's active limit orders in other pools now included claimable limit orders
1.
2.
1.
2.
> fix calculation of activeUserLimitOrdersLength

- src/pages/Chart/Axes/xAxis/XaxisCanvas.tsx
- src/pages/Chart/Axes/yAxis/YaxisCanvas.tsx
- src/pages/Chart/Chart.css
- src/pages/Chart/Chart.tsx
- src/pages/Chart/FeeRate/FeeRateChart.tsx
- src/pages/Chart/Tvl/TvlChart.tsx
- src/pages/Trade/TradeCharts/TradeCharts.tsx
Reverts CrocSwap/ambient-ts-app#3925
> Revert "fixed disappears triangles on Limit and Pool"

- src/components/Form/TokenInputQuantity.tsx
- src/components/Form/TokenInputWithWalletBalance.tsx
- src/components/Global/Tabs/TableMenu/TableMenuComponents/TransactionsMenu.tsx
- src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
- src/pages/Trade/Swap/Swap.tsx
https://github.com/user-attachments/assets/96e815c9-75b6-48e6-a03e-e62e7106b8a8
1.
2.
1.
2.
> fix swap reversal on token selection

- src/App/functions/urlSlugs.ts
- src/components/Trade/TradeTabs/Orders/orderRowConstants.tsx
- src/components/Trade/TradeTabs/Ranges/rangeRowConstants.tsx
- src/components/Trade/TradeTabs/Transactions/txRowConstants.tsx
> fix token pair links on account

- src/components/Global/Explore/TableHead.tsx
- src/components/Global/Explore/TopPools.tsx
- src/components/Trade/TableInfo/DetailedBox.tsx
- src/components/Trade/TableInfo/TableInfo.styles.ts
- src/components/Trade/TableInfo/TableInfo.tsx
ADD TOOLTIP TO TOP POOL HEADERS
_Closes #0000_
1.
2.
1.
2.
> add tooltip to explore headers

- src/App/hooks/useFetchPoolStats.ts
- src/ambient-utils/types/pool/PoolStatIF.ts
- src/components/Global/Explore/DexTokens.tsx
- src/components/Global/Explore/PoolRow.tsx
- src/components/Global/Explore/TableHead.tsx
- src/components/Global/Explore/TableHeadTokens.tsx
- src/components/Global/Explore/TopPools.tsx
- src/components/Global/Explore/useSortedPools.ts
- src/components/Global/TooltipComponent/TooltipComponent.tsx
- src/components/Trade/TableInfo/DetailedBox.tsx
- src/components/Trade/TableInfo/TableInfo.tsx
- src/contexts/ExploreContext.tsx
added 24h APR to Top Pools on /explore and Pool Info (along with 24h Fees in Pool Info):
_Closes #0000_
1.
2.
1.
2.
> add 24h Fees and APR to pool info

- src/assets/branding/ambientProductionBrandAssets.ts
- src/assets/branding/ambientTestnetBrandAssets.ts
- src/assets/branding/blastBrandAssets.ts
- src/assets/branding/defaultBrandAssets.ts
- src/assets/branding/futaBrandAssets.ts
- src/assets/branding/scrollBrandAssets.ts
- src/components/Home/Landing/MobileLandingSections.tsx
disable points CTAs (homepage & trade banner) for all environments
note: the content is still in place in case it should be re-enabled or modified to suit another purpose
> disable points CTAs

- src/components/Trade/TradeTabs/NoTableData/NoTableData.module.css
- src/components/Trade/TradeTabs/PositionsOnlyToggle/PositionsOnlyToggle.tsx
- src/pages/Chart/Chart.css
- src/pages/Explore/Explore.tsx
- src/pages/Trade/TradeCharts/TradeCharts.module.css
- src/pages/Trade/TradeCharts/TradeChartsComponents/CurveDepth.module.css
- src/pages/Trade/TradeCharts/TradeChartsComponents/CurveDepth.tsx
- src/pages/Trade/TradeCharts/TradeChartsComponents/OrderHistoryDisplay.tsx
- src/pages/Trade/TradeCharts/TradeChartsComponents/TimeFrame.module.css
- src/pages/Trade/TradeCharts/TradeChartsComponents/TimeFrame.tsx
- src/pages/Trade/TradeCharts/TradeChartsComponents/TradeChartsTokenInfo.tsx
- src/pages/Trade/TradeCharts/TradeChartsComponents/VolumeTVLFee.module.css
- src/pages/Trade/TradeCharts/TradeChartsComponents/VolumeTVLFee.tsx
- src/styled/Components/Trade.ts
> Fix chart header mobile

- src/pages/Chart/Chart.tsx
> bug fixed : chart disappear

- src/pages/Trade/Trade.tsx
- src/pages/Trade/TradeCharts/TradeChartsHeader/TradeChartsHeader.tsx
> update chart header on mobile

- src/App/App.tsx
- src/App/hooks/useAppChain.ts
- src/components/Global/TabComponent/TabComponent.tsx
- src/components/Global/Tabs/TableMenu/TableMenuComponents/OrdersMenu.tsx
- src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx
- src/components/Portfolio/PortfolioTabs/PortfolioTabs.tsx
- src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx
- src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx
- src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx
- src/utils/hooks/useLinkGen.ts
add support for links like https://ambient.finance/benwolski.eth/liquidity
_Closes #0000_
1.
2.
1.
2.
> support tab specific links to lookup account portfolios

- src/components/Trade/TradeModules/TradeModuleSkeleton.tsx
- src/styled/Components/TradeModules.ts
add Looking to LP? link 
_Closes #0000_
1.
2.
1.
2.
> Add link to pool module

- src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx
- src/App/components/PageHeader/PageHeader.tsx
- src/App/hooks/useAppChain.ts
- src/components/Global/TabComponent/TabComponent.tsx
- src/pages/Home/Home.tsx
fix links like https://ambient.finance/?network=blast when wallet is not connected
test links:
https://deploy-preview-3968--dev-ambi.netlify.app/0xE09de95d2A8A73aA4bFa6f118Cd1dcb3c64910Dc/liquidity/?network=blast
https://deploy-preview-3968--dev-ambi.netlify.app/wolsk.eth/liquidity/?network=scroll
_Closes #0000_
1.
2.
1.
2.
> fix network switching by search param when not connected

- src/App/components/PageHeader/PageHeader.tsx
add logic to navigate to the relevant URL when a user clicks the Account button after viewing their limits or liquidity, e.g. /account/liquidity
_Closes #0000_
1.
2.
1.
2.
> open relevant portfolio tab when user clicks Account in page header

- src/assets/branding/ambientProductionBrandAssets.ts
- src/assets/branding/defaultBrandAssets.ts
set Scroll mainnet as the default network to help with Binance Web3 Wallet issues
_Closes #0000_
1.
2.
1.
2.
> set Scroll as default network

- src/App/hooks/useTokens.ts
- src/ambient-utils/dataLayer/functions/index.ts
- src/ambient-utils/dataLayer/functions/serializeBigInt.ts
- src/components/Global/TokenIcon/processLogoSrc.ts
fix bug attempting to save token acknowledgement for token with bignumber as totalSupply
_Closes #0000_
1.
2.
1.
2.
> fix token acknowledgement bug

- src/components/Futa/Comments/CommentInput/CommentInput.tsx
> circular progress bar bug has solved

- src/App/components/PageHeader/Account/Account.tsx
- src/App/components/PageHeader/PageHeader.tsx
- src/styled/Components/Header.ts
> Reorganize header items on Ambient

- src/components/Futa/Comments/CommentCard/CommentCard.tsx
> Day separator futa

- src/App/components/PageHeader/PageHeader.tsx
- src/App/hooks/useAppChain.ts
- src/ambient-utils/dataLayer/functions/regex/checkEoaHexAddress.ts
- src/ambient-utils/dataLayer/functions/regex/index.ts
add support for page titles like 'My Liquidity'
_Closes #0000_
1.
2.
1.
2.
> fix portfolio page titles

- src/App/App.css
- src/components/Global/DropdownSearch/DropdownSearch.module.css
- src/components/Global/DropdownSearch/DropdownSearch.tsx
- src/components/Trade/TableInfo/TableInfo.tsx
- src/components/Trade/TradeTabs/Orders/Orders.tsx
- src/components/Trade/TradeTabs/Ranges/Leaderboard.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
Reverts CrocSwap/ambient-ts-app#3964
> Revert "add and update scrollbars for transaction tables"

- src/App/App.tsx
- src/App/components/PageHeader/PageHeader.tsx
- src/components/Global/TabComponent/TabComponent.tsx
- src/pages/Portfolio/Portfolio.tsx
add URLs to open balances tabs on portfolio and relevant page titles
_Closes #0000_
1.
2.
1.
2.
> add url slugs for balances tabs on portfolio

- src/components/Futa/Comments/Comments.module.css
- src/components/Futa/Comments/Comments.tsx
- src/pages/platformFuta/SwapFuta/SwapFuta.tsx
- Comments component adapted for mobile on swap page.
- Comments component Mobile CSS rules extended for Auctios/SwapPage cases
- Scroll bar problem fixed for auctions page
- Connection status disabled for mobile
_Closes #0000_
1.
2.
1.
2.
> Futa Swap | Comments component for mobile

- src/pages/Chart/Chart.tsx
- src/pages/Chart/Draw/DrawCanvas/DragCanvas.tsx
- src/pages/Chart/Draw/DrawCanvas/DrawCanvas.tsx
- src/pages/Chart/Draw/FloatingToolbar/FloatingToolbarSettings.tsx
- src/pages/Chart/Draw/FloatingToolbar/FloatingToolbarSettingsCss.ts
_Closes #0000_
[snap algorithm for condenced mode is changed](https://github.com/CrocSwap/ambient-ts-app/commit/cc3e2615794bea189903450621a0407b452d4350)
[dp range tooltip plament fix](https://github.com/CrocSwap/ambient-ts-app/commit/f2ca6b9879fd01867b181bdfa758fd061040a164)
Fib retracement settings page alignment 
1.
2.
1.
2.
> Ambient draw bug fix

- public/ambient-token-list.json
- src/ambient-utils/constants/ambient-token-list.json
- src/ambient-utils/constants/defaultTokens.ts
- src/ambient-utils/dataLayer/functions/getMoneynessRank.ts
- src/ambient-utils/dataLayer/functions/stablePairs.ts
- src/components/Form/RangeWidth/RangeWidth.tsx
- src/components/Global/PoolCard/PoolCard.tsx
- src/contexts/PoolContext.tsx
- src/contexts/TradeDataContext.tsx
added SolvBTC.b token on Scroll
https://scrollscan.com/token/0x3ba89d490ab1c0c9cc2313385b30710e838370a4
https://www.coingecko.com/en/coins/solv-protocol-solvbtc
_Closes #0000_
1.
2.
1.
2.
> add SolvBTC.b token on Scroll

- src/components/Global/Explore/PoolRow.tsx
- src/components/Global/Explore/TopPools.tsx
- src/components/Portfolio/PortfolioBanner/PortfolioBanner.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx
- src/components/Trade/TradeTabs/TradeTabs2.tsx
- src/styled/Components/Portfolio.ts
- src/styled/Components/TransactionTable.ts
overlapping numbers make the portfolio difficult to read
1.
2.
1.
2.
> Fix portfolio display aug 10

- src/pages/Chart/Chart.tsx
- src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
- src/pages/Trade/TradeCharts/TradeCharts.tsx
- src/pages/Trade/TradeCharts/TradeChartsHeader/TradeChartsHeader.tsx
- fixed: color of the pool details section appears different in the screenshot
- fixed: loss of tooltip of selected candle when re render chart
1.
2.
1.
2.
> Proven - bug fixes

- src/pages/platformFuta/SwapFuta/SwapFuta.tsx
Border added into swap comments
_Closes #0000_
1.
2.
1.
2.
> Border added into swap comments

- src/App/hooks/useSimulatedIsUserConnected.ts
change logic for determining if the page is still loading the user's wallet connection
"Please Connect Your Wallet" would flash when loading the page or switching networks.
https://github.com/user-attachments/assets/6fb6b2ee-c5cf-4efb-ac78-7c74fd246fc9
This must have started after implementing Web3Modal or upgrading to a new version.
1.
2.
1.
2.
> fix connection simulation on page load

- src/pages/Chart/Chart.tsx
- src/pages/Chart/Draw/Toolbar/Toolbar.tsx
> toolbar tooltip is disabled for mobile

- src/ambient-utils/constants/index.ts
- src/pages/Trade/Limit/Limit.tsx
in case of a TF error for a limit order, catch the error and try one tick closer to the current pool price
_Closes #0000_
1.
2.
1.
2.
> add limit error workaround

- src/ambient-utils/dataLayer/transactions/limit.ts
- src/pages/Trade/Limit/Limit.tsx
> add tertiary limit tx backup moving price away from pool price

- .husky/pre-commit
- package.json
- src/components/Form/TokenInputQuantity.tsx
- src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
- src/pages/Trade/Swap/Swap.tsx
- yarn.lock
swap confirm button gets stuck when deleting input longer than two characters
1.
2.
1.
2.
> Fix swap token input bugs

- src/components/Global/TransactionDetails/TransactionDetailsHeader/TransactionDetailsHeader.module.css
- src/components/Global/TransactionDetails/TransactionDetailsHeader/TransactionDetailsHeader.tsx
> transaction details card closing button for mobile

- src/App/hooks/usePoolMetadata.ts
- src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
refetch pool liquidity when pool positions and limit orders change
_Closes #0000_
1.
2.
1.
2.
> refetch pool liquidity when receipt received

- src/contexts/ChainDataContext.tsx
token balances in the token selector and wallet dropdown weren't updating when a transaction was initiated from the account page. now the balances will be updated every time a receipt is received.
_Closes #0000_
1.
2.
1.
2.
> update token balances on new receipt

- src/components/Global/Account/AccountTabs/Points/Points.module.css
- src/components/Global/Account/AccountTabs/Points/Points.tsx
- src/components/Global/Account/AccountTabs/Points/PointsRow.tsx
- src/components/Portfolio/PortfolioBanner/PortfolioBanner.tsx
- src/components/Portfolio/PortfolioBanner/PortfolioBannerAccount/PortfolioBannerAccount.tsx
- src/components/Portfolio/PortfolioTabs/PortfolioTabs.tsx
- src/css/GlobalCssClassnames.css
- src/pages/Portfolio/Portfolio.tsx
- src/styled/Components/Portfolio.ts
FIX PORTFOLIO LAYOUT ISSUES ON MOBILE
| **Before** | **After** |
|------------|-----------|
| <img width="398" alt="image" src="https://github.com/user-attachments/assets/6332ae56-d0b4-4c37-a6d8-f49c768a686a"> | <img width="391" alt="image" src="https://github.com/user-attachments/assets/54744137-c52a-418e-a461-7073212f4a15"> |
| <img width="396" alt="image" src="https://github.com/user-attachments/assets/80bae18b-d411-4274-9c6f-f8a67e7a5ed6"> | <img width="388" alt="image" src="https://github.com/user-attachments/assets/98cc78c8-eb57-4da2-b8c5-423e81542bcf"> |
| <img width="391" alt="image" src="https://github.com/user-attachments/assets/d2b65610-9719-4441-93af-7fbe1b6110e1"> | <img width="395" alt="image" …
> Fix portfolio layout issues on mobile devices

- package.json
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- fixed missing toggle to Hide Empty Positions on /account on desktop
> Release 2.7.10

- src/App/hooks/useTokenBalancesAndAllowances.ts
- src/pages/InitPool/InitPool.tsx
removed instance of usePoolMetadata hook that wasn't doing anything
_Closes #0000_
1.
2.
1.
2.
> remove extra instance of usePoolMetadata hook

- src/components/Chat/FullChat/FullChat.module.css
vh units converted into svh on fullchat.module.css file
_Closes #0000_
1.
2.
1.
2.
> vh to svh conversion on fullchat css module file

- src/components/Trade/TradeTabs/TableRows.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
- src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx
> add automatic shifting when first/last rows visible

- src/components/Global/Account/AccountTabs/Exchange/Exchange.tsx
- src/components/Global/Account/AccountTabs/Exchange/ExchangeCard.module.css
- src/components/Global/Account/AccountTabs/Exchange/ExchangeCard.tsx
- src/components/Global/Account/AccountTabs/Exchange/ExchangeHeader.module.css
- src/components/Global/Account/AccountTabs/Wallet/Wallet.tsx
- src/components/Global/Account/AccountTabs/Wallet/WalletCard.module.css
- src/components/Global/Account/AccountTabs/Wallet/WalletCard.tsx
- src/components/Global/Account/AccountTabs/Wallet/WalletHeader.module.css
remove token name on mobile and apportion more space to the Amount column
1.
2.
1.
2.
> fix overlap of content in wallet & exchange balance rows on portfolio

- src/ambient-utils/constants/index.ts
- src/pages/Trade/Swap/Swap.tsx
> add flag to enable l1 gas estimates

- src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
> Liq pool changes

- src/components/Chat/MessagePanel/Room/Room.tsx
- src/contexts/CrocEnvContext.tsx
- src/contexts/GlobalContexts.tsx
- src/contexts/TokenBalanceContext.tsx
- src/contexts/TokenContext.tsx
- src/contexts/TradeDataContext.tsx
> consolidate useTokens hooks

- src/App/components/Sidebar/Sidebar.tsx
- src/App/components/Sidebar/SidebarSearchResults/PoolsSearchResults/PoolSearchResult.tsx
- src/App/components/Sidebar/SidebarSearchResults/PoolsSearchResults/PoolsSearchResults.tsx
- src/App/components/Sidebar/SidebarSearchResults/SidebarSearchResults.tsx
- src/App/hooks/useFetchPoolStats.ts
- src/App/hooks/usePoolMetadata.ts
- src/ambient-utils/api/fetchContractDetails.ts
- src/ambient-utils/api/fetchPoolLiquidity.ts
- src/ambient-utils/api/fetchTokenBalances.ts
- src/ambient-utils/constants/defaultTokens.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/dataLayer/functions/getPoolStats.ts
- src/components/Global/DropdownSearch/DropdownSearch.tsx
- src/components/Global/PoolCard/PoolCard.tsx
- src/components/Global/RangeBounds/RangeBounds.tsx
- src/components/Global/Sidebar/FavoritePools.tsx
- src/components/Global/Sidebar/PoolsListItem.tsx
- src/components/Global/Sidebar/RecentPools.tsx
- src/components/Global/Sidebar/TopPools.tsx
- src/components/Home/Stats/AmbientStats.tsx
- src/components/Home/TopPools/TopPools.tsx
- src/components/Trade/Range/RangePriceInfo/RangePriceInfo.tsx
- src/contexts/ChainDataContext.tsx
- src/contexts/PoolContext.tsx
- src/pages/Trade/Range/Range.tsx
reduce RPC calls by removing unnecessary calls and running calls concurrently, instead of sequentially, when possible.
_Closes #0000_
1.
2.
1.
2.
> prevent unnecessary RPC calls

- src/components/Global/ContentContainer/ContentContainer.module.css
- src/pages/Trade/Trade.tsx
> make trade outlet scrollable on mobile

- package.json
- src/ambient-utils/dataLayer/functions/querySpotPrice.ts
- src/components/Home/Stats/AmbientStats.tsx
temporary fix for apparent decimalization bug:
> temportary fix for dex stats by reducing tokens aggregated on scroll

- src/components/Chat/MessagePanel/Room/Room.module.css
- src/components/Chat/MessagePanel/Room/Room.tsx
Add room css to Room.css and Room.tsx
_Closes #0000_
1.
2.
1.
2.
> Add room css to Room.css and Room.tsx

- netlify.toml
- src/components/Home/Landing/BackgroundImages.module.css
- vite.config.ts
instruct browsers to cache assets for 1 year
_Closes #0000_
1.
2.
1.
2.
> add browser caching for assets

- src/ambient-utils/api/fetchDepositBalances.ts
- src/ambient-utils/api/fetchTokenBalances.ts
- src/contexts/CachedDataContext.tsx
- src/contexts/ChainDataContext.tsx
- src/contexts/TokenBalanceContext.tsx
- src/pages/Portfolio/Portfolio.tsx
> refactor balances queries to not cache token list

- package.json
- src/index.tsx
- yarn.lock
add Metamask, Binance web 3 wallet, and trust wallet as featured wallets
_Closes #0000_
1.
2.
1.
2.
> add featured wallets

- src/pages/Chart/Chart.tsx
> Liq buffer for xaxis

- src/pages/Chart/Chart.tsx
- src/pages/Chart/ChartTooltip/ChartTooltip.tsx
- src/pages/Chart/ChartTooltip/ChartTooltipStyles.ts
- src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
- src/pages/Trade/TradeCharts/TradeCharts.module.css
- src/pages/Trade/TradeCharts/TradeCharts.tsx
> Moved chart tooltip next to toolbar

- src/components/Trade/TradeTabs/useSortedLimits.ts
- src/components/Trade/TradeTabs/useSortedPositions.ts
- src/components/Trade/TradeTabs/useSortedTxs.ts
- src/pages/Trade/Range/Range.tsx
- src/utils/hooks/useProcessOrder.ts
> test removal of hashing of table data

- src/ambient-utils/dataLayer/functions/getObjectSize.ts
- src/ambient-utils/dataLayer/functions/index.ts
- src/contexts/CandleContext.tsx
- src/pages/Trade/TradeCharts/TradeCandleStickChart.tsx
> potential chart efficiency improvements

- src/components/Trade/TradeTabs/useSortedLimits.ts
- src/components/Trade/TradeTabs/useSortedPositions.ts
- src/components/Trade/TradeTabs/useSortedTxs.ts
> update row sorting dependencies

- src/pages/Chart/ChartTooltip/ChartTooltip.tsx
- for small devices chart tooltip information displayed in 3 lines
- fixed chart tooltip sometimes display just pool/period section
_Closes #0000_
1.
2.
1.
2.
> Chart tooltip issues

- src/ambient-utils/dataLayer/functions/memoizePromiseFn.ts
> add interval to clear query cache

- src/pages/Chart/Tvl/TvlChart.tsx
> hotfix - TVL chart crash on solvBTC

- package.json
- fixed USD value calculation displayed on default view of range details modal to include rewards value
> Release 2.8.7

- src/pages/Trade/Reposition/Reposition.tsx
move early return below all hooks in reposition module
1.
2.
1.
2.
> fix crash on page refresh when reposition module active

- src/App/hooks/useFetchPoolStats.ts
> fix pool price change display after pool switch

- package.json
- src/App/hooks/useFetchPoolStats.ts
- src/contexts/ExploreContext.tsx
- src/contexts/PoolContext.tsx
- src/pages/Trade/Reposition/Reposition.tsx
- src/pages/Trade/TradeCharts/TradeChartsComponents/TradeChartsTokenInfo.tsx
- fixed issues causing intermittent display of incorrect 24h pool price change %
- fixed inversion of 24h pool price change % when pool price inverted
> Release 2.8.9

- src/ambient-utils/dataLayer/functions/getPositionData.ts
make on-chain liquidity query when liquidity value is zero, but rewards value is non-zero
1.
2.
1.
2.
> fix missing liq. position liquidity display

- package.json
- src/ambient-utils/dataLayer/functions/getPositionData.ts
- fix edge case of missing liquidity position display
> Release 2.8.10

- src/App/App.tsx
- src/components/Global/ContentContainer/ContentContainer.module.css
- src/components/Global/Modal/Modal.module.css
- src/components/Home/Landing/BackgroundImages.module.css
- src/pages/common/FAQ/FAQ.module.css
- src/pages/common/TermsOfService/TermsOfService.module.css
- src/pages/platformAmbient/Chart/Chart.tsx
- src/pages/platformAmbient/Explore/Explore.module.css
- src/pages/platformAmbient/Level/Level.module.css
- src/pages/platformAmbient/Trade/PointsBanner.module.css
- src/pages/platformAmbient/Trade/TradeCharts/TradeCharts.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeChartsComponents/CurveDepth.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeChartsComponents/OrderHistoryDisplay.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeChartsComponents/TimeFrame.module.css
- src/pages/platformFuta/SwapFuta/SwapFuta.tsx
> Fix merge conflicts mobile sep 9 2

- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
> fix pool switching for infinite scroll pool tx table

- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
Last seen tx id binding reset on scroll to top method
_Closes #0000_
1.
2.
1.
2.
> fix scroll to top problem for page 2 case

- src/App/App.tsx
- src/components/Global/Explore/DexTokens/DexTokens.module.css
- src/components/Global/Explore/PoolRow/PoolRow.module.css
- src/components/Global/Explore/TokenRow/TokenRow.module.css
- src/components/Global/Explore/TopPools/TopPools.module.css
> fix scroll and highlight issues on explore

- src/App/components/PageHeader/PageHeader.module.css
- src/components/Futa/SearchableTicker/SearchableTicker.module.css
- src/pages/platformFuta/Account/Account.module.css
> fix futa scroll issue

- src/pages/Chart/ChartTooltip/ChartTooltip.tsx
- src/pages/Chart/ChartTooltip/ChartTooltipStyles.ts
- src/pages/Trade/TradeCharts/TradeCandleStickChart/TradeCandleStickChart.tsx
- src/pages/platformAmbient/Chart/Chart.tsx
- src/pages/platformAmbient/Chart/Draw/Toolbar/Toolbar.tsx
- src/pages/platformAmbient/Chart/Draw/Toolbar/ToolbarCss.ts
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
> Fix toolbar UI for mobile

- src/contexts/AppStateContext.tsx
- src/pages/Trade/TradeCharts/TradeCharts/TradeCharts.tsx
- src/pages/platformAmbient/Chart/Draw/Toolbar/Toolbar.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.css
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
replaces the chart with a loading indicator placeholder when the user has been idle for more than 10 minutes. 
This is a temporary solution to prevent the app from slowly increasing its memory usage as the app sits idle.
_Closes #0000_
1.
2.
1.
2.
> Disable Chart after 10 minutes of user idle

- src/pages/Trade/TradeCharts/TradeCharts/TradeCharts.tsx
- src/pages/platformAmbient/Chart/Draw/Toolbar/Toolbar.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.css
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
- TradeCandleStickChart import moved to platformAmbient/Trade/TradeCharts/TradeCandleStickChart
- Chart skeleton added when user idle (temporarly solition for memory overflow)
_Closes #0000_
1.
2.
1.
2.
> Chart disabled when user idle

- src/ambient-utils/api/fetchPoolRecentChanges.ts
- src/components/Trade/TradeTabs/TableRowsInfiniteScroll.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
- src/components/Trade/TradeTabs/Transactions/TransactionsBackup.tsx
- src/contexts/GraphDataContext.tsx
- src/styled/Components/TransactionTable.ts
Infinite scroll related actions and variables moved into another component named `TableRowsInfiniteScroll.tsx`
Implementation made for Transactions.tsx component
_Closes #0000_
1.
2.
1.
2.
> Moving infinite scroll into a generic component

- src/contexts/ExploreContext.tsx
removed Blast network exception for $100 minimum TVL for pool to appear in Top Pools list on /explore
_Closes #0000_
1.
2.
1.
2.
> remove blast exception for $100 TVL threshold for Top Pools

- src/pages/Chart/ChartTooltip/ChartTooltip.tsx
- src/pages/Chart/ChartTooltip/ChartTooltipStyles.ts
- src/pages/platformAmbient/Chart/Draw/Toolbar/Toolbar.tsx
- src/pages/platformAmbient/Trade/Trade.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCharts.tsx
- src/pages/platformFuta/SwapFuta/SwapFuta.module.css
- src/pages/platformFuta/SwapFuta/SwapFuta.tsx
- src/styled/Components/Trade.ts
> Futa chart mobile merge develop

- src/App/App.tsx
- src/components/Chat/ChatIFs.tsx
- src/components/Global/TutorialComponent/TutorialComponent.module.css
- src/components/Global/TutorialComponent/TutorialComponent.tsx
- src/components/Global/TutorialOverlay/TutorialOverlayUrlBased.module.css
- src/components/Global/TutorialOverlay/TutorialOverlayUrlBased.tsx
- src/pages/common/CSSDebug/CSSDebug.tsx
- src/pages/common/CSSDebug/CSSModal.module.css
- src/pages/common/CSSDebug/CSSModal.tsx
- src/pages/common/CSSDebug/ColorToggle.module.css
- src/utils/tutorial/Futa/FutaCreateSteps.tsx
> Modalize css debugger

- src/components/Chat/MessagePanel/SentMessagePanel/SentMessagePanel.tsx
- src/pages/platformAmbient/Trade/Range/Range.tsx
> use local images for chat network logos

- src/App/hooks/useTokens.ts
- src/components/Global/Explore/TokenRow/TokenRow.tsx
- src/pages/platformAmbient/Explore/useTokenStats.ts
> fix display of non-local token logos on Top Tokens

- src/pages/platformAmbient/Chart/Draw/Toolbar/Toolbar.tsx
- src/pages/platformAmbient/Trade/Trade.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCharts.module.css
- src/pages/platformAmbient/Trade/TradeCharts/TradeCharts.tsx
> Futa chart css fixes

- package.json
- src/App/hooks/usePoolMetadata.ts
- src/ambient-utils/api/fetchUserPositions.ts
- src/ambient-utils/dataLayer/functions/getPositionData.ts
- src/components/Global/TransactionDetails/TransactionDetailsModal.tsx
- src/components/RangeActionModal/RangeActionModal.tsx
- src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
pull liquidity values directly from on-chain instead of using the values from the indexer due to an outage on scroll affecting the indexer and potentially preventing liquidity removal.
_Closes #0000_
1.
2.
1.
2.
> force onchain liq. update - staging

- src/pages/platformAmbient/Trade/Trade.tsx
- fixed: top pools dropdowns not clickable
- fixed: two dropdowns appear in full screen chart 
_Closes #0000_
1.
2.
1.
2.
> fixed: top pool dropdown not clickable in full screen chart 

- src/components/Futa/Navbar/Navbar.tsx
- src/components/Global/TutorialComponent/TutorialComponent.module.css
- src/components/Global/TutorialComponent/TutorialComponent.tsx
- Navigation buttons for mobile (icon versions)
- Navigation buttons positioning on mobile (bottom navs)
- Little shifting is fixed for navigation bar once tutorial is activated
_Closes #0000_
1.
2.
1.
2.
> Tutorial fixes

- src/App/hooks/usePoolMetadata.ts
- src/ambient-utils/api/fetchUserPositions.ts
- src/ambient-utils/dataLayer/functions/getPositionData.ts
- src/components/Global/TransactionDetails/TransactionDetailsModal.tsx
- src/components/RangeActionModal/RangeActionModal.tsx
- src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
> force onchain liq updates

- package.json
- public/ambient-token-list.json
- src/ambient-utils/constants/ambient-token-list.json
- src/ambient-utils/constants/defaultTokens.ts
- src/ambient-utils/dataLayer/functions/getMoneynessRank.ts
- src/ambient-utils/dataLayer/functions/stablePairs.ts
fix rswETH-ETH not showing up with a price denominated in ETH
> add rswETH as staked ETH token

- src/pages/Chart/ChartSettings/ChartSettings.tsx
- src/pages/platformAmbient/Chart/Chart.tsx
> fixed chart settings not open when press canvas during long time

- src/contexts/AppStateContext.tsx
> attempt to re-activate chart on mobile without touch

- src/contexts/AppStateContext.tsx
- src/pages/platformAmbient/Chart/Draw/Toolbar/Toolbar.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
> increase chart timeout to 20 minutes

- src/components/Global/IconWithTooltip/IconWithTooltip.tsx
- src/components/Global/TooltipComponent/TooltipComponent.module.css
- src/components/Global/TooltipComponent/TooltipComponent.tsx
- src/components/Trade/TableInfo/DetailedBox.tsx
- src/components/Trade/TableInfo/TableInfo.styles.ts
- src/components/Trade/TableInfo/TableInfo.tsx
7. trade/info
1. remove the background graphics entirely 
2. change the arrangement of the lower info boxes to match the figma
1. this will be easier to read and space out
2. obv the stats part isnt implemented at all yet so its fine to leave that out for now
3. the question mark buttons on each field are currently not working
_Closes #0000_
1.
2.
1.
2.
> TRADE/INDFO : add requested changes to info

- src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx
- src/components/Trade/TradeTabs/Orders/Orders.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
- src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx
- src/components/Trade/TradeTabs/Transactions/txRowConstants.tsx
- src/styled/Components/TransactionTable.ts
> replace wallet column with tx/position ID on account tables

- package.json
- yarn.lock
(https://github.com/pillarjs/path-to-regexp/security/advisories/GHSA-9wv6-86v2-598j)
1.
2.
1.
2.
> upgrade p5 dependency

- package.json
- yarn.lock
replaced https://github.com/CrocSwap/ambient-ts-app/pull/4021
_Closes #0000_
1.
2.
1.
2.
> update alchemy sdk package

- src/pages/Chart/ChartTooltip/ChartTooltipStyles.ts
- src/pages/platformAmbient/Trade/Trade.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCharts.tsx
> timeframe section moved to top of chart for mobile

- src/pages/platformAmbient/Chart/FeeRate/FeeRateChart.tsx
- src/pages/platformAmbient/Chart/Tvl/TvlChart.tsx
> fixed: tvl and fee rate charts overflows when zooming

- package.json
- src/ambient-utils/api/fetchNft.ts
- src/contexts/ChainDataContext.tsx
- yarn.lock
remove the Alchemy SDK dependency and replace with an HTTP fetch request for a user's NFTs.
_Closes #0000_
1.
2.
1.
2.
> remove alchemy SDK dependency

- package.json
- yarn.lock
Reverts CrocSwap/ambient-ts-app#4201
> Revert "Bump framer-motion from 4.1.17 to 11.11.4"

- src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.tsx
> fixed:  shareable chart x axis tick overlap for mobile device

- package.json
- yarn.lock
> upgrade ethers to 6.13.3

- src/contexts/ChartContext.tsx
- src/pages/Chart/ChartSettings/ChartSettings.tsx
- src/pages/Chart/ChartSettings/ChartSettingsContent.tsx
- src/pages/Chart/ChartSettings/ChartSettingsCss.ts
- src/pages/platformAmbient/Chart/Chart.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCharts.module.css
- src/pages/platformAmbient/Trade/TradeCharts/TradeCharts.tsx
> Chart settings mobile refactor

- src/App/components/PageHeader/UserMenu/LevelDropdown/LevelDropdown.tsx
- src/components/Global/LevelsCard/UserLevelDisplay.tsx
- src/components/Portfolio/PortfolioBanner/PortfolioBannerAccount/PortfolioBannerAccount.module.css
- src/components/Portfolio/PortfolioBanner/PortfolioBannerAccount/PortfolioBannerAccount.tsx
- src/components/Portfolio/PortfolioTabs/PortfolioTabs.tsx
- src/utils/hooks/useLinkGen.ts
> add buttons to mobile account view

- src/ambient-utils/constants/blacklist.ts
- src/ambient-utils/dataLayer/functions/getPoolStats.ts
- src/components/Trade/TradeModules/TradeModuleSkeleton.tsx
- src/contexts/ExploreContext.tsx
- src/pages/platformAmbient/Explore/Explore.tsx
add list of tokens to be ineligible for display on the Top Pools and Top Tokens list on /explore
_Closes #0000_
1.
2.
1.
2.
> add excluded token filter for top pools/tokens

- src/components/Global/LevelsCard/LevelsCard.module.css
- src/components/Global/LevelsCard/LevelsCard.tsx
- src/pages/platformAmbient/Level/Level.tsx
> bugfix/ fix level card profile picture while taking screenshot

- src/pages/Chart/ChartTooltip/ChartTooltip.tsx
- src/pages/platformAmbient/Chart/Draw/Toolbar/Toolbar.tsx
- src/pages/platformAmbient/Chart/Draw/Toolbar/ToolbarCss.ts
- src/styled/Components/Trade.ts
> fixed : tablet screen issues for ambient

- package.json
- src/ambient-utils/constants/index.ts
update mainnet fallback RPC to llamarpc
_Closes #0000_
1.
2.
1.
2.
> update mainnet fallback RPC

- package.json
- src/ambient-utils/constants/index.ts
- src/ambient-utils/constants/networks/blastNetwork.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
> update fallback RPC endpoints

- src/components/Trade/TradeTabs/Orders/OrderTable/OrderHeader.tsx
- src/components/Trade/TradeTabs/Ranges/RangesTable/RangeHeader.tsx
- src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionHeader.tsx
without padding:
with padding:
_Closes #0000_
1.
2.
1.
2.
> add right padding to table header labels

- package.json
- src/pages/platformAmbient/Vanity/Vanity.tsx
- src/routes/PlatformAmbient.tsx
add support for vanity links like https://deploy-preview-4239--staging-ambient.netlify.app/v/SCRETH
_Closes #0000_
1.
2.
1.
2.
> add vanity link subroute - staging

- package.json
- src/pages/platformAmbient/Vanity/Vanity.tsx
- src/routes/PlatformAmbient.tsx
add support for vanity links 
e.g. 
https://deploy-preview-4238--dev-ambi.netlify.app/v/SCRETH
_Closes #0000_
1.
2.
1.
2.
> add vanity link subroute

- index.html
- package.json
- vite.config.ts
> add version to html - staging

- src/ambient-utils/dataLayer/functions/getPoolStats.ts
> remove provider call for pool price on /explore

- src/ambient-utils/dataLayer/functions/getPoolStats.ts
- src/contexts/ExploreContext.tsx
- src/pages/platformAmbient/Explore/Explore.tsx
> remove chained top pools query

- src/App/App.tsx
- src/ambient-utils/constants/blacklist.ts
- src/ambient-utils/dataLayer/functions/getPoolStats.ts
- src/components/Global/Modal/Modal.tsx
- src/components/Global/NoTokenIcon/NoTokenIcon.module.css
- src/components/Global/TokenIcon/processLogoSrc.ts
- src/components/Trade/TradeModules/TradeModuleSkeleton.tsx
- src/pages/platformAmbient/Explore/Explore.tsx
prevent fraudulent tokens from appearing with the token logo for a real token with the same symbol
_Closes #0000_
1.
2.
1.
2.
> prevent excluded address from getting real logos

- src/App/components/PageHeader/PageHeader.tsx
change z index to 0.1 when bottom sheet is opened in navbar
_Closes #0000_
1.
2.
1.
2.
> change z index to 0.1 when bottom sheet is opened in navbar

- src/App/hooks/useTokens.ts
- prevent properly formatted token symbols in the Ambient token list from being overwritten by other values for the same tokens in other lists
- prevent duplicate token listings in token selector when wallet is connected
_Closes #0000_
1.
2.
1.
2.
> Prevent overwriting ambient token list value

- src/pages/platformAmbient/Chart/Draw/Toolbar/ToolbarCss.ts
> fixed: disappear toolbar  if fullscreen chart

- src/contexts/ExploreContext.tsx
- src/pages/platformAmbient/Explore/Explore.tsx
add 100ms pause during Top Pools manual refresh to allow spinner to momentarily appear
_Closes #0000_
1.
2.
1.
2.
> add pause during Top Pools reload

- src/components/Home/TopPoolsHome/TopPoolsHome.tsx
- src/contexts/CrocEnvContext.tsx
> fix crocEnv replacement when not logged in

- package.json
test PR for new deployment process
> bump version to 2.9.15

- src/App/hooks/useTokens.ts
test release for new deployment process
> Release 2.9.15

- src/pages/platformAmbient/Chart/Axes/yAxis/YaxisCanvas.tsx
- src/pages/platformAmbient/Chart/Chart.css
- src/pages/platformAmbient/Chart/Chart.tsx
- src/pages/platformAmbient/Chart/Volume/VolumeBarCanvas.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeChartsHeader/TradeChartsHeader.tsx
- [fixed: volume bars broken on screenshot](https://github.com/CrocSwap/ambient-ts-app/commit/846ecac0280a4b3a5296f524397091e18b029ed2)
- [fixed: bottom of chart not show in screenshot when screen width below 1500](https://github.com/CrocSwap/ambient-ts-app/commit/cd193db1ac1c2e2b26f6d6cc8878f648b842af1f)
_Closes #0000_
1.
2.
1.
2.
> Fix broke volume when copy clipboard

- src/pages/platformAmbient/InitPool/InitSkeleton.tsx
> fix padding on pool init

- package.json
- src/ambient-utils/constants/defaultTokens.ts
- src/contexts/ChainDataContext.tsx
allow a hidden token to be defined in defaultTokens without appearing in the token selector when a wallet is connected
_Closes #0000_
1.
2.
1.
2.
> Fix hidden token filter of token balances

- src/App/components/Sidebar/SidebarSearchResults/PoolsSearchResults/PoolsSearchResults.tsx
- src/App/hooks/useFetchPoolStats.ts
- src/App/hooks/usePoolMetadata.ts
- src/ambient-utils/api/fetchCandleSeries.ts
- src/ambient-utils/api/fetchTokenPrice.ts
- src/ambient-utils/dataLayer/functions/getLimitOrderData.ts
- src/ambient-utils/dataLayer/functions/getPositionData.ts
- src/ambient-utils/dataLayer/functions/querySpotPrice.ts
- src/components/Global/DetailModals/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx
- src/components/Global/DetailModals/TransactionDetailsGraph/TransactionDetailsGraph.tsx
- src/components/Global/Sidebar/FavoritePools.tsx
- src/components/Global/Sidebar/RecentPools.tsx
- src/components/Global/Sidebar/TopPools.tsx
- src/components/Home/TopPoolsHome/TopPoolsHome.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/pages/platformAmbient/Explore/useTokenStats.ts
> gatekeep pool price fetches based on crocEnv chainId

- src/components/Trade/TradeTabs/Orders/Orders.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
> Merge develop network switch 2

- src/components/Global/DetailModals/TransactionDetails/TransactionDetailsPriceInfo/TransactionDetailsPriceInfo.tsx
- src/components/Trade/TradeTabs/Transactions/txRowConstants.tsx
- src/utils/hooks/useProcessRange.ts
- src/utils/hooks/useProcessTransaction.ts
interpret token price range maximum values greater than $1 billion as infinity
1.
2.
1.
2.
> Fix table cell overflow for long price

- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
Added resetters for user txs cases to fix redundant data display on pair change
_Closes #0000_
1.
2.
1.
2.
> Infinite scroll - fix Transactions

- src/App/components/PageHeader/PageHeader.tsx
- src/App/hooks/useAppChain.ts
- src/components/Portfolio/PortfolioTabs/PortfolioTabs.tsx
- src/components/Trade/TradeTabs/Orders/Orders.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
- src/pages/platformAmbient/Portfolio/Portfolio.tsx
- src/utils/hooks/useLinkGen.ts
> remove reload on portfolio when wallet not connected

- src/App/components/PageHeader/PageHeader.tsx
> fix ambient logo in page header

- src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx
- src/ambient-utils/constants/networks/blastMainnet.ts
- src/ambient-utils/constants/networks/blastSepolia.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/ethereumSepolia.ts
- src/ambient-utils/constants/networks/index.ts
- src/ambient-utils/constants/networks/plumeSepolia.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/ambient-utils/constants/networks/scrollSepolia.ts
- src/ambient-utils/types/NetworkIF.ts
- src/assets/branding/ambientTestnetBrandAssets.ts
- src/assets/branding/defaultBrandAssets.ts
- src/contexts/CrocEnvContext.tsx
- src/index.tsx
> clean up network specs

- src/ambient-utils/types/index.ts
- src/ambient-utils/types/vaults/index.ts
- src/ambient-utils/types/vaults/vaultIF.ts
- src/ambient-utils/types/vaults/vaultServerIF.ts
- src/pages/platformAmbient/Vaults/VaultRow/VaultRow.tsx
- src/pages/platformAmbient/Vaults/Vaults.tsx
- tsconfig.json
> Create vault data interface

- src/pages/platformAmbient/InitPool/InitButton.tsx
- src/pages/platformAmbient/InitPool/InitPool.tsx
> fix pool init spending cap suggestion

- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
fix missing 'Hide Empty Positions' toggle on /account
_Closes #0000_
1.
2.
1.
2.
> fix missing empty positions display toggle

- src/pages/platformAmbient/Vaults/Vaults.tsx
fix disappearing vault modals. theory is that the row component would get regenerated when TVL or other vault data would change, causing the modals opened from those rows to close.
_Closes #0000_
1.
2.
1.
2.
> fix disappearing vault modals

- src/ambient-utils/constants/networks/blastMainnet.ts
- src/ambient-utils/constants/networks/blastSepolia.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/ethereumSepolia.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/ambient-utils/constants/networks/scrollSepolia.ts
- src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx
> fix explorer links

- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
- src/components/Trade/TradeTabs/Transactions/txRowConstants.tsx
- Removed redundant useEffect on component to not refresh itself in a redundant way
- Hidden id field key is changed to mark single row on list
_Closes #0000_
1.
2.
1.
2.
> Infinite Scroll | Fix for user transactions page

- src/ambient-utils/api/fetchUserPositions.ts
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/useSortedPositions.ts
prevent liquidity tables from reverting to a previous state after an update
replaces: https://github.com/CrocSwap/ambient-ts-app/pull/4334
_Closes #0000_
1.
2.
1.
2.
> Prevent liq table reversion

- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/useSortedPositions.ts
useSortedPositions.tsx and Ranges.tsx revised to support user's liquidity changes
_Closes #0000_
1.
2.
1.
2.
> Infinite scroll | update liq changes

- src/contexts/ChainDataContext.tsx
> fix fetch of wallet balances

- src/components/Portfolio/PortfolioBanner/PortfolioBannerAccount/PortfolioBannerAccount.module.css
> prevent wallet address from wrapping in Portfolio banner

- src/components/Home/Landing/MobileLandingSections.tsx
- src/pages/platformAmbient/Trade/TradeMobile.tsx
added mobileActiveTab key to local storage for mobile
> keep selected tab fixed when switching networks

- public/ambient-token-list.json
- src/ambient-utils/constants/ambient-token-list.json
- src/ambient-utils/constants/defaultTokens.ts
- src/ambient-utils/dataLayer/functions/stablePairs.ts
> add rsETH on Scroll to ambient token list

- src/components/Global/Modal/Modal.tsx
- src/pages/platformAmbient/Vaults/VaultActionModal/VaultWithdraw/VaultWithdraw.module.css
- src/pages/platformAmbient/Vaults/VaultActionModal/VaultWithdraw/VaultWithdraw.tsx
- src/pages/platformAmbient/Vaults/Vaults.tsx
> fix slippage blur function

- src/ambient-utils/dataLayer/functions/getFormattedNumber.ts
- src/ambient-utils/dataLayer/functions/getPositionData.ts
- src/components/Global/DetailModals/OrderDetails/OrderDetailsModal/OrderDetailsModal.tsx
- src/components/Global/DetailModals/OrderDetails/OrderDetailsSimplify/OrderDetailsSimplify.tsx
- src/components/Global/DetailModals/OrderDetails/PriceInfo/PriceInfo.tsx
- src/components/Global/DetailModals/RangeDetails/RangeDetailsSimplify/RangeDetailsSimplify.tsx
- src/utils/hooks/useProcessOrder.ts
- src/utils/hooks/useProcessRange.ts
- src/utils/hooks/useProcessTransaction.ts
before: 
after: 
_Closes #0000_
1.
2.
1.
2.
> remove extra trailing zeros from table data token quantities

- src/contexts/CandleContext.tsx
> Fix chart reloading on disconnect

- src/contexts/CandleContext.tsx
> prevent candle fetching race condition on pool switch

- src/contexts/CandleContext.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
> attempt to fix stuck chart due to memoized empty chartSettings

- src/App/hooks/usePoolMetadata.ts
- src/ambient-utils/api/fetchPoolLiquidity.ts
- src/components/Global/DetailModals/TransactionDetailsGraph/TransactionDetailsLiquidityGraph.tsx
- src/contexts/GraphDataContext.tsx
- src/pages/platformAmbient/Chart/Liquidity/LiquidityChart.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
fix stuck or disappearing liquidity curve/depth chart after pool change
_Closes #0000_
1.
2.
1.
2.
> check for crocEnv mismatch before liq chart data request

- src/App/components/PageHeader/NetworkSelector/NetworkSelector.module.css
- src/components/Global/DropdownMenu2/DropdownMenu2.module.css
- src/components/Global/Modal/Modal.module.css
fix modal layout in dropdown menu and modal
_Closes #0000_
> fix modal layout in dropdown menu and modal

- src/App/hooks/useAppChain.ts
- src/ambient-utils/constants/networks/blastMainnet.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/index.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/contexts/CrocEnvContext.tsx
> fix addition of private RPC to metamask

- src/App/hooks/useTokens.ts
- src/ambient-utils/constants/blacklist.ts
- fix issue with token universe not updating
- fix issue with display of previous version of Ambient Testnet USDC on Swell Testnet
token universe would not update after switching chains with exactly the same number of tokens
1.
2.
1.
2.
> fix token selector on testnets

- src/contexts/CandleContext.tsx
replaces https://github.com/CrocSwap/ambient-ts-app/pull/4394
fixes chart reload when user connects/disconnects their wallet
1.
2.
1.
2.
> Fix chart reload when user connects/disconnects wallet

- src/contexts/CandleContext.tsx
> fixed : chart reloading when user connect/disconnect

- docs/release/testnet_token_contract.sol
- public/ambient-token-list.json
- src/App/hooks/useFetchPoolStats.ts
- src/ambient-utils/constants/ambient-token-list.json
- src/ambient-utils/constants/defaultTokens.ts
- src/ambient-utils/dataLayer/functions/stablePairs.ts
> replace swell sepolia usdc

- src/App/components/PageHeader/PageHeader.tsx
prevent vaults link from appearing on deployments where none of the supported networks support vaults
vaults link was displaying on network-specific deployments when vaults were not supported on that network
1.
2.
1.
2.
> prevent unexpected vaults link in page header 

- src/App/components/PageHeader/UserMenu/UserProfileCard.tsx
- src/App/hooks/useHandleRangeButtonMessage.ts
- src/App/hooks/usePoolMetadata.ts
- src/App/hooks/useSimulatedIsPoolInitialized.ts
- src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx
- src/components/Portfolio/ExchangeBalance/Transfer/Transfer.tsx
- src/components/Portfolio/ExchangeBalance/Withdraw/Withdraw.tsx
- src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
- src/components/Trade/Limit/LimitTokenInput/LimitTokenInput.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
- src/contexts/AppStateContext.tsx
- src/contexts/CandleContext.tsx
- src/contexts/ChainDataContext.tsx
- src/contexts/CrocEnvContext.tsx
- src/contexts/ExploreContext.tsx
- src/contexts/GraphDataContext.tsx
- src/contexts/UserDataContext.tsx
- src/pages/platformAmbient/Level/Level.tsx
- src/pages/platformAmbient/Trade/Limit/Limit.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
Prevent the app from looking broken when the user goes offline or looking out of date when user returns from offline.
_Closes #0000_
1.
2.
1.
2.
> improve offline handling

- src/App/hooks/useFetchPoolStats.ts
- src/App/hooks/usePoolMetadata.ts
- src/components/Swap/SwapExtraInfo/SwapExtraInfo.tsx
- src/components/Trade/Limit/ConfirmLimitModal/ConfirmLimitModal.tsx
- src/components/Trade/Limit/LimitExtraInfo/LimitExtraInfo.tsx
- src/components/Trade/Range/ConfirmRangeModal/SelectedRange/SelectedRange.tsx
- src/components/Trade/Range/RangeExtraInfo/RangeExtraInfo.tsx
- src/components/Trade/Reposition/RepositionPriceInfo/RepositionPriceInfo.tsx
- src/components/Trade/TableInfo/FeaturedBox.tsx
- src/components/Trade/TableInfo/TableInfo.tsx
- src/contexts/GraphDataContext.tsx
- src/contexts/TradeDataContext.tsx
- src/pages/platformAmbient/Trade/Limit/Limit.tsx
- src/pages/platformAmbient/Trade/Range/Range.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeChartsComponents/PoolData.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeChartsComponents/TradeChartsTokenInfo.tsx
- fix the clearing of pool price variables when the on-chain query returns zero
- fix the updating of pool fee rate when pool changes
pool price sometimes appearing for uninitialized pools
1.
2.
1.
2.
> fix incorrect pool price and fee rate appearing for uninitialized pools

- src/App/hooks/useFetchPoolStats.ts
- src/ambient-utils/api/fetchAprEst.ts
- src/ambient-utils/types/pool/PoolStatIF.ts
- src/components/Trade/Range/RangeExtraInfo/RangeExtraInfo.tsx
- src/pages/platformAmbient/Trade/Range/Range.tsx
add estimated APR for a new range position
_Closes #0000_
1.
2.
1.
2.
> add estimate for new position APR

- src/pages/platformAmbient/InitPool/InitPool.tsx
- src/pages/platformAmbient/Trade/Range/Range.tsx
prevent prompt to approve a token not needed to be deposited when user mints an out of range position
1.
2.
1.
2.
> fix out of range position mint approval logic

- package.json
- yarn.lock
> upgrade to vite v6

- src/App/hooks/usePoolMetadata.ts
remove unnecessary crocEnv gatekeeping
stable pairs were not getting the correct default range width on initial app load
1.
2.
1.
2.
> fix default range width

- src/pages/platformAmbient/Vaults/VaultRow/VaultRow.tsx
- src/pages/platformAmbient/Vaults/Vaults.tsx
instead of showing the default vaults list while waiting for the tempest API, show a loading indicator and only show the default list if the query fails.
_Closes #0000_
1.
2.
1.
2.
> add vaults list loading indicator

- src/components/Global/DetailModals/TransactionDetailsGraph/TransactionDetailsGraph.tsx
> fix missing chart for liquidity position after mint/update 

- src/pages/platformAmbient/Trade/Reposition/Reposition.tsx
prevent resetting the reposition module when the Reposition button for the same position is clicked multiple times
_Closes #0000_
1.
2.
1.
2.
> prevent reposition module getting stuck after multiple clicks of same reposition button

- package.json
- src/App/functions/approve.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/types/vaults/index.ts
- src/ambient-utils/types/vaults/vaultStrategy.ts
- src/pages/platformAmbient/Vaults/VaultActionModal/VaultDeposit/VaultDeposit.tsx
- src/pages/platformAmbient/Vaults/VaultActionModal/VaultWithdraw/VaultWithdraw.tsx
- src/pages/platformAmbient/Vaults/VaultRow/VaultRow.tsx
- src/pages/platformAmbient/Vaults/Vaults.tsx
- yarn.lock
bump Crocswap SDK and pass a strategy value depending on active chain to fix mainnet vault transactions
_Closes #0000_
1.
2.
1.
2.
> add vault strategy to fix ETH / rswETH vault transactions

- src/pages/platformAmbient/Chart/Liquidity/LiquidityChart.tsx
> bugfix/ fix liq line highlighted in advanced mode

- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/tokenUnicodeCharMap.ts
- src/ambient-utils/dataLayer/functions/getMoneynessRank.ts
- src/ambient-utils/dataLayer/functions/stablePairs.ts
- src/components/Global/PoolCard/PoolCard.tsx
- src/contexts/PoolContext.tsx
update display of tBTC pools to match Wbtc
_Closes #0000_
1.
2.
1.
2.
> define tBTC as staked BTC

- src/i18n/zh/common.json
supplement Chinese translation
> i18n: supplement Chinese translation

- src/App/hooks/useFetchPoolStats.ts
- src/ambient-utils/dataLayer/functions/getPoolStats.ts
> fix TVL display on trade route

- src/components/Home/Landing/MobileLandingSections.tsx
- src/contexts/ChainDataContext.tsx
> fix missing L2 network logos on mobile homepage

- src/assets/branding/ambientProductionBrandAssets.ts
- src/assets/branding/ambientTestnetBrandAssets.ts
- src/assets/branding/baseSepoliaBrandAssets.ts
- src/assets/branding/blastBrandAssets.ts
- src/assets/branding/defaultBrandAssets.ts
- src/assets/branding/futaBrandAssets.ts
- src/assets/branding/plumeSepoliaBrandAssets.ts
- src/assets/branding/sampleBrandAssets.ts
- src/assets/branding/scrollBrandAssets.ts
- src/assets/branding/swellBrandAssets.ts
- src/assets/branding/swellSepoliaBrandAssets.ts
- src/assets/branding/types.ts
- src/components/Home/Landing/Hero.tsx
- src/components/Home/Landing/MobileLandingSections.tsx
- src/contexts/BrandContext.tsx
updated logic to simplify the definition of the cobranding logo and use the same definition for desktop & mobile.
_Closes #0000_
1.
2.
1.
2.
> simplify definition of cobranding logo

- src/index.tsx
attempt to fix remaining issues when the user tries to connect their wallet
_Closes #0000_
1.
2.
1.
2.
> add delay before checking currently connected chain

- src/components/Home/Landing/Investors.tsx
- src/components/Home/Landing/LandingSections.tsx
> add loading='lazy' for homepage images under page break

- src/App/hooks/useFetchPoolStats.ts
24h price change and volume change calculations were incorrect for pools with little to no liquidity and a relatively large last swap.
1.
2.
1.
2.
> fix 24h change stats for pool info

- src/App/hooks/useFetchPoolStats.ts
- src/ambient-utils/api/fetchCandleSeries.ts
- src/ambient-utils/dataLayer/functions/getPoolStats.ts
- src/contexts/ExploreContext.tsx
> fix volume calc edge case

- src/App/components/PageHeader/PageHeader.tsx
- src/ambient-utils/dataLayer/functions/chains.ts
- src/contexts/ChainDataContext.tsx
- src/contexts/UserDataContext.tsx
- src/pages/platformAmbient/Vaults/NoVaults.tsx
- src/pages/platformAmbient/Vaults/Vaults.tsx
> save vaults data to context

- index.html
- netlify.toml
- package.json
- public/google8802b6df6f9999e8.html
- vite.config.ts
improve time to start render and add background color during local build 
before:
after:
_Closes #0000_
1.
2.
1.
2.
> add dark background color during app load

- src/pages/platformAmbient/Chart/Liquidity/LiquidityChart.tsx
> bugfix/ fix liq highlighted lines on depth mode and ambient position

- src/components/Home/Stats/AmbientStats.tsx
- src/contexts/ChainDataContext.tsx
move dex stats to context to avoid refreshing every time the user loads the homepage
_Closes #0000_
1.
2.
1.
2.
> move dex stats to chain context

- src/contexts/ChainDataContext.tsx
> prevent dex stats fetching when disabled

- src/pages/platformAmbient/Trade/Limit/Limit.tsx
- src/pages/platformAmbient/Trade/Range/Range.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
> bug fix: trade confirm button stuck after pool change

- package.json
- src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx
- src/App/hooks/useAppChain.ts
- src/ambient-utils/api/fetchTokenPrice.ts
- src/ambient-utils/constants/ambient-token-list.json
- src/ambient-utils/constants/defaultTokens.ts
- src/ambient-utils/constants/gcgo.ts
- src/ambient-utils/constants/networks/index.ts
- src/ambient-utils/constants/networks/plumeMainnet.ts
- src/ambient-utils/dataLayer/functions/lookupChainId.ts
- src/ambient-utils/types/chainHexIds.ts
- src/assets/branding/defaultBrandAssets.ts
- src/assets/branding/index.ts
- src/assets/branding/plumeBrandAssets.ts
- src/contexts/BrandContext.tsx
- src/contexts/ChainDataContext.tsx
- src/index.tsx
- yarn.lock
> add Plume mainnet

- src/App/components/PageHeader/UserMenu/WalletDropdown/WalletDropdown.tsx
- src/ambient-utils/constants/defaultTokens.ts
- src/ambient-utils/constants/networks/plumeMainnet.ts
- src/ambient-utils/dataLayer/functions/stablePairs.ts
> add Plume USD and NEV tokens

- src/pages/platformAmbient/Trade/Limit/Limit.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
> add default approval quantity buffer for floating side on swaps

- src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
> fix swap impact update when string changes but number remains the same

- src/App/functions/approve.ts
- src/App/hooks/useCreateRangePosition.ts
- src/App/hooks/useSendInit.ts
- src/components/Global/NotificationCenter/NotificationTable/NotificationTable.tsx
- src/components/Global/NotificationCenter/ReceiptDisplay/ReceiptDisplay.tsx
- src/components/LimitActionModal/LimitActionModal.tsx
- src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx
- src/components/Portfolio/ExchangeBalance/Transfer/Transfer.tsx
- src/components/Portfolio/ExchangeBalance/Withdraw/Withdraw.tsx
- src/components/RangeActionModal/RangeActionModal.tsx
- src/contexts/ReceiptContext.tsx
- src/pages/platformAmbient/InitPool/InitPool.tsx
- src/pages/platformAmbient/Trade/Limit/Limit.tsx
- src/pages/platformAmbient/Trade/Reposition/Reposition.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
- src/pages/platformAmbient/Vaults/VaultActionModal/VaultDeposit/VaultDeposit.tsx
- src/pages/platformAmbient/Vaults/VaultActionModal/VaultWithdraw/VaultWithdraw.tsx
> fix notification center explorer links after switching networks

- src/components/Global/NotificationCenter/ReceiptDisplay/ReceiptDisplay.module.css
- src/components/Global/NotificationCenter/ReceiptDisplay/ReceiptDisplay.tsx
REFACTOR NOTIFICATION CENTER CARD LAYOUT TO INCREASE CLICKABLE AREA.
CLICKING ANYWHERE ON THE CARD EXCEPT FOR THE CLOSE ICON SHOULD NOW TAKE YOU TO THE ETHERSCAN LINK
_Closes #0000_
1.
2.
1.
2.
> change clickable area on notification center

- src/ambient-utils/constants/ambient-token-list.json
- src/ambient-utils/constants/defaultTokens.ts
- src/ambient-utils/dataLayer/functions/stablePairs.ts
> add USDe on Swell

- package.json
- src/ambient-utils/constants/networks/swellMainnet.ts
- src/ambient-utils/dataLayer/functions/stablePairs.ts
> add swell top pools

- src/App/hooks/useTokens.ts
> fix RPC token lookup when token has same address on other chain

- src/contexts/ChainDataContext.tsx
- src/contexts/CrocEnvContext.tsx
> add Swell to Dex Stats

- package.json
- src/pages/platformAmbient/Vaults/VaultRow/VaultRow.tsx
hide invalid vault APR estimates
1.
2.
1.
2.
> Hide vault apr until valid

- package.json
- src/ambient-utils/constants/networks/baseSepolia.ts
- src/ambient-utils/constants/networks/blastMainnet.ts
- src/ambient-utils/constants/networks/blastSepolia.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/ethereumSepolia.ts
- src/ambient-utils/constants/networks/index.ts
- src/ambient-utils/constants/networks/plumeMainnet.ts
- src/ambient-utils/constants/networks/plumeSepolia.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/ambient-utils/constants/networks/scrollSepolia.ts
- src/ambient-utils/constants/networks/swellMainnet.ts
- src/ambient-utils/constants/networks/swellSepolia.ts
- src/ambient-utils/types/NetworkIF.ts
- src/pages/platformAmbient/Vaults/VaultRow/VaultRow.tsx
> Fix swell vault links

- package.json
- src/ambient-utils/constants/networks/baseSepolia.ts
- src/ambient-utils/constants/networks/blastMainnet.ts
- src/ambient-utils/constants/networks/blastSepolia.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/ethereumSepolia.ts
- src/ambient-utils/constants/networks/index.ts
- src/ambient-utils/constants/networks/plumeMainnet.ts
- src/ambient-utils/constants/networks/plumeSepolia.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/ambient-utils/constants/networks/scrollSepolia.ts
- src/ambient-utils/constants/networks/swellMainnet.ts
- src/ambient-utils/constants/networks/swellSepolia.ts
- src/ambient-utils/types/NetworkIF.ts
- src/pages/platformAmbient/Vaults/VaultRow/VaultRow.tsx
- src/pages/platformAmbient/Vaults/Vaults.tsx
- fixed links to app.tempestfinance.xyz from /vaults when connected to swell network
> Release 2.12.15

- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/contexts/CandleContext.tsx
add missing useEffect dependency
chart would sometimes get stuck loading, especially navigating to /trade after landing on another page
1.
2.
1.
2.
> fix chart loading bug

- package.json
- src/ambient-utils/constants/networks/baseSepolia.ts
- src/ambient-utils/constants/networks/blastMainnet.ts
- src/ambient-utils/constants/networks/blastSepolia.ts
- src/ambient-utils/constants/networks/ethereumSepolia.ts
- src/ambient-utils/constants/networks/plumeMainnet.ts
- src/ambient-utils/constants/networks/plumeSepolia.ts
- src/ambient-utils/constants/networks/scrollSepolia.ts
- src/ambient-utils/constants/networks/swellSepolia.ts
- src/ambient-utils/types/NetworkIF.ts
- fixed bug causing chart to sometimes never finish loading
> Release 2.12.16

- package.json
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/contexts/CandleContext.tsx
- add missing commit to fix chart loading bug
> Release 2.12.17

- package.json
- src/ambient-utils/dataLayer/functions/lookupChainId.ts
- add support for "swellchain" network name alias
> release 2.12.18

- src/components/Global/ModalHeader/ModalHeader.tsx
> add close bottom sheet function to modal header

- src/components/Trade/TradeTabs/NoTableData/NoTableData.tsx
- src/components/Trade/TradeTabs/Orders/Orders.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/TradeTabs2.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
> fix no transactions in candle prompts

- src/components/Global/TokenSelectContainer/SoloTokenSelect.tsx
- src/components/Global/TokenSelectContainer/SoloTokenSelectModal.tsx
> allow pasting address without focusing input field

- src/App/components/PageHeader/NetworkSelector/NetworkSelector.module.css
> remove min width value of network selector

- src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx
- src/components/Portfolio/ExchangeBalance/Transfer/Transfer.tsx
- src/components/Portfolio/ExchangeBalance/Withdraw/Withdraw.tsx
- src/pages/platformAmbient/Trade/Limit/Limit.tsx
- src/pages/platformAmbient/Trade/Range/Range.tsx
- src/pages/platformAmbient/Trade/Reposition/Reposition.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
> prevent L2 gas estimates of $0.00

- src/components/Global/TutorialOverlay/TutorialOverlayUrlBased.module.css
- src/components/Home/Landing/Hero.tsx
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding5.tsx
> fix tutorial overlapping with notification center on futa

- src/components/Futa/Navbar/Navbar.module.css
- src/components/Futa/SearchableTicker/SearchableTicker.module.css
- src/components/Futa/SearchableTicker/SearchableTicker.tsx
- src/index.css
- src/pages/platformAmbient/Trade/TradeMobile.tsx
- src/pages/platformFuta/Auctions/Auctions.module.css
> Fix scatter chart gap on FUTA mobile

- src/components/Futa/SearchableTicker/SearchableTicker.tsx
- src/pages/Chart/ChartTooltip/ChartTooltip.tsx
- src/pages/Chart/ChartTooltip/ChartTooltipStyles.ts
- src/pages/platformAmbient/Chart/Draw/Toolbar/Toolbar.tsx
- src/pages/platformAmbient/Chart/Draw/Toolbar/ToolbarCss.ts
- src/pages/platformAmbient/Trade/TradeCharts/TradeCharts.module.css
- src/pages/platformAmbient/Trade/TradeCharts/TradeCharts.tsx
- src/pages/platformAmbient/Trade/TradeMobile.module.css
- src/pages/platformAmbient/Trade/TradeMobile.tsx
- src/pages/platformFuta/SwapFuta/SwapFuta.tsx
- src/routes/PlatformFuta.tsx
Fixed;
- Toolbar overlap in Futa mobile
- Timeframe div overlap in Futa laptop screen 
- Chart full screen button functionality
- Below Trade Page black gap in Futa tablet
_Closes #0000_
1.
2.
1.
2.
> Futa ui issues

- src/components/Futa/TickerComponent/tickerDisplayElements.tsx
_Closes #0000_
-   [x] Is this PR ready for merge? (Please convert to a draft PR otherwise)
-   [x] I have performed a self-review of my code.
-   [x] Does my code following the style guide at `docs/CODING-STYLE.md`?
> update ref and clickable areas on max fdv dropdown

- src/components/Futa/Navbar/Navbar.tsx
> navigate on mouse down for futa links

- src/components/Futa/Navbar/Navbar.module.css
- src/components/Futa/Navbar/Navbar.tsx
- src/components/Futa/SearchableTicker/SearchableTicker.module.css
- src/components/Global/NotificationCenter/ActivityIndicator/ActivityIndicator.module.css
- src/components/Global/NotificationCenter/ActivityIndicator/ActivityIndicator.tsx
- src/pages/platformFuta/Account/Account.module.css
- src/pages/platformFuta/Account/Account.tsx
1. Refactor account layout on smaller devices
2.  Change tutorial icon to match figma
3. Fix paddings on ticker table and table headers
4. Create pulsing animation for notification
> address layout issues and minor changes on FUTA

- src/ambient-utils/constants/ambient-token-list.json
- src/ambient-utils/constants/blacklist.ts
- src/ambient-utils/constants/defaultTokens.ts
> update plume mainnet tokens

- src/components/LimitActionModal/LimitActionModal.tsx
- src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx
- src/components/Portfolio/ExchangeBalance/Transfer/Transfer.tsx
- src/components/Portfolio/ExchangeBalance/Withdraw/Withdraw.tsx
- src/components/RangeActionModal/RangeActionModal.tsx
- src/components/Trade/TradeModules/TradeModuleSkeleton.tsx
- src/pages/platformAmbient/Trade/Reposition/Reposition.tsx
remove smol refuel links as requested by Miyu and the Plume team
_Closes #0000_
1.
2.
1.
2.
> remove smol refuel links

- src/contexts/ExploreContext.tsx
- src/pages/platformAmbient/Explore/Explore.tsx
> fix intermittent blank top pools page

- src/contexts/ExploreContext.tsx
> fix top pools data updates on /explore

- src/contexts/ChartContext.tsx
- src/index.css
- src/pages/platformAmbient/Chart/Candle/CandleChart.tsx
- src/pages/platformAmbient/Chart/Chart.tsx
- src/pages/platformAmbient/Chart/FeeRate/FeeRateChart.tsx
- src/pages/platformAmbient/Chart/RangeLine/RangeLinesChart.tsx
- src/pages/platformAmbient/Chart/Tvl/TvlChart.tsx
> switch to red/green default candle colors

- src/components/Global/RangeBounds/RangeBounds.tsx
- src/components/Trade/Range/RangePriceInfo/RangePriceInfo.module.css
- src/components/Trade/Range/RangePriceInfo/RangePriceInfo.tsx
- src/pages/platformAmbient/Trade/Range/Range.tsx
add estimated APR display outside of extra info section
_Closes #0000_
1.
2.
1.
2.
> add APR estimate to balanced range price info display

- src/components/Global/DetailModals/TransactionDetailsGraph/TransactionDetailsGraph.tsx
- src/pages/platformAmbient/Chart/Liquidity/LiquiditySeries/AreaSeries.ts
- src/pages/platformAmbient/Chart/Liquidity/LiquiditySeries/LineSeries.ts
> fix tx details chart default colors

- src/components/Futa/SearchableTicker/TickerItem.module.css
- src/components/Futa/SearchableTicker/TickerItem.tsx
update tow highlighting
_Closes #0000_
> update row highlighting

- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
> fixed disappear liq depth chart for blast

- package.json
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
- fixed missing liquidity chart for ETH_USDB in depth mode
> Release 3.1.5

- src/components/Global/DropdownSearch/DropdownSearch.tsx
- src/components/Global/Sidebar/PoolsListItem.tsx
> hide token logos on futa swap

- src/components/Global/TutorialComponent/TutorialComponent.module.css
- src/components/Global/TutorialComponent/TutorialComponent.tsx
Blurry background effect which consists of 4 parts added for tutorial component 
_Closes #0000_
1.
2.
1.
2.
> Futa Tutorial | Blurry background effect

- src/pages/platformAmbient/Chart/Axes/yAxis/YaxisCanvas.tsx
- src/pages/platformAmbient/Chart/Liquidity/LiquiditySeries/AreaSeries.ts
- src/pages/platformAmbient/Chart/Liquidity/LiquiditySeries/LineSeries.ts
- src/pages/platformAmbient/Chart/OrderHistoryCh/OrderHistoryCanvas.tsx
- src/pages/platformAmbient/Chart/RangeLine/RangeLinesChart.tsx
- src/pages/platformAmbient/Chart/Volume/VolumeBarCanvas.tsx
> Proven update chart colors

- src/components/Form/Chip.tsx
- src/components/Global/Modal/Modal.module.css
- src/components/Global/Modal/Modal.tsx
- src/components/Global/SlippageTolerance/SlippageTolerance.tsx
- src/pages/Chart/ChartSettings/ChartSettings.tsx
- src/pages/Chart/ChartSettings/ChartSettingsCss.ts
- src/styled/Common/Types.ts
Address settings welcome frontend review
SWAP SETTINGS
Remove the purple border glow thing
Make the slippage preset buttons have the typical futa button style
Also change the presets to 0.5%, 1%, 5%. Memecoins can be very volatile
The toggle buttons need some color changes so they appear “on” properly
CHART SETTINGS
Remove the outer glow
The font in this modal is the old font Lexend
WELCOME
Remove the glow to the header section
_Closes #0000_
**Functionalities or workflows …
> Address settings welcome frontend review

- src/App/hooks/useSlippage.ts
- src/ambient-utils/constants/slippage.ts
- src/contexts/ChainDataContext.tsx
> update default slippage settings for L2s

- src/ambient-utils/dataLayer/functions/getFormattedNumber.ts
- src/components/Futa/SearchableTicker/TickerItem.tsx
- src/components/Futa/TickerComponent/tickerDisplayElements.tsx
> update number truncation

- src/contexts/AppStateContext.tsx
- src/pages/platformAmbient/Chart/Draw/Toolbar/Toolbar.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
increase time user must be idle before chart is deactivated from 20 minutes to 40 minutes
_Closes #0000_
1.
2.
1.
2.
> increase chart timeout to 40 minutes

- package.json
- src/ambient-utils/constants/networks/swellMainnet.ts
- fixed one of the Top Pools on Swellchain (rswETH instead of rsETH)
> fix top pools on swellchain

- src/pages/platformFuta/Home/FutaLandings/FutaLandingNav.module.css
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding.module.css
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding1.tsx
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding2.module.css
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding2.tsx
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding3.module.css
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding3.tsx
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding4.module.css
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding4.tsx
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding5.module.css
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaLanding5.tsx
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaNewLanding.module.css
- src/pages/platformFuta/Home/FutaLandings/NewLandings/FutaNewLanding.tsx
Add snap scroll to landing page
_Closes #0000_
1.
2.
1.
2.
> Add snap scroll to landing page

- src/components/Form/TokenInputQuantity.tsx
> limit pulse animation to token select buttons

- src/components/Global/NotificationCenter/NotificationCenter.tsx
- src/contexts/ReceiptContext.tsx
- src/contexts/SidebarContext.tsx
> clear tx notifications after opening block explorer

- src/components/Futa/SearchableTicker/SearchableTicker.tsx
Fixed : auction table scrolling when hovering over dots in scatter chart
> Proven style auctions

- package.json
- src/components/Global/TabComponent/TabComponent.tsx
> Remove redundant tab control

- src/contexts/AppStateContext.tsx
- src/pages/platformAmbient/Chart/Draw/Toolbar/Toolbar.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
> increase timeout for chart display to 60 minutes

- src/ambient-utils/api/fetchCandleSeries.ts
- src/ambient-utils/types/candleData/CandleDataIF.ts
- src/components/Global/DetailModals/TransactionDetailsGraph/TransactionDetailsGraph.tsx
- src/contexts/CandleContext.tsx
- src/pages/Chart/ChartSettings/ChartSettingsContent.tsx
- src/pages/platformAmbient/Chart/ChartUtils/candleDataUtils.ts
- removed liquidity chart from shareable chart
- liq color change options changed to ask on the left and bid on the right
- fix candle 0 price issues;
_Closes #0000_
1.
2.
1.
2.
> Remove liq chart from shareable chart

- src/components/Global/DetailModals/TransactionDetailsGraph/TransactionDetailsGraph.tsx
change which tick is used for drawing the limit line in tx details
1.
2.
1.
2.
> fix placement of limit line in tx details cards

- src/components/Global/TutorialComponent/TutorialComponent.module.css
Change z-index values of tutorial component elements to fix conflict with w3modal
_Closes #0000_
1.
2.
1.
2.
> Tutorial | Fix z-indexes on tutorial component to fix w3modal conflict

- src/components/Global/DetailModals/TransactionDetailsGraph/TransactionDetailsGraph.tsx
- Changed buy/sell overlays color in shareable charts
- Fixed : comma mid price issue
> Proven - use middle of limit fill for fill overlay

- src/assets/branding/plumeBrandAssets.ts
- src/components/Home/Landing/MobileLandingSections.tsx
- src/pages/platformAmbient/Home/Home.tsx
> fix display of disabled dex stats on mobile

- src/pages/platformFuta/Create/Create.module.css
- src/pages/platformFuta/Create/Create.tsx
- src/pages/platformFuta/Create/CreateInput.module.css
- src/pages/platformFuta/Create/CreateInput.tsx
> add frontend reviews for create

- src/components/Global/DetailModals/OrderDetails/OrderDetailsModal/OrderDetailsModal.tsx
- src/components/Global/DetailModals/TransactionDetailsGraph/TransactionDetailsGraph.tsx
> show average fill price in limit details card

- src/components/Trade/Limit/LimitRate/LimitRate.tsx
- src/pages/platformAmbient/Trade/Limit/Limit.tsx
> Set default limit line to 1 percent

- package.json
- yarn.lock
> bump crocswap sdk to fix rswETH vault withdrawal

- src/components/Futa/SearchableTicker/SearchableTicker.tsx
- src/pages/platformFuta/Account/Account.module.css
> fixed : Account page height for Futa design

- src/components/Error/GlobalErrorFallback.module.css
- src/components/Error/GlobalErrorFallback.tsx
- src/pages/platformAmbient/Trade/Trade.tsx
fixes the missing error message, line wrapping and add the current URL to the end of the copied details
- copied error messages on Safari were missing the custom error message
- displayed error messages were not line wrapping
- copied error details did not include the current URL
1.
2.
1.
2.
> Fix missing error details

- src/App/hooks/useFetchPoolStats.ts
> fix async pool card moneyness update

- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/plumeMainnet.ts
- src/components/Global/PoolCard/PoolCard.tsx
- src/components/Global/Sidebar/TopPools.tsx
- src/components/Home/TopPoolsHome/TopPoolsHome.tsx
- src/contexts/ExploreContext.tsx
> automatically update which pools are displayed on homepage

- src/index.tsx
remove Binance Wallet from the list of featured wallets
the Binance team has asked us to remove the Binance Wallet walletconnect option from being featured, since it appears to duplicate the options for connecting to Binance Web3 Wallet.
1.
2.
1.
2.
> remove Binance Wallet as featured wallet

- src/ambient-utils/constants/networks/blastMainnet.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/contexts/ExploreContext.tsx
- src/pages/platformAmbient/Explore/Explore.tsx
> check for hidden tokens when generating top pools

- src/components/Futa/Chart/ScatterChart/ScatterChart.tsx
- src/components/Futa/Chart/ScatterChart/Xaxis.tsx
> fixed : completed auctions scatter chart display weird

- src/contexts/CandleContext.tsx
> Fix reloading chart when user connect/disconnect

- src/App/components/PageHeader/MobileDropdown/MobileDropdown.tsx
- src/App/components/PageHeader/PageHeader.tsx
- src/components/Futa/Navbar/Navbar.tsx
- src/contexts/UserDataContext.tsx
Wallets aren't being fully disconnected when the disconnect button is clicked (upon reconnection the wallet isn't asking the user to confirm and to select the address to connect). This behavior is introduced in newer versions of web3modal/AppKit but backporting this is a lot easier than upgrading.
_Closes #0000_
1. Disconnect the wallet and connect it again, some wallets (e.g. browser extensions of Metamask and Rabby) will ask to confirm.
**Environmental …
> Revoke wallet permissions on disconnect

- src/ambient-utils/constants/blacklist.ts
- src/ambient-utils/constants/defaultTokens.ts
- src/ambient-utils/constants/testnet-token-list.json
> fix duplicate testnet token address

- src/components/Futa/Comments/CommentInput/CommentInput.tsx
> Users were able to send messages containing higher than 180 characters by copying and pasting text . It's fixed now.

- src/index.tsx
Detect running inside of Binance Wallet browser to prevent showing two Binance wallet options in web3modal.
_Closes #0000_
-   [X] Did I request feedback from a team member prior to the merge?
1. Check the list of featured wallets in the Binance Wallet and also anywhere else, there should only be one Binance option in all cases.
1.
2.
> Detect Binance Wallet

- src/components/Chat/ChatIFs.tsx
- src/components/Global/TutorialComponent/TutorialHelpModal/TutorialHelpModal.module.css
- src/components/Global/TutorialComponent/TutorialHelpModal/TutorialHelpModal.tsx
- src/components/Global/TutorialComponent/TutorialHelpModal/TutorialHelpModalContents.module.css
- src/components/Global/TutorialComponent/TutorialHelpModal/TutorialHelpModalContents.tsx
- src/components/Global/TutorialOverlay/TutorialOverlayUrlBased.module.css
- src/components/Global/TutorialOverlay/TutorialOverlayUrlBased.tsx
Help modal feature added into Tutorial Component.
`<TutorialHelpModal />` should be added as **helpModal.content** property into TutorialIF interface (with page prop)
Page prop is been used to decide content of Help Modal
Help Modal contents can be defined in `TutorialHelpModalContents.tsx` file.
Content with page prop can be associated in `TutorialHelpModal` component's `getModalContent()` method
_Sample scenario has been implemented for Auctions page in this PR_
_Closes #0000_
**Functionalities or workflows that should …
> Tutorial | Help modal

- package.json
- src/components/Form/Chip.tsx
- src/components/Form/Form.styles.ts
- src/components/Form/Icons/Icons.styles.tsx
- src/components/Global/Explore/TokenDisplay.tsx
- src/components/Portfolio/PortfolioBanner/PortfolioBannerAccount/NFTBannerAccountCss.ts
- src/components/Portfolio/ProfileSettings/ProfileSettings.styles.ts
- src/components/Trade/TableInfo/TableInfo.styles.ts
- src/pages/platformAmbient/InitPool/InitConfirmation.tsx
- src/pages/platformAmbient/InitPool/InitSettings.tsx
- src/pages/platformAmbient/InitPool/InitSkeleton.tsx
- src/styled/Common/Breakpoints.ts
- src/styled/Common/Container.ts
- src/styled/Common/ScrollContainer.ts
- src/styled/Common/Text.ts
- src/styled/Components/Chart.ts
- src/styled/Components/Home.ts
- src/styled/Components/Portfolio.ts
- src/styled/Components/Range.ts
- src/styled/Components/Sidebar.ts
- src/styled/Components/Trade.ts
- src/styled/Components/TradeModules.ts
- src/styled/Components/TransactionTable.ts
- src/styled/Components/Tutorial.ts
- vite.config.ts
- yarn.lock
remove unnecessary babel dependencies
_Closes #0000_
1.
2.
1.
2.
> remove unnecessary babel dependencies

- src/ambient-utils/dataLayer/functions/translateTokenSymbol.ts
- src/contexts/CrocEnvContext.tsx
> fix saving token selection to local storage for plume

- package.json
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/ambient-utils/types/NetworkIF.ts
- src/components/Home/TopPoolsHome/TopPoolsHome.tsx
add optional ability to hardcode a pool to display in the third Top Pools slot regardless of volume
_Closes #0000_
1.
2.
1.
2.
> Add priority pool to homepage

- src/App/hooks/useFetchPoolStats.ts
> fix disappearing pool price change display on homepage

- package.json
- fixed occasionally disappearing pool price change displays on homepage after switching chains
> Release 3.1.25

- src/pages/platformAmbient/Chart/Chart.tsx
> fixed: candle missing

- src/components/Futa/Navbar/Navbar.tsx
- src/components/Futa/SearchableTicker/SearchableTicker.tsx
decode urls before matching to determine if the tab is active in order to support URLs with an emoji
1.
2.
1.
2.
> fix futa Url decoding

- package.json
- yarn.lock
> update ethers to 6.13.5

- src/components/Global/TutorialComponent/TutorialHelpModal/TutorialHelpModal.module.css
- src/components/Global/TutorialComponent/TutorialHelpModal/TutorialHelpModal.tsx
Close icon added into tutorial help modal
_Closes #0000_
1.
2.
1.
2.
> Tutorial | Help modal close icon

- netlify/edge-functions/country-redirect.ts
update Netlify redirect function to redirect all traffic to a restricted site (i.e. a site domain beginning with "us.") to the non-us version.
_Closes #0000_
1.
2.
1.
2.
> update Netlify redirect function

- src/components/Home/TopPoolsHome/TopPoolsHome.tsx
- src/contexts/ExploreContext.tsx
> prevent intermittent top pools flashing

- src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
> fix swap update when adding preceding decimal point

- src/pages/platformAmbient/Vaults/Vaults.tsx
> run vaults queries concurrently

- package.json
- src/ambient-utils/dataLayer/functions/getFormattedNumber.ts
numbers like 0.00009999999999502 were being incorrectly determined to have 4 subscript zeros when after rounding they should only have three.
1.
2.
1.
2.
> fix subscript rounding bugs

- src/contexts/CandleContext.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
> fixed: candle pilling up on the right for pools like ETH/USDC.e

- src/components/Global/DetailModals/TransactionDetailsGraph/TransactionDetailsGraph.tsx
> fixed : chart gap left side on shareable charts

- src/App/components/PageHeader/UserMenu/UserMenu.module.css
- src/App/components/PageHeader/UserMenu/UserMenu.tsx
- src/components/Global/Modal/Modal.tsx
> add wallet to mobile header

- src/App/components/PageHeader/UserMenu/UserProfileCard.tsx
always link to /account when clicking the avatar or ENS/address in the wallet dropdown
the links in the wallet dropdown were incorrect after viewing another user's portfolio
1.
2.
1.
2.
> fix links to portfolio in wallet dropdown

- src/pages/platformAmbient/Chart/Liquidity/LiquidityChart.tsx
sample pools that occur:
- /trade/pool/chain=0x82750&tokenA=0x06eFdBFf2a14a7c8E15944D1F4A48F9F95F663A4&tokenB=0x6f2a1a886dbf8e36c4fa9f25a517861a930fbf3a
- /trade/pool/chain=0x18231&tokenA=0xD630fb6A07c9c723cf709d2DaA9B63325d0E0B73&tokenB=0xdddD73F5Df1F0DC31373357beAC77545dC5A6f3F
> fixed : liquidity highlighted lines broken

- src/components/Portfolio/PortfolioBanner/PortfolioBannerAccount/NFTBannerAccount.tsx
> fix NFT selector pop-up on large screens

- src/App/hooks/useTokenSearch.ts
- src/ambient-utils/dataLayer/functions/stablePairs.ts
prioritize pETH to appear below Native ETH and pUSD to appear below USDC
pETH and pUSD are at the bottom when just sorted alphabetically
1.
2.
1.
2.
> prioritize pETH & pUSD in token selector

- src/components/Trade/InfiniteScroll/useGenFakeTableRow.tsx
- src/components/Trade/InfiniteScroll/useMergeWithPendingTxs.tsx
Handling table update once limit order has been claimed
_Closes #0000_
1.
2.
1.
2.
> Limits Tab | Handle update for claims

- src/ambient-utils/types/limitOrder/LimitOrderIF.ts
- src/components/Global/Tabs/TableMenu/TableMenuComponents/OrdersMenu.tsx
- src/components/Trade/InfiniteScroll/useGenFakeTableRow.tsx
- src/components/Trade/InfiniteScroll/useMergeWithPendingTxs.tsx
- src/components/Trade/TradeTabs/Orders/Orders.tsx
- src/components/Trade/TradeTabs/useSortedLimits.ts
- src/pages/platformAmbient/Chart/Chart.tsx
> fix update of limit tab data for fill completion status

- src/components/Futa/Comments/Comments.tsx
Connection status indicator has been removed from Comments Panel
_Closes #0000_
1.
2.
1.
2.
> FUTA | Disable connection status indicator on Comments Panel

- src/components/Chat/ChatIFs.tsx
- src/components/Global/TutorialComponent/TutorialHelpModal/TutorialHelpModal.module.css
- src/components/Global/TutorialComponent/TutorialHelpModal/TutorialHelpModal.tsx
- src/components/Global/TutorialComponent/TutorialHelpModal/TutorialHelpModalContents.tsx
- src/components/Global/TutorialOverlay/TutorialOverlayUrlBased.tsx
- Showing help modal by default set for tutorial component
- Ambient version of help modal has been created
- Default help modal content objs created for both Ambient & Futa
- `noHelpModal` field added into TutorialIF to override default behaviour of component
- Tutorial component render rules and behaviour has been modified for recent changes
_Closes #0000_
1.
2.
1.
2.
> Tutorial | Show help modal by default

- package.json
- src/ambient-utils/constants/networks/plumeMainnet.ts
- yarn.lock
> update Plume RPC and explorer endpoints

- src/App/hooks/useDrawSettings.ts
- src/contexts/ChartContext.tsx
- src/pages/Chart/ChartSettings/ChartSettingsContent.tsx
> bugfix/ fix default color bug for context menu

- src/components/Futa/Comments/CommentCard/CommentCard.module.css
Coloring changed on comment cards css file to make it same with Firma document
_Closes #0000_
1.
2.
1.
2.
> Futa | Comments section color revisions

- src/components/Chat/FullChat/FullChat.tsx
- src/components/Chat/MessagePanel/Room/Room.module.css
- src/components/Chat/MessagePanel/Room/Room.tsx
> Go to current pool button

- src/components/Chat/ChatUtils.ts
- src/components/Chat/MessagePanel/Room/Room.tsx
> Remove emojis from room names except favorite ones

- src/components/Chat/MessagePanel/SentMessagePanel/SentMessagePanel.tsx
> -Removed network icon from room's message except Admins room

- package.json
- yarn.lock
> update vite to 6.1.0

- src/ambient-utils/constants/ambient-token-list.json
- src/ambient-utils/dataLayer/functions/bigIntReplacer.ts
- src/components/Trade/InfiniteScroll/useMergeWithPendingTxs.tsx
TypeError: Do not know how to serialize a BigInt
at JSON.stringify (<anonymous>)
at useMergeWithPendingTxs (http://localhost:3000/src/components/Trade/InfiniteScroll/useMergeWithPendingTxs.tsx?t=1739386944777:103:12)
at InfiniteScroll (http://localhost:3000/src/components/Trade/InfiniteScroll/InfiniteScroll.tsx?t=1739386944777:564:52)
at renderWithHooks (http://localhost:3000/node_modules/.vite/deps/chunk-IM75J4MN.js?v=253d29e6:11596:26)
at updateFunctionComponent (http://localhost:3000/node_modules/.vite/deps/chunk-IM75J4MN.js?v=253d29e6:14630:28)
at updateSimpleMemoComponent (http://localhost:3000/node_modules/.vite/deps/chunk-IM75J4MN.js?v=253d29e6:14511:18)
at updateMemoComponent …
> add bigInt replacer fn to fix crash

- src/App/hooks/usePoolList.ts
- src/contexts/ExploreContext.tsx
add getTokenByAddress function to list of dependencies for side effect
top pools / explore sometimes fails to load initially for first time users (or in incognito)
1.
2.
1.
2.
> fix loading top pools on some chain specific deployments

- package.json
- src/contexts/ExploreContext.tsx
prevent setting poollist from gcgo before timeout has expired
gcgo pool list would be set even if analytics pool list was available
1.
2.
1.
2.
> fix pool list fallback on gcgo

- src/contexts/ChainDataContext.tsx
- src/contexts/ExploreContext.tsx
- src/contexts/PoolContext.tsx
> fix gcgo fallback for pool list

- src/App/hooks/useFavePools.ts
fixed crash when user had previously saved favorite pools before the update to PoolIF and then opened the dropdown menu on /trade.
1.
2.
1.
2.
> fix favePools crash

- package.json
- src/components/Chat/MessagePanel/Room/Room.tsx
- fixed crash for some users opening the pool dropdown on /trade
> Release 3.2.7

- src/App/components/Sidebar/SidebarSearchResults/PoolsSearchResults/PoolSearchResult.tsx
- src/App/components/Sidebar/SidebarSearchResults/PoolsSearchResults/PoolsSearchResults.tsx
- src/App/hooks/useFetchPoolStats.ts
- src/App/hooks/useRecentPools.ts
- src/ambient-utils/dataLayer/functions/getPoolStats.ts
- src/ambient-utils/types/pool/PoolIF.ts
- src/components/Global/DropdownSearch/DropdownSearch.tsx
- src/components/Global/Explore/PoolRow/PoolRow.tsx
- src/components/Global/PoolCard/PoolCard.tsx
- src/components/Global/Sidebar/FavoritePools.tsx
- src/components/Global/Sidebar/PoolsListItem.tsx
- src/components/Global/Sidebar/RecentPools.tsx
- src/components/Global/Sidebar/TopPools.tsx
- src/components/Home/TopPoolsHome/TopPoolsHome.tsx
- src/contexts/ExploreContext.tsx
> display pool price on /explore instead of last swap price

- src/App/hooks/useFetchPoolStats.ts
- src/ambient-utils/types/pool/PoolStatIF.ts
- src/components/Global/PoolCard/PoolCard.tsx
- src/contexts/PoolContext.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeChartsComponents/PoolData.tsx
> fix pool price change display for new pools

- package.json
- src/ambient-utils/constants/networks/swellMainnet.ts
display KING / ETH pool on Swellchain in featured pool slot on homepage
_Closes #0000_
1.
2.
1.
2.
> add KING / ETH as featured pool

- src/contexts/ChainDataContext.tsx
- added KING / ETH as featured pool on Swellchain
> Release 3.2.11

- src/App/hooks/useFetchPoolStats.ts
- src/ambient-utils/api/fetchTokenPrice.ts
- src/ambient-utils/dataLayer/functions/getPoolStats.ts
- src/ambient-utils/dataLayer/functions/stablePairs.ts
- src/components/Form/RangeWidth/RangeWidth.tsx
- src/components/Global/PoolCard/PoolCard.tsx
- src/contexts/CrocEnvContext.tsx
- src/contexts/PoolContext.tsx
- src/contexts/TradeDataContext.tsx
> fix monad testnet token prices

- src/pages/platformAmbient/Chart/Chart.tsx
> y axis autoscale changed according to visibleCandleData

- src/pages/platformAmbient/Chart/Chart.tsx
> Order history circle size

- src/ambient-utils/api/fetchTokenPrice.ts
- src/components/Global/PoolCard/PoolCard.tsx
fix calculation of usd value
1.
2.
1.
2.
> fix homepage token price displays

- src/ambient-utils/api/fetchTokenPrice.ts
- src/ambient-utils/constants/index.ts
- src/components/Form/TokenInputWithWalletBalance.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
add flag to hide token values and value loss warnings on testnets
testnet users were getting worried about the loss of value for testnet swaps of testnet tokens with estimated fake values
1.
2.
1.
2.
> Add flag to hide token values and warnings

- package.json
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
> attempted fix for intermittent incorrect display of No Table Data component on portfolio

- src/pages/platformAmbient/Chart/Liquidity/LiquidityChart.tsx
- src/pages/platformAmbient/Trade/TradeCharts/TradeCandleStickChart.tsx
Data sample which reduces liqudity chart data to optimize fps on liq hovering
_Closes #0000_
1.
2.
1.
2.
> Liquidity Chart data sampling

- src/components/Trade/TradeTabs/TableRows.tsx
- src/components/Trade/TradeTabs/TradeTabs2.tsx
limit transactions table display on /trade to 100 rows
_Closes #0000_
1.
2.
1.
2.
> prevent accumulation of memory usage by active transactions table

- package.json
- src/App/hooks/usePoolMetadata.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/ambient-utils/constants/testnet-token-list.json
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- fixed bug causing delay when toggling the display of empty positions on /account
- possibly fixed bug causing errant display of the No Table Data component on account when the user has an open position
- improved performance of liquidity chart dollar estimate calculations on hover in pools with many positions
- improved performance of transactions table in pools with many positions
> Release 3.3.1

- package.json
- src/App/hooks/useFetchPoolStats.ts
- src/ambient-utils/api/fetchCandleSeries.ts
- src/ambient-utils/api/fetchTokenPrice.ts
- src/ambient-utils/constants/networks/monadTestnet.ts
- src/ambient-utils/constants/testnet-token-list.json
- src/ambient-utils/dataLayer/functions/stablePairs.ts
- src/assets/branding/ambientProductionBrandAssets.ts
- src/components/Form/TokenInputWithWalletBalance.tsx
- src/contexts/CandleContext.tsx
- src/index.tsx
- src/pages/platformAmbient/Chart/Chart.tsx
- src/pages/platformAmbient/Explore/Explore.tsx
- src/pages/platformAmbient/Explore/useTokenStats.ts
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
- yarn.lock
- added Monad Testnet to the production deploy network selector
- fixes various unnecessary on-chain calls
_Closes #0000_
1.
2.
1.
2.
> add monad testnet to ambient production deploy

- src/utils/batchedProvider.ts
Enable caching of responses to RPC requests to marginally reduce the frontend's RPC load.
_Closes #0000_
-   [X] Did I request feedback from a team member prior to the merge?
1. The entire frontend.
1. Users with lots of positions can have higher cache hit rate due to redundant liquidity and rewards calls.
> Enable RPC response cache

- src/ambient-utils/constants/networks/baseSepolia.ts
- src/ambient-utils/constants/networks/blastMainnet.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/ethereumSepolia.ts
- src/ambient-utils/constants/networks/scrollSepolia.ts
- src/contexts/ChainDataContext.tsx
updated the gas price fetching logic to ensure that the provider and chainId match before requesting the gas price estimate
sometimes the gas price would get stuck after switching chains
1.
2.
1.
2.
> fix bug causing gas price to revert after switching chains

- package.json
- src/App/hooks/useFetchPoolStats.ts
- src/ambient-utils/api/fetchCandleSeries.ts
- src/ambient-utils/types/pool/PoolStatIF.ts
- src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
- src/contexts/CandleContext.tsx
- yarn.lock
improve logic for determining if a pool has been initialized by checking the analytics server response, rather than on-chain.
_Closes #0000_
1.
2.
1.
2.
> improve pool init status check & candle loading

- package.json
- src/ambient-utils/api/fetchCandleSeries.ts
- src/ambient-utils/constants/testnet-token-list.json
- src/assets/images/tokens/MAMABTC.svg
- src/assets/images/tokens/exports.ts
- src/components/Global/DetailModals/TransactionDetailsGraph/TransactionDetailsGraph.tsx
> fix tx chart displays

- src/components/Trade/InfiniteScroll/InfiniteScroll.tsx
Merging hot transactions into sort type once page fetches new txs
_Closes #0000_
1.
2.
1.
2.
> Merge hot transactions with sort method

- src/App/hooks/usePoolMetadata.ts
- src/App/hooks/useSidebarSearch.ts
- src/ambient-utils/api/fetchBatch.ts
- src/ambient-utils/api/fetchPoolLimitOrders.ts
- src/ambient-utils/api/fetchPoolRecentChanges.ts
- src/ambient-utils/api/fetchPoolUserChanges.ts
- src/ambient-utils/api/fetchTokenPrice.ts
- src/ambient-utils/api/fetchUserPositions.ts
- src/ambient-utils/api/fetchUserRecentChanges.ts
- src/ambient-utils/dataLayer/functions/getPoolStats.ts
- src/ambient-utils/types/fetchBatch.ts
- src/components/Global/Explore/DexTokens/DexTokens.tsx
- src/components/Portfolio/PortfolioTabs/PortfolioTabs.tsx
- src/components/Trade/InfiniteScroll/useInfiniteScrollFetchers.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
- src/contexts/ChainDataContext.tsx
- src/contexts/ExploreContext.tsx
- src/contexts/GraphDataContext.tsx
- src/contexts/PoolContext.tsx
- src/pages/platformAmbient/Explore/Explore.tsx
- src/pages/platformAmbient/Explore/useTokenStats.ts
- improve efficiency of RPC calls from /explore
- add fallback on gcgo pool list when analytics list not available
_Closes #0000_
1.
2.
1.
2.
> improve efficiency of RPC calls from /explore

- src/contexts/ChainDataContext.tsx
> fix gcgo pool list fallback

- src/components/Trade/Limit/LimitRate/LimitRate.tsx
- src/pages/platformAmbient/Chart/Chart.tsx
For Chart;
1. Drag Limit Line
For Limit Component;
1.  Entering a value in the limit price input
> Fixed limit price calculation when limit line drag on chart or entering a value in the limit price input

- package.json
- src/contexts/AppStateContext.tsx
> Fix table loading on account

- src/components/Swap/SwapTokenInput/SwapTokenInput.tsx
> fix non-primary token input display when liquidity insufficient

- src/contexts/CandleContext.tsx
re-fetch latest candles when a new user transaction is indexed to update the chart more quickly
_Closes #0000_
1.
2.
1.
2.
> add candle fetch after new user transaction indexed

- index.html
> update home wallpager prefetch URI

- src/components/Global/InfoRow.tsx
- src/components/Global/Tooltip/Tooltip.module.css
- src/components/Global/Tooltip/Tooltip.tsx
- src/components/Global/TooltipComponent/TooltipComponent.tsx
> create new tooltip for confirmation modals

- src/pages/platformAmbient/Vaults/VaultActionModal/VaultWithdraw/VaultWithdraw.tsx
- src/pages/platformAmbient/Vaults/VaultRow/VaultRow.tsx
quantities with a comma were not displaying correctly
_Closes #0000_
1.
2.
1.
2.
> fix vault withdrawal qty display

- package.json
- src/ambient-utils/constants/networks/baseSepolia.ts
- src/ambient-utils/constants/networks/blastMainnet.ts
- src/ambient-utils/constants/networks/blastSepolia.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/ethereumSepolia.ts
- src/ambient-utils/constants/networks/monadTestnet.ts
- src/ambient-utils/constants/networks/plumeLegacy.ts
- src/ambient-utils/constants/networks/plumeMainnet.ts
- src/ambient-utils/constants/networks/plumeSepolia.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/ambient-utils/constants/networks/scrollSepolia.ts
- src/ambient-utils/constants/networks/swellMainnet.ts
- src/ambient-utils/constants/networks/swellSepolia.ts
> fix block explorer links

- package.json
- src/ambient-utils/constants/ambient-token-list.json
- src/assets/images/tokens/USDT0.svg
- src/assets/images/tokens/exports.ts
- src/components/Global/TokenIcon/processLogoSrc.ts
- src/components/Trade/TradeTabs/Orders/Orders.tsx
- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
- src/components/Trade/TradeTabs/Ranges/rangeRowConstants.tsx
- src/components/Trade/TradeTabs/Transactions/Transactions.tsx
> Add usdt0 on swell

- src/contexts/AppStateContext.tsx
- src/pages/platformAmbient/Vaults/VaultActionModal/VaultWithdraw/VaultWithdraw.tsx
- src/pages/platformAmbient/Vaults/VaultRow/VaultRow.tsx
> fix vaults balance display updates after transaction

- src/ambient-utils/api/fetchTokenPrice.ts
- src/components/Global/DetailModals/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx
- src/components/Global/DetailModals/RangeDetails/RangeDetailsSimplify/RangeDetailsSimplify.tsx
- src/components/LimitActionModal/LimitActionModal.tsx
- src/components/RangeActionModal/RangeActionModal.tsx
- src/components/Trade/TradeModules/SubmitTransaction/SubmitTransaction.tsx
- src/components/Trade/TradeModules/SubmitTransaction/TransactionSubmitted/TransactionSubmitted.tsx
- src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx
- src/utils/hooks/useProcessRange.ts
import button text incorrect when transaction submitted from portfolio while trade route on different token pair
1.
2.
1.
2.
> fix token import button on portfolio

- src/components/Global/Tabs/TableMenu/TableMenuComponents/OrdersMenu.tsx
- src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx
- src/components/Global/Tabs/TableMenu/TableMenuComponents/TransactionsMenu.tsx
- src/components/Trade/TradeTabs/Ranges/rangeRowConstants.tsx
- src/components/Trade/TradeTabs/Transactions/txRowConstants.tsx
> set active tab when user clicks copy button

- src/components/Trade/TradeTabs/Ranges/Ranges.tsx
> fix hidden hide empty positions toggle at medium screen widths

- package.json
- src/App/functions/approve.ts
- src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx
- src/pages/platformAmbient/InitPool/InitButton.tsx
- src/pages/platformAmbient/InitPool/InitPool.tsx
- src/pages/platformAmbient/Trade/Limit/Limit.tsx
- src/pages/platformAmbient/Trade/Range/Range.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
- src/pages/platformAmbient/Vaults/VaultActionModal/VaultDeposit/VaultDeposit.tsx
- yarn.lock
add support for reseting mainnet USDT approvals
_Closes #0000_
1.
2.
1.
2.
> add support for reseting mainnet USDT approvals

- src/ambient-utils/constants/blacklist.ts
> separate legacy ofac blacklist

- src/ambient-utils/dataLayer/functions/stablePairs.ts
- src/components/Swap/SwapExtraInfo/SwapExtraInfo.tsx
- src/components/Trade/Limit/LimitExtraInfo/LimitExtraInfo.tsx
- src/contexts/PoolContext.tsx
to be easier to understand, display avg. rate and final price in terms of USD when dollarization mode is enabled, instead of in terms of the token
1.
2.
1.
2.
> display swap impact estimates denominated in USD

- src/components/Global/TooltipComponent/TooltipComponent.tsx
> fix tooltip z-index bug

- src/App/hooks/useFetchPoolStats.ts
- fixes pool price update when switching networks with different native tokens
_Closes #0000_
1.
2.
1.
2.
> fix pool price update when switching networks 

- src/ambient-utils/api/fetchTokenPrice.ts
- src/ambient-utils/dataLayer/functions/stablePairs.ts
- src/components/Form/RangeWidth/RangeWidth.tsx
- src/components/Global/PoolCard/PoolCard.tsx
- src/components/Global/TransactionSettingsModal/TransactionSettingsModal.tsx
- src/components/RangeActionModal/RangeActionModal.tsx
- src/contexts/PoolContext.tsx
- src/contexts/TradeDataContext.tsx
- src/pages/platformAmbient/Trade/Range/Range.tsx
- src/pages/platformAmbient/Trade/Reposition/Reposition.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
consolidated logic in multiple places to determine if app should treat a token pair as if it were stable for purposes of determining default range width, slippage tolerance, etc.
_Closes #0000_
1.
2.
1.
2.
> consolidate logic for determining if token pair is "stable"

- src/components/Chat/MessagePanel/InputBox/MessageInput.module.css
- src/components/Chat/MessagePanel/InputBox/MessageInput.tsx
> mobile chart disappear after input box is activated in chat in ios

- package.json
- src/App/hooks/useFetchPoolStats.ts
- src/App/hooks/usePoolMetadata.ts
- src/contexts/PoolContext.tsx
- src/contexts/TradeDataContext.tsx
- src/contexts/TradeTokenContext.tsx
- src/utils/batchedProvider.ts
sometimes the pool price would be incorrect after switching pools
_Closes #0000_
1.
2.
1.
2.
> fix sometimes incorrect pool price on trade route

- src/components/Portfolio/PortfolioBanner/PortfolioBannerAccount/NFTBannerAccount.tsx
- src/components/Portfolio/PortfolioBanner/PortfolioBannerAccount/NFTBannerAccountCss.ts
Updated NFTBannerAccount.tsx, NFTBannerAccountCss.ts to fix issue where avatar selector is not displaying on medium screen widths
[
](url)
_Closes #0000_
1.
2.
1.
2.
> Avatar selector display at medium screen widths bug has solved

- package.json
- yarn.lock
> update vite plugins

- .github/workflows/playwright.yml
- .github/workflows/vitest.yml
Potential fix for [https://github.com/CrocSwap/ambient-ts-app/security/code-scanning/7](https://github.com/CrocSwap/ambient-ts-app/security/code-scanning/7)
To fix the issue, we will add a `permissions` block at the root level of the workflow. This block will specify `contents: read`, which is sufficient for the tasks performed in this workflow (e.g., checking out the repository and running tests). This change ensures that the workflow does not inadvertently inherit broader permissions from the repository.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 7: Workflow does not contain permissions

- package.json
- src/ambient-utils/constants/ambient-token-list.json
- src/ambient-utils/constants/blacklist.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
add new USDQ; hide old USDQ token on Scroll
_Closes #0000_
1.
2.
1.
2.
> add new usdq

- package.json
- src/App/hooks/useFetchPoolStats.ts
- src/App/hooks/useTokens.ts
- src/ambient-utils/api/fetchTokenBalances.ts
- src/ambient-utils/api/fetchTokenPrice.ts
- src/ambient-utils/constants/index.ts
- src/ambient-utils/constants/testnet-token-list.json
- src/ambient-utils/dataLayer/functions/tokenMap.ts
- src/contexts/ChainDataContext.tsx
- src/contexts/TokenContext.tsx
- src/contexts/TradeTokenContext.tsx
- src/pages/platformAmbient/Portfolio/Portfolio.tsx
- yarn.lock
- fixed bugs causing USD values for tokens to not periodically update during a user session
- fixed bug causing tokens not in the Ambient Token List to not have balances displayed in the token selector
_Closes #0000_
1.
2.
1.
2.
> fix USD value updates

- package.json
- src/ambient-utils/dataLayer/functions/memoizePromiseFn.ts
- src/components/Trade/TradeModules/TradeModuleSkeleton.tsx
- src/contexts/ChainDataContext.tsx
fix case where user acknowledges an unknown token and then opens the token selector to view balance
_Closes #0000_
1.
2.
1.
2.
> fix bug causing newly ack'd token to not get balance in token selector

- package.json
- src/assets/branding/plumeBrandAssets.ts
> remove plume legacy from plume.ambient.finance

- package.json
- src/ambient-utils/constants/networks/swellMainnet.ts
- yarn.lock
update swell block explorer endpoint
_Closes #0000_
1.
2.
1.
2.
> update swell block explorer endpoint

- package.json
- src/ambient-utils/types/vaults/allVaultsServerIF.ts
- src/pages/platformAmbient/Vaults/Vault.ts
- src/pages/platformAmbient/Vaults/VaultRow/VaultRow.tsx
- src/pages/platformAmbient/Vaults/Vaults.tsx
- yarn.lock
This PR replaces an API call to get user vault balances with onchain queries. It also [updates the SDK version](https://github.com/CrocSwap/sdk/pull/80) to bring in minor vault improvements.
_Closes #0000_
-   [X] Did I request feedback from a team member prior to the merge?
1. Vault interactions, switching chains/addresses afterwards.
1.
2.
> Use RPC calls for vault balances

- package.json
- src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
switch to using the effective conversion rate for determining whether to require the user to acknowledge a price change during swap confirmation.
_Closes #0000_
1.
2.
1.
2.
> use effective conversion rate for swap price warning

- package.json
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/components/Swap/ConfirmSwapModal/ConfirmSwapModal.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
- updated the logic for when to display price change warning on swap confirmation to use effective rate instead of final pool price
> Release 3.5.10

- package.json
- src/assets/branding/ambientProductionBrandAssets.ts
- added plume to production network selector
> release 3.5.13

- package.json
- src/ambient-utils/constants/ambient-token-list.json
This was necessary due to an incorrect Decimals value for stBTC on the Plume token list.
_Closes #0000_
1.
2.
1.
2.
> add stBTC on Plume to Ambient Token List

- package.json
- src/ambient-utils/constants/networks/plumeMainnet.ts
- src/pages/platformAmbient/Trade/Limit/Limit.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
- fixed warning message when user's gas token wallet balance is insufficient on a network with a non-ETH gas token
- added stBTC on Plume to Ambient token list to override a mistake in the Plume token list
> Release 3.6.4

- src/contexts/BrandContext.tsx
remove canto from network selector
_Closes #0000_
1.
2.
1.
2.
> remove canto from network selector

- package.json
- src/pages/platformAmbient/Vaults/VaultActionModal/VaultDeposit/VaultDeposit.tsx
> fix vault deposit verbiage

- netlify/functions/show-country.js
- package.json
- update to prevent potential function invocation error
> Release v3.7.1

- netlify.toml
- package.json
- src/App/components/PageHeader/PageHeader.tsx
- src/ambient-utils/constants/index.ts
added VITE_LINK_TO_PERPS_HOME environment variable to make the page header link to the homepage an external link in order to respect the redirect/proxy rules for the new perps app.
_Closes #0000_
1.
2.
1.
2.
> add external link to perps home

- netlify.toml
- package.json
- src/ambient-utils/constants/blacklist.ts
- removed Syria, North Macedonia and Serbia as these countries are no longer under general OFAC sanctions
- update the wallet address blacklist
_Closes #0000_
1.
2.
1.
2.
> update address and country blacklist

- package.json
- src/ambient-utils/constants/networks/scrollMainnet.ts
- fix vault value total calculation
> Release 3.7.5

- package.json
- src/App/hooks/useFastLaneProtection.ts
temporarily disable the option to enable MEV protection on Monad Testnet
_Closes #0000_
1.
2.
1.
2.
> Temp disable mev protection

- src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx
- src/App/hooks/useFastLaneProtection.ts
- src/App/hooks/useTokenPairAllowance.ts
- src/ambient-utils/constants/index.ts
- src/ambient-utils/constants/networks/baseSepolia.ts
- src/ambient-utils/constants/networks/blastMainnet.ts
- src/ambient-utils/constants/networks/blastSepolia.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/ethereumSepolia.ts
- src/ambient-utils/constants/networks/monadTestnet.ts
- src/ambient-utils/constants/networks/plumeLegacy.ts
- src/ambient-utils/constants/networks/plumeMainnet.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/ambient-utils/constants/networks/scrollSepolia.ts
- src/ambient-utils/constants/networks/swellMainnet.ts
- src/ambient-utils/constants/networks/swellSepolia.ts
- src/ambient-utils/types/NetworkIF.ts
- src/components/Form/WalletBalanceSubinfo.tsx
- src/components/Global/TransactionSettingsModal/TransactionSettingsModal.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
- move flag for enabling fastlane MEV protection to network definition (e.g. monadTestnet.ts)
- update fastlane contract fallback address
> reenable MEV protection on Monad

- package.json
- src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx
- src/App/hooks/useFastLaneProtection.ts
- src/App/hooks/useTokenPairAllowance.ts
- src/ambient-utils/constants/index.ts
- src/ambient-utils/constants/networks/baseSepolia.ts
- src/ambient-utils/constants/networks/blastMainnet.ts
- src/ambient-utils/constants/networks/blastSepolia.ts
- src/ambient-utils/constants/networks/ethereumMainnet.ts
- src/ambient-utils/constants/networks/ethereumSepolia.ts
- src/ambient-utils/constants/networks/monadTestnet.ts
- src/ambient-utils/constants/networks/plumeLegacy.ts
- src/ambient-utils/constants/networks/plumeMainnet.ts
- src/ambient-utils/constants/networks/scrollMainnet.ts
- src/ambient-utils/constants/networks/scrollSepolia.ts
- src/ambient-utils/constants/networks/swellMainnet.ts
- src/ambient-utils/constants/networks/swellSepolia.ts
- src/ambient-utils/types/NetworkIF.ts
- src/components/Form/WalletBalanceSubinfo.tsx
- src/components/Global/TransactionSettingsModal/TransactionSettingsModal.tsx
- src/contexts/ChainDataContext.tsx
- src/pages/platformAmbient/Trade/Swap/Swap.tsx
- updated Fastlane MEV protection router address
> Release 3.7.7

- src/App/components/PageHeader/PageHeader.module.css
- src/App/components/PageHeader/PageHeader.tsx
> create page header animation using css only
